### ISSUE TITLE
Admin Bro doesn't execute post save hooks on defined schemas

### ISSUE THREAD

**Issue by surfer77** [SoftwareBrothers/admin-bro#105]
I can update records from the admin but the post save hooks on my schema won't execute when updating from admin bros, is there a fix for this?

this is my code so far: 

```const AdminBro = require("admin-bro");
const AdminBroExpress = require("admin-bro-expressjs");

const AdminBroMongoose = require("admin-bro-mongoose");
const mongoose = require("mongoose");

const User = require("../models/user.js");
const Api = require("../models/api.js");
const Query = require("../models/query.js");
const Company = require("../models/company.js");
const Collection = require("../models/collection.js");
const Comment = require("../models/comment.js");

AdminBro.registerAdapter(AdminBroMongoose);

// Passing resources one by one
const adminBro = new AdminBro({
	resources: [
		{
			resource: Api,
			options: {
				listProperties: ["title", "approved", "updatedAt"],
				filterProperties: [
					"title",
					"approved",
					"updatedAt",
					"createdAt",
					"url",
					"totalUpvotes",
					"upvotes",
					"_id"
				]
			}
		},
		Company,
		{
			resource: Collection,
			options: {
				editProperties: ["title", "apis", "description"],
				// listProperties: ["title", "apis", "description"],
				properties: { description: { type: "richtext" } }
			}
		},
		Comment,
		{
			resource: Query,
			options: {
				listProperties: ["query", "createdAt"],
				editProperties: ["query", "approved"]
			}
		}
	],
	rootPath: "/admin",
	loginPath: "/login",
	branding: {
		companyName: "API List"
	}
});

router = AdminBroExpress.buildRouter(adminBro);

module.exports = router;
```

**Comment by wojtek-krysiak** [comment]
yep - that is true. I will think how to change that in the next release.

**Comment by douglas2428** [comment]
Hi, I would like to know if there is any update about this issue? thanks

**Comment by wojtek-krysiak** [comment]
sorry. Unfortunately, we didn't add it yet but there are action hooks where you can put any "wrapping" logic: 
* https://softwarebrothers.github.io/admin-bro-dev/BaseAction.html#.before and 
* https://softwarebrothers.github.io/admin-bro-dev/BaseAction.html#.after
We will definitely implement that but right now not sure exactly when - will try to update you in 2 weeks time

**Comment by douglas2428** [comment]
thanks very much, I already did it by modify the edit handler action, but I will check with the "after" solution also. Thanks :)

**Comment by endel** [comment]
I've managed to get post save working with mongoose like this:

```typescript
YourSchema.post('findOneAndUpdate', async function(doc, next){
  // ...
  next();
});
```

**Comment by wojtek-krysiak** [comment]
Unfortunately, we decided not to change the implementation because we will need to perform an additional query (update query doesn't return updated record, but we need it). 

@endel solution seems to solve all the issues.
