### ISSUE TITLE
There is no TypeORM adapter

### ISSUE THREAD

**Issue by bayraak** [SoftwareBrothers/admin-bro#111]
As an idea, I think TypeORM adapter is vital for the project

**Comment by agustif** [comment]
I would like to use typeorm myself too @wojtek-krysiak @michlask any plans on it? could you help giving directions where should one start if wanting to create a PR for it?

thanks for the project guys!

**Comment by wojtek-krysiak** [comment]
we are working on it. Will be ready probably in 2 weeks from now.

**Comment by agustif** [comment]
@Wojtek-krysiak that’s great news indeed, can’t wait to try it!!

**Comment by Arteha** [comment]
@bayraak , @agustif npm install [admin-bro-typeorm](https://www.npmjs.com/package/admin-bro-typeorm) :innocent:

**Comment by bayraak** [comment]
@Arteha Thank you very much for this :) I will try it now

**Comment by agustif** [comment]
> @bayraak , @agustif npm install [admin-bro-typeorm](https://www.npmjs.com/package/admin-bro-typeorm) 😇



> @bayraak Just need to fix some small filtering bugs and provide all data types. Will in the next version. Maybe this evening or on weekend.

Wow thank you so much @Arteha I hadn't seen the previous version will try it as soon as I can for our next launch! Thanks for coding it! Can't wait for next release too!

**Comment by bayraak** [comment]
@wojtek-krysiak Do we have any updates about this issue?

**Comment by wojtek-krysiak** [comment]
@bayraak - @Arteha build that - it can be found here: https://github.com/Arteha/admin-bro-typeorm, I've forked that, and added some changes (PR is here https://github.com/Arteha/admin-bro-typeorm/pull/2). Until it is not merged, you can use our forked version: https://github.com/SoftwareBrothers/admin-bro-typeorm

```
yarn add https://github.com/SoftwareBrothers/admin-bro-typeorm
```

We are continuously testing that but I think it is stable enough to give it a try.
