### ISSUE TITLE
Actions custom validation improvements

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/admin-bro#116]
Currently there is only one possibility to add custom validation when overwriting actions. If something is not valid we can only return in action object like this:
`{ record: { errors: { <fieldName>: <validationMessage> } } }`
Also there is no possibility to show Notification for general issue in form, but notification is there, because it is displaying for other build in informations.

**Comment by wojtek-krysiak** [comment]
ac: add docs about it

**Comment by wojtek-krysiak** [comment]
added support for throwing ValidationError and described everything here:  https://adminbro.com/tutorial-actions-validations.html
