### ISSUE TITLE
Custom actions http method

### ISSUE THREAD

**Issue by szymonpoltorakrst** [SoftwareBrothers/admin-bro#117]
Maybe I'm missing something but is it possible to specify what http method is used when calling custom action or is limited to `GET` only?

**Comment by wojtek-krysiak** [comment]
When you create new action - it handles all types of http methods. In the action handler you can then apply different logic to different actions. Check out the edit action as an example: https://softwarebrothers.github.io/admin-bro-dev/admin-bro_src_backend_actions_edit-action.js.html

**Comment by wojtek-krysiak** [comment]
OK - this issue is about allowing developers to change HTTP method of the autogenerated buttons in custom actions. So when the action button appears on the list (in the record action case) - developer should be able to modify it that instead of GET it sends POST request.

**Comment by wojtek-krysiak** [comment]
duplicates #114
