### ISSUE TITLE
Role based access control

### ISSUE THREAD

**Issue by pawarbr13** [SoftwareBrothers/admin-bro#118]
hi can we add role based access control using admin bro? i need to create mulitple roles like super admin ,admin,user...is it gonna help on it?

**Comment by wojtek-krysiak** [comment]
Right now the only way of simulating this is to use `isVisible` as a method for each action you create or override - https://softwarebrothers.github.io/admin-bro-dev/BaseAction.html#.isVisible - but this is just hiding actions in the UI.

This feature has to be added

**Comment by wojtek-krysiak** [comment]
I am working on that - should be available in a couple of days

**Comment by wojtek-krysiak** [comment]
updated that with version 1.0.0. 
Now there are 2 methods:
* https://softwarebrothers.github.io/admin-bro-dev/BaseAction.html#.isVisible for controlling the visibility of a given action
* https://softwarebrothers.github.io/admin-bro-dev/BaseAction.html#.isAccessible - for access control.

Each action takes invocation context as a parameter (https://softwarebrothers.github.io/admin-bro-dev/BaseAction.html#~Context) which has currently logged in admin.
