### ISSUE TITLE
Can't find PageBuilder class

### ISSUE THREAD

**Issue by singhravi1** [SoftwareBrothers/admin-bro#119]
Hi,

I'm not able to find the `PageBuilder` class anywhere hence not able to customize the dashboard.

I'm following this link, https://softwarebrothers.github.io/admin-bro-dev/tutorial-custom-dashboard.html

**Comment by wojtek-krysiak** [comment]
that tutorial is obsolete. Right now the way of changing the dashboard is to pass the react component: https://softwarebrothers.github.io/admin-bro-dev/tutorial-07-custom-dashboard.html 

See the example here: 
- https://github.com/SoftwareBrothers/admin-bro-example-app/blob/master/admin/index.js#L37
- and the actual component: https://github.com/SoftwareBrothers/admin-bro-example-app/blob/master/admin/components/dashboard.jsx

This is how the dashboard on https://admin-bro-example-app.herokuapp.com/admin is built.
