### ISSUE TITLE
Not able to login when NODE_ENV=production

### ISSUE THREAD

**Issue by robincsamuel** [SoftwareBrothers/admin-bro#120]
Authentication works fine on the development environment. But if I set the NODE_ENV to `production`, it won't. 

I see the server is still responding with 200 OK, but it's getting redirected to the login page.

Also, I noticed a warning,
```
express-session deprecated undefined resave option;
express-session deprecated undefined saveUninitialized option
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

Is there an option to use `mongoStore` instead?

**Comment by robincsamuel** [comment]
Closing this issue in favor of https://github.com/SoftwareBrothers/admin-bro-expressjs/issues/5

**Comment by kiminohero** [comment]
@robincsamuel  What was the solution ?

**Comment by robincsamuel** [comment]
> @robincsamuel What was the solution ?

It was because of secure cookie. I’ve updated [here](https://github.com/SoftwareBrothers/admin-bro-expressjs/issues/5#issuecomment-516450494)
