### ISSUE TITLE
Allow modifying the layout

### ISSUE THREAD

**Issue by robincsamuel** [SoftwareBrothers/admin-bro#121]
It'd be nice if there is an option to override the layout (`/src/frontend/layout-template.js`).

I see the page title is hardcoded and also the scripts come via CDN.  For some reason, unpkg.com was really slow last day and It'd faster with local references or maybe just bundle it.

<img width="921" alt="Screenshot 2019-08-02 at 12 32 38 PM" src="https://user-images.githubusercontent.com/4545992/62350899-ba8f1c00-b521-11e9-9ac2-d96d21a8a5cf.png">

**Comment by wojtek-krysiak** [comment]
Thanks for the idea. We will plan the development of the admin this month and I will take that into consideration.

**Comment by wojtek-krysiak** [comment]
this was closed along with #146
