### ISSUE TITLE
View only resource possible bug

### ISSUE THREAD

**Issue by szymonpoltorakrst** [SoftwareBrothers/admin-bro#122]
Assuming that I want to create read only view of resource, let's called `history` resource.
I've disabled other other actions:
```javascript
options: {
  actions: {
    delete: {
      isVisible: false,
    },
    new: {
      isVisible: false,
    },
    edit: {
      isVisible: false,
    },
  },
},
```
Now when there is nothing in DB I still see
 ![Screenshot 2019-08-13 at 12 42 33](https://user-images.githubusercontent.com/36701899/62935623-e33bcf00-bdc7-11e9-8c0e-d136d0c15d1a.png).
 Clicking "first record" link cause error `Cannot read property 'showFilter' of undefined`

**Comment by wojtek-krysiak** [comment]
it was fixed and released with 1.0.0 version - thanks
