### ISSUE TITLE
[Feature] Hooks

### ISSUE THREAD

**Issue by szymonpoltorakrst** [SoftwareBrothers/admin-bro#123]
Would it be possible to have hooks? Something like in Mongo model? For instance on crud actions something like: `beforeCreate`, `afterCreate`, `beforeEdit` etc? I know it can be done by overwriting controller actions but hooks sound like more elegant solution.

**Comment by wojtek-krysiak** [comment]
awesome idea - working on that

**Comment by wojtek-krysiak** [comment]
@szymonpoltorakrst I've just released version 1.0.0. There are 2 extra methods in the BaseAction interface: `before(request)` and `after(response)` - check them out: http://localhost:3000/BaseAction.html#.after
