### ISSUE TITLE
Default sort on index action

### ISSUE THREAD

**Issue by szymonpoltorakrst** [SoftwareBrothers/admin-bro#124]
Am I missing something or it is not possible to define default sort e.g. `desc` instead of `asc` ?

**Comment by wojtek-krysiak** [comment]
added this feature along with version 0.9.6 - check out the https://softwarebrothers.github.io/admin-bro-dev/global.html#ResourceOptions (sort property)

**Comment by KalleVuorjoki** [comment]
Is there an updated documentation somewhere for defining default sort? In 1.3.1 global.html doesn't have sort property anymore. Any hints to change sortBy to `desc` instead and `asc` and instead of first column in table use some other column (e.g. `record_publish_date`).

**Comment by wojtek-krysiak** [comment]
we moved the docs a little bit. It is here: https://softwarebrothers.github.io/admin-bro-dev/ResourceOptions.html#sort
