### ISSUE TITLE
Inaccurate Tutorial Documentation

### ISSUE THREAD

**Issue by eenewbsauce** [SoftwareBrothers/admin-bro#128]
Great product guys!

I tried to add `adminBro` to a new Express app last night and ran into a gotcha when setting up the database connection.

I was following along on this [page](https://softwarebrothers.github.io/admin-bro-dev/tutorial-03-passing-resources.html)

The issue arises because `mongoose.connect` is asynchronous. So the sample code results in an error being raised in `lib/backend/utils/resources-factory._convertDatabase ln: 54` because the `db` is a `Promise<pending>` at the time it is executed.

The specific sample code I'm referring to is this:

```JavaScript
const adminBro = require('admin-bro')
const AdminBroMongoose = require('admin-bro-mongoose')
const mongoose = require('mongoose')
AdminBro.registerAdapter(AdminBroMongoose)

// Initializ Database along with models
const mongooseDb = mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true })
const User = mongoose.model('User', { name: String, email: String, surname: String })
const Admin = mongoose.model('Admin', { name: String, email: String})

// Passing resources by giving entire database
const AdminBro = new AdminBro({
  databases: [mongooseDb],
  //... other AdminBroOptions
})
```

Please let me know if I can help out!

**Comment by wojtek-krysiak** [comment]
Thanks a lot for that. Already updated the docs: https://softwarebrothers.github.io/admin-bro-dev/tutorial-03-passing-resources.html
