### ISSUE TITLE
Use placeholder loaders for a less jumpy table interaction experience

### ISSUE THREAD

**Issue by jay-jlm** [SoftwareBrothers/admin-bro#131]
Because table content is paginated, simply changing the sort order in a column triggers a complete table refresh and displays a loader component while doing it, which creates a bit of a jumpy UX, imho.
To combat this problem, at work we use placeholder loaders such as this one (https://github.com/danilowoz/react-content-loader) , instead of traditional spinning / jumping / crawling loaders.
Supporting this kind of functionality would be a great addition to user experience.

**EDIT:**  an alternative approach would be to dim the current table rows until the new content is loaded. ( bitbucket uses this solution when you're browsing a paginated list of commits)

**Comment by wojtek-krysiak** [comment]
loader in list was added in version @1.2.0-beta.4 - btw thanks for the suggestion.
