### ISSUE TITLE
Arrays with nested schemas don't show the content

### ISSUE THREAD

**Issue by DyaryRaoof** [SoftwareBrothers/admin-bro#135]
I think this is the only feature that is not implemented by admin-bro team. Adding this would make it a fully fledged admin panel tool. 

Does the Admin-bro team have a plan for adding that feature too ? 
thanks.

**Comment by wojtek-krysiak** [comment]
Hi @DyaryRaoof, first of all - thanks for trying AdminBro!

Hmm - we already added nested schemas along with version 1.1 :) Take a look at this example: https://admin-bro-example-app.herokuapp.com/admin/resources/Complicated/actions/list

The schema for that is: https://github.com/SoftwareBrothers/admin-bro-example-app/blob/master/mongoose/complicated-model.js

So if they are not present in your App - maybe this is some kind of error. Could you write here the example schema you are trying to run with AdminBro?

**Comment by DyaryRaoof** [comment]
Hi  Wojciech.
Thank you for your response.
I have already upgraded the admin-bro package to the latest version.

and  this is the schema
const Place = mongoose.model('Place', new mongoose.Schema({
name: {
type: String,
required: true,
minlength: 1,
maxlength: 50
},

nameEn: {
type: String,
required: true,
minlength: 1,
maxlength: 50
},

description: {
type: String,
minlength: 15,
maxlength: 400,
required: true
},

phoneNumbers: {
type: [Object],
account: {
phoneNumber: Number,
owner: String,
},
required: true
},



tags : {
type: [String],
required : true
},

gpsCoordinates: {
type: Object,
longitude: {type : Number, requierd : true},
latitude: {type : Number, requierd : true},
required: true
},

services: {
type: [],
service: String,
description: String,
requierd: true
},

albums: {
type: Object,
required: true,
name : String,
nameEn: String,
items:{
type: Object,
dateCreated : {
type : Date,
default : Date.now
}
},
isAutoConvertToUSDEnabled:Boolean,
isAllItemsDeliveryEnabled : Boolean,
isEnglishAutomaticallyConvertedToKurdish : Boolean,
dateCreated : {
type : Date,
default : Date.now
}
},

socialMedia: {
type: Object,
required: true,
},

comments: Object,

images: {
type: [Buffer],
requied: true
},


rating: { type : Number, default : 0},
ratingByUsersCount : { type : Number, default : 0},

shares : { type : Number, default : 0},

favorites : { type : Number, default : 0},

views : { type : Number, default : 0},


category: {
type: mongoose.Schema.Types.ObjectId,
ref: 'Category'
},

subcategory: {
type: mongoose.Schema.Types.ObjectId,
ref: 'Subcategory'
},

workingHours: {
openingHour: String,
closingHour: String
},

isDeleted : {
type : Boolean,
default : false
},

distanceToUser : {
type: Number,
default : 0
},

isApproved : {
type : Boolean,
default : false
},

address : {
type : String,
required : true
},

coverImages: {
type : [String],
required : true
},

dateCreated : {
type : Date,
default : Date.now
},

isAutoConvertKurdishToEnglishEnabled : {
type : Boolean,
required : true
}

}));

**Comment by DyaryRaoof** [comment]
forgot to include the JSON that I that is generated before sending it to
the server :

{
  "_id": "5d6828bfd6beec301464dd30",
  "phoneNumbers": [
    {
      "phoneNumber": 70070700,
      "owner": "bbbssv"
    },
    {
      "phoneNumber": 7070400,
      "owner": "ebebebbeb"
    }
  ],
  "tags": [
    "sbsbbbss ",
    " sbsbbsbsbs"
  ],
  "services": [
    {
      "name": "dbebbns",
      "description": "sbbbsbsbsbsvssvvs"
    }
  ],
  "images": [],
  "rating": 0,
  "ratingByUsersCount": 0,
  "shares": 0,
  "favorites": 0,
  "views": 0,
  "isDeleted": false,
  "distanceToUser": 0,
  "isApproved": false,
  "coverImages": [
    "486HJ6120812U5GY0751JPEG_20190828_214536_675562972.jpg"
  ],
  "name": "hbbbb",
  "nameEn": " ",
  "description": "ssbbsbsbsbsdnbbsbsbbs",
  "gpsCoordinates": {
    "longitude": 45.4143095,
    "latitude": 35.6016466
  },
  "albums": [
    {
      "name": "ejh",
      "nameEn": " ",
      "items": [
        {
          "imageVariants": [
            {
              "imageURL": "ROHXUB4PDEXS1NBPTLFN20190719_022348.jpg",
              "isApproved": false,
              "dateCreated": "2019-08-29T22:33:47.265783",
              "isDeleted": false
            }
          ],
          "name": "whwbwbwbw",
          "nameEn": "",
          "isAutoConvertNameToEnglishEnabled": true,
          "tags": [
            "bssbbsbsn , shss"
          ],
          "priceIQD": 70700,
          "priceUSD": 58.916666666666664,
          "description": "bsbbbcaamababbbaaaba",
          "isDeliveryAvailable": true,
          "isDinarAutomaticallyConvertedToDollar": true,
          "itemIndex": 0,
          "albumIndex": 0,
          "isDeleted": false,
          "isApproved": false,
          "dateCreated": "2019-08-29T22:33:47.266414"
        }
      ],
      "isAutoConvertToUSDEnabled": true,
      "isAllItemsDeliveryEnabled": true,
      "isEnglishAutomaticallyConvertedToKurdish": true,
      "isApproved": false,
      "isDeleted": false,
      "dateCreated": "2019-08-29T22:33:14.228267"
    }
  ],
  "socialMedia": {
    "facebook": "",
    "instagram": "",
    "youTube": "bbbsb",
    "snapChat": "",
    "twitter": "",
    "googlePlus": "",
    "pinterest": ""
  },
  "comments": null,
  "category": "5d47b3caa81b633e444e022f",
  "workingHours": {
    "openingHour": "22:00",
    "closingHour": "22:00"
  },
  "address": "bbsbsss",
  "dateCreated": "2019-08-29T19:34:22.790Z",
  "isAutoConvertKurdishToEnglishEnabled": true,
  "__v": 0
}

**Comment by wojtek-krysiak** [comment]
You can define nested schemas and use that within your _root_ schema.

Example for phoneNumbers:

```
const PhoneNumbers = new mongoose.Schema({
  account: {
    phoneNumber: Number,
    owner: String,
  },
}, { _id: false })

const Place = mongoose.model('Place', new mongoose.Schema({
  ...
  phoneNumbers: {
    type: [PhoneNumbers],
    required: true
  },
  ...
}));

```

And in the admin panel everything should be ok.

**Comment by DyaryRaoof** [comment]
Thank you so much Wojciech. Works like magic. You made my life so much easier not having to go out and build an admin panel from scratch. Please keep up the good work. Take care.

Sent from Mail for Windows 10

**Comment by DyaryRaoof** [comment]
Sorry for asking too many questions , but one last question : Every thing works fine for tow level of nesting but not more.

in the lower schema i have albums array, each album in the array has an item array, each item in that array has an imageVariant array witch intern has a few properties like ImageURL, dateCreated and so on.

The problem is Admin-bro doesn't show any items in an album and I am sure that I have set up everything correctly. I have checked like 50 times.

here is the my schemas : 


const PhoneNumber =  new mongoose.Schema({
    phoneNumber: Number,
    owner: String,
});

const GpsCoordinate =  new mongoose.Schema({
    latitude: Number,
    longitude : Number,
});

const Service =  new mongoose.Schema({
    name: String,
    description: String,
});

const ImageVariant =  new mongoose.Schema({
    imageURL : String,
    isApproved: Boolean,
    dateCreated : {
        type : Date,
        default : Date.now
    },
    isDeleted: Boolean
});


const Item = new mongoose.Schema({
    // imageVariants : [ImageVariant],
    name : String,
    nameEn : String,
    isAutoConvertNameToEnglishEnabled : Boolean,
    tags : [String],
    priceIQD : Number,
    priceUSD : Number,
    description : String,
    isDeliveryAvailable : Boolean,
    isDinarAutomaticallyConvertedToDollar : Boolean,
    itemIndex : Number,
    albumIndex : Number,
    isDeleted : Boolean,
    isApproved : Boolean,
    dateCreated : {
        type : Date,
        default : Date.now
            }
        }
    );

const Album = new mongoose.Schema({
    name : String,
    nameEn : String,
    items : [Item],
    isAutoConvertToUSDEnabled : Boolean ,
    isAllItemsDeliveryEnabled : Boolean,
    isEnglishAutomaticallyConvertedToKurdish : Boolean,
    isApproved : Boolean,
    dateCreated :{
        type : Date,
        default: Date.now
    },
    isDeleted : Boolean
});


const SocialMedia =  new mongoose.Schema({
    facebook : String,
    instagram : String,
    youTube :String,
    snapChat : String,
    twitter : String,
    googlePlus : String,
    pinterest : String
});

const User =  new mongoose.Schema({
    name : String,
    socialMedia : SocialMedia,
    email : String,
    password : String,
    isApproved : Boolean,
    dateCreated : {
        type : Date,
        default : Date.now
    },
    isDeleted : Boolean,
    profileImageURL : Boolean
});

const Comment =  new mongoose.Schema({
   user : [User],
   userId :{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
   },
   text : String,
   dateCreated : {
       type : Date,
       default: Date.now
   }
});

const WorkingHour =  new mongoose.Schema({
    openingHour: String,
    closingHour: String
});

const CoverImage =  new mongoose.Schema({
    imageURL : String,
    isApproved : Boolean,
    dateCreated : {
        type :Date,
        default : Date.now
    }
});


const Place = mongoose.model('Place', new mongoose.Schema({
    name: {
        type: String,
        required: true,
        minlength: 1,
        maxlength: 50
    },

    nameEn: {
        type: String,
        required: true,
        minlength: 1,
        maxlength: 50
    },

    description: {
        type: String,
        minlength: 15,
        maxlength: 400,
        required: true
    },

    phoneNumbers: {
        type: [PhoneNumber],
        required: true
    },



    tags : {
        type: [String],
        required : true
    },

    gpsCoordinates: {
        type: GpsCoordinate,
        requied : true

    },

    services: {
        type: [Service],
        requied : true
    },

    albums: {
        type: [Album],
        required: true,
    },

    socialMedia: {
        type: SocialMedia,
        required: true,
    },

    comments: [Comment],

    rating: { type : Number, default : 0},

    ratingByUsersCount : { type : Number, default : 0},

    shares : { type : Number, default : 0},

    favorites : { type : Number, default : 0},

    views : { type : Number, default : 0},

    category: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Category',
        require : true
    },

    subcategory: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Subcategory',
        required : true
    },

    workingHours: {
       type : WorkingHour,
       required : true
    },

    isDeleted : {
        type : Boolean,
        default : false
    },

    distanceToUser : {
        type: Number,
        default : 0
    },

    isApproved : {
        type : Boolean,
        default : false
    },

    address : {
        type : String,
        required : true
    },

    coverImages: {
        type : [CoverImage],
        required : true
    },

    dateCreated : {
        type : Date,
        default : Date.now
    },

    isAutoConvertKurdishToEnglishEnabled : {
        type : Boolean,
        required : true
    },

    user : {
        type : User,
        required : true
    },


}));

and the server handling of requests : 



    reqJson = JSON.parse(req.body.json);
    var place = new Place({
        name: reqJson.name,
        nameEn : reqJson.nameEn,
        description: reqJson.description,
        tags: reqJson.tags,
        phoneNumbers: reqJson.phoneNumbers,
        gpsCoordinates: reqJson.gpsCoordinates,
        services: reqJson.services,
        albums: reqJson.albums,
        socialMedia: reqJson.socialMedia,
        comments : reqJson.comments,
        rating: 0,
        category: reqJson.category,
        subcategory: reqJson.subcategory,
        secondHand: reqJson.secondHand,
        workingHours : reqJson.workingHours,
        isDeleted : reqJson.isDeleted,
        isApproved : reqJson.isApproved,
        address : reqJson.address,
        coverImages: reqJson.coverImages,
        dateCreated : reqJson.dateCreated,
        isAutoConvertKurdishToEnglishEnabled : reqJson.isAutoConvertKurdishToEnglishEnabled,
        user : reqJson.user,

    });

Thanks.

**Comment by wojtek-krysiak** [comment]
ok - I see that it doesn's work with this level of complicity. I will try to figure out why, and get back to you

**Comment by DyaryRaoof** [comment]
Ok. Great.

**Comment by DyaryRaoof** [comment]
Hi Wojciech. I didn’t hear back from you. I though you might have forgotten about me. 😊

**Comment by wojtek-krysiak** [comment]
Currently, we are working on [better-docs](https://github.com/SoftwareBrothers/better-docs) and finishing this next week after that I will get back to you with a solution.

**Comment by DyaryRaoof** [comment]
OK. Great. I will be waiting for your reply.

Sent from Mail for Windows 10

**Comment by wojtek-krysiak** [comment]
@DyaryRaoof - it is finally fixed with version `admin-bro@1.2.0-beta.2` please check that out and let me know if that helped.

**Comment by DyaryRaoof** [comment]
Thank you so much. I’ll test it tomorrow when i have time and will get back to you.

**Comment by DyaryRaoof** [comment]
Works perfectly thank you so much for your time and effort Admin-bro team

**Comment by DyaryRaoof** [comment]
I there a chance that you may add functionality for arranging order of data by other fields other than the visible fields in the future ? [https://ibb.co/Dg9qcP5](url)

**Comment by TheMisir** [comment]
@wojtek-krysiak , Does nested objects works with sequelize? Is there any example on sequelize nested objects?

I tried but it did not worked. Server sends nested data within response but UI doesn't contains nested fields for editing/creating/displaying data.

**Comment by wojtek-krysiak** [comment]
we don't support nested objects in sequelize (tbh I didn't know such things exists). @TheMisir you can create additional issue with example schema so we will put that to the backlog

**Comment by TheMisir** [comment]
I'm rewriting sequelize adapter with nested object support. I will create PR if it worked.

**Comment by wojtek-krysiak** [comment]
I've just published support for arrays in Sequelize adapter. Download the latest admin-bro and admin-bro-sequelize and try it out
