### ISSUE TITLE
Component1 is not defined

### ISSUE THREAD

**Issue by Diktat0ren** [SoftwareBrothers/admin-bro#136]
I'm attempting to render a property with a custom component, but it won't work and the console is showing me this error: 

> components.bundle.js:9 Uncaught ReferenceError: Component1 is not defined
    at components.bundle.js:9

I literally copy pasted the example from the docs to make sure i wasn't doing anything wrong, but it doesn't work. 

Also I've seen that some places in the docs you use components: {} instead of component: {}

This is how im trying to do it:
` 
{
      resource: Voyage,
      options: {
        properties: {
          status: {
            component: {
              list: AdminBro.require('./city-content-in-list'),
            },
          },
        },
      },
    },`

the component is a copy paste of your example in the docs.

What confuses me is that in your repo admin-bro-example-app you add a custom component to the article field, but you apply the component like this:

`properties: {
    _id: { isVisible: false },
    content: {
      type: 'richtext',
    },
    published: {
      label: 'Published (custom render)',
      components: {
        list: AdminBro.require('../components/article-in-list')
      }
    }
  }`
What's the difference between those two?
If i use components i get another error 
(Invariant Violation: Element type is invalid) apparently it got undefined?

Anyway i just dont understand why it doesn't work when I've followed the docs closely!

**Comment by Diktat0ren** [comment]
And even more confusing, on page https://softwarebrothers.github.io/admin-bro-dev/BasePropertyComponent.html 

you apply the component like this
`        name: {
          components: {
            show: AdminBro('./my-react-component'),
          },`

No AdminBro.require() ?

**Comment by wojtek-krysiak** [comment]
Hi @Diktat0ren - first of all, thanks for trying AdminBro. I will answer in points:

1. `components` (plural) is used to modify property (because you can pass there multiple components: for _list_, _show_ etc), `component` (singular) to modify _action_ and _dashboard_ (only one component per dashboard/action).

In the example you posted:

```
{ resource: Voyage, options: { properties: { status: { component: { list: AdminBro.require('./city-content-in-list'), }, }, }, }, },
```
you use `component` instead of `components`

2. In the example component from the docs there was no `export default` statement - so when you copied that - it caused an error. Simply add:

```(javascript)
export default Dashboard
```
at the end of the file. PS (I already updated the docs).

3. Yes, there was a typo in the docs (BasePropertyComponent.html) - already fixed that - of course, it should have been AdminBro.require - Thank you for spotting that!

Please let me know if that helped. In case of any other questions/problems (especially with the not-so-clear documentation) also let me know by opening another issue.

**Comment by Diktat0ren** [comment]
Thanks for the clarification, however my custom component did have an export default, so when i changed component to components it caused this error as i mentioned before:

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Ri`.
See development console for more details...

Soo now my resource looks like this:
`options: { properties: { status: { components: { list: AdminBro.require('./city-content-in-list')}},},`

and the city-content-in-list is the same as the one in your docs (mentioned on /tutorial-04-customizing-resources.html)

Am i missing something?

**Comment by wojtek-krysiak** [comment]
1. which AdminVersion are you using?
2. could you paste exact content of your `./city-content-in-list` file?
3. Try to change ./city-content-in-list to something like this:
```
import React from 'react'

const component = (props) => {
  return (
     <div>Is it working?</div>
  )
}

export default component
```

if that works try to change it to:
```
import React from 'react'

export default class ArticleInList extends React.PureComponent {
  render() {
    const { record, property } = this.props
    const value = record.params[property.name]
    
    return (
      <span>{value ? <i className="far fa-thumbs-up" /> : <i className="far fa-thumbs-down" />}</span>
    )
  }
}
```

this is from the example app.

And let me know how that worked.

**Comment by Diktat0ren** [comment]
1. version 1.13
2. 

```
// city-content-in-list.jsx
import React from 'react'

const CityContentInList = (props) => (
  <div>Some custom content...</div>
)

export default CityContentInList
```

3. Same error

**Comment by Diktat0ren** [comment]
And in the console i get tons of erros with the same message, but i also still get this one:
`components.bundle.js:9 Uncaught ReferenceError: Component1 is not defined
    at components.bundle.js:9`

**Comment by Diktat0ren** [comment]
This is my full project file, it's a bit messy since i'm just trying to get it to work
Everything else works btw (x is just a placeholder for a sensitive name)
```
const AdminBro = require('admin-bro')
const AdminBroExpress = require('admin-bro-expressjs')
const AdminBroSequalize = require('admin-bro-sequelizejs')
const bodyParser = require('body-parser')
const express = require('express')
const app = express()
app.use(bodyParser.json())
AdminBro.registerAdapter(AdminBroSequalize); 
const portalDb = require('./models/portal')
const x= require('./models/x')

const run = async() => {
const adminBro = new AdminBro({
  databases: [portalDb.sequelize, x.sequelize],
  resources: [
    {resource: portalDb.sequelize.models.user, options:{parent:"Portal", name:"User"}},
    {resource: x.sequelize.models.charterer, options:{parent:"x", name:"x"}},
    {resource: x.sequelize.models.voyage, options:{parent:"x", name:"Voyages"}},
    {
      resource: x.sequelize.models.voyage_meta,
      options: {
        properties: {
          status: {
            components: {
              list: AdminBro.require('./city-content-in-list')
            }
          },
        },
        parent:"x",
        name:"Voyage Meta"
      },
    },
    {resource: x.sequelize.models.vessel, options:{parent:"x", name:"Vessels"}},
    {resource: x.sequelize.models.port, options:{parent:"x", name:"Ports"}},
    {resource: x.sequelize.models.cargo, options:{parent:"x", name:"Cargoes"}},
    {resource: x.sequelize.models.cargo_parcel, options:{parent:"x", name:"Cargo Parcels"}},
    {resource: x.sequelize.models.canal, options:{parent:"x", name:"Canals"}},
    {resource: x.sequelize.models.vessel_consumption, options:{parent:"x", name:"Vessel Consumptions"}},
    {resource: x.sequelize.models.client, options:{parent:"x", name:"Clients"}},
    {resource: x.sequelize.models.region, options:{parent:"x", name:"ETA Regions"}},
    {resource: x.sequelize.models.region_port, options:{parent:"x", name:"ETA Region Ports"}},
    {resource: x.sequelize.models.geo_region, options:{parent:"x", name:"Geo Regions"}},
    {resource: x.sequelize.models.geo_region_port, options:{parent:"x", name:"Geo Region Ports"}},
    {resource: x.sequelize.models.bunker_price, options:{parent:"x", name:"Bunker Prices"}},
  ],
  rootPath: '/admin',
  branding: {
    companyName: "WDS Admin",
    softwareBrothers:false,
  }
})
const router = AdminBroExpress.buildRouter(adminBro)
app.use(adminBro.options.rootPath, router)
app.listen(8080, () => console.log('AdminBro is under localhost:8080/admin'))
}

run();
```

**Comment by wojtek-krysiak** [comment]
give me sec - will try to run that. Aparently for some reason AdminBro cannot bundle your project.

Please check those things out:
1. When you open your Browser and write `AdminBro.UserComponents` in Chrome console do you have object with key: Component1 ?
2. can you paste the error from the terminal (not from chrome but from the terminal where you run the nodejs app)
3. In the meanwhile, I will try to run your app on my mac.

**Comment by Diktat0ren** [comment]
1. Nope, empty object.
2. Good idea, i didnt even think about that, here it is:

> 'F:devwinedarkseacoukappsadminBroapisrccity-content-in-list' is imported by .adminbro\.entry.js, but could not be resolved – treating it as an external dependency
No name was provided for external module 'F:devwinedarkseacoukappsadminBroapisrccity-content-in-list' in output.globals – guessing 'Component1'

Maybe this explains it?

**Comment by wojtek-krysiak** [comment]
ok - we are closer - AdminBro crates a hidden folder `.adminbro` and there is an `.entry.js` file (base on that it creates a bundle) - can you paste its content (bases od the log you provider there should be an error in a path).

Are you using Windows?

**Comment by wojtek-krysiak** [comment]
BTW entry.js should look something like that:
```
AdminBro.UserComponents = {}
import Component1 from '/path-to-your-component/city-content-in-list'
AdminBro.UserComponents.Component1 = Component1
```

**Comment by Diktat0ren** [comment]
Yep i am on Windows. This is the contents of the file:

> AdminBro.UserComponents = {}
> import Component1 from 'F:\dev\winedarkseacouk\apps\adminBro\api\src\city-content-in-list'
> AdminBro.UserComponents.Component1 = Component1

I think the path is accurate? When i right click it and select properties on Windows it says this is the location:

> F:\dev\winedarkseacouk\apps\adminBro\api\src

only problem i could see is that it doesn't have the .jsx file extension, but even adding that makes no difference

**Comment by wojtek-krysiak** [comment]
OK - so I think it is a Windows issue - I will try to debug it tomorrow (I don't have a windows machine right now) and will let you know.

Meanwhile, can you try it with docker?

**Comment by Diktat0ren** [comment]
I don't have Docker set up, but i will try tonight and let you know if it makes any difference 👍

**Comment by Diktat0ren** [comment]
Okay i deployed it on my Ubuntu staging server and it works perfectly fine on there, so it's definitely a Windows issue. Question is whether or not this is a problem with my system?

**Comment by subhasis020299** [comment]
I have been facing the same issue on Windows 10. It has something to do with the absolute path of the import file . 
The entry.js file looks something like this :

`AdminBro.UserComponents = {}
import Component1 from 'E:\Projects\ORSI\routes\profile-photo'
AdminBro.UserComponents.Component1 = Component1`

I think the backward slashes in the absolute file name is causing all the trouble. Is there a way to set the relative filename for these imports in entry.js ?

**Comment by fernandocucci** [comment]
Seems like a Windows issue... Having the same problem in my computer, deployed to Heroku and works fine over there.
In my case I noticed that the error that I get in the console doesn't have the "\":
```
'C:Documentsodecomponent1' is imported by .adminbro\.entry.js, but could not be resolved – treating it as an external dependency
No name was provided for external module 'C:Documentsodecomponent1' in output.globals – guessing 'Component1'.
```
Also, it's missing a letter (says **odecomponent1** instead of **nodecomponet1**).

**Comment by wojtek-krysiak** [comment]
can you try out the 1.1.5-beta.2 version? - I changed absolute paths to relative - this should help.

**Comment by Chukstart** [comment]
> can you try out the 1.1.5-beta.2 version? - I changed absolute paths to relative - this should help.
This is the output of my hidden adminbro file
AdminBro.UserComponents = {} import Component1 from '..\routes\my-dashboard-component' AdminBro.UserComponents.Component1 = Component1

This is the error that I'm getting or rather output
outesmy-dashboard-component' is imported by .adminbro\.entry.js, but could not be resolved – treating it as an external dependency outesmy-dashboard-component' in output.globals – guessing 'Component1'

This is how I'm importing the component
dashboard: { component: AdminBro.require('./my-dashboard-component') }
what I'm i doing wrong?

**Comment by dogleg69** [comment]
I believe the issue is in the admin-bro/src/backend/generate-user-component-entry.js

It uses path.relative to build a partial path that is written into the .adminbro/.entry.js file.  However, using path.relative on Windows will return the relative path in Windows format (ie with a single backslash).  That causes node to read it as an escape character.  

Need to fix by hack like path.relative(absoluteEntryPath, UserComponents[componentId]).replace(/\\/g, '/')

or use a library with a toUnix or ...

But please fix as I don't want to have my own copy of Admin-Bro.  Thanks for putting this together.  I am enjoying it.

**Comment by wojtek-krysiak** [comment]
Hi - I forced `path` to always use posix (linux) paths. Can you please test that out - version: `1.4.0-beta.3`

**Comment by dogleg69** [comment]
Unfortunately that caused other functions to break.  I was using relative path to display an image in a list.  In the properties of that resource, I pass in '../components/image-in-list' which is relative to the resource file and points to a .jsx file.  

Now in the Admin-bro.js Bundle(src) method, I get:

```
    Given file "../components/image-in-list", doesn't exist.
    More information can be found at: https://softwarebrothers.github.io/admin-bro-dev/AdminBro.html

    at Function.bundle (W:\x1\apps\dev\admin_gui_bro\node_modules\admin-bro\lib\admin-bro.js:238:13)
```

I see how you are getting the path by using the Error().stack and parsing it.  That looks good to me but the call to _path.posix.dirname(m[1]) is returning "."

So when you join . with src, you basically don't have what you passed in as src in the first place.  I have changed the line:

`  filePath = _path.posix.join(_path.posix.dirname(m[1]), src);`

to

`  filePath = _path.posix.join(_path.dirname(m[1]), src);`

and it seems to be working.  However, that causes another problem when loading a  component:

Error: Could not resolve '../../components/image-in-list' from .adminbro\.entry.js

I will try to find some time to look into this further, but this was a step back for me as now the code is not longer working.  Thank you for rewriting though.

**Comment by wojtek-krysiak** [comment]
thanks for the info. There is a https://github.com/sindresorhus/slash library - I will use that and this should solve this issue (tomorrow)

**Comment by wojtek-krysiak** [comment]
can you try `admin-bro@1.4.0-beta.15`

**Comment by dogleg69** [comment]
Thank you.  This is working.  I appreciate you fixing it.  I have a question/enhancement request, but will open it in another thread.  I believe this issue can be closed.  Thank you again.
