### ISSUE TITLE
Koa support

### ISSUE THREAD

**Issue by gabalicious** [SoftwareBrothers/admin-bro#137]
Original desc: Any plans to write a Admin Bro plugin that integrates with Koa framework?

In this task we will have to build koa support. It should be similar to express, which exports 2 functions:
- buildRouter
- buildAuthenticatedRouter

koa also have routers so the same principles could be used.

**Comment by wojtek-krysiak** [comment]
probably next month - until then you can simply use express and launch admin on a different port.

**Comment by gabalicious** [comment]
oh nice! good work around!

**Comment by johnstan** [comment]
Any update on a potential koa plugin? Admin Bro is awesome, but since we use heroku and already serve our APIs etc via the web dyno we aren't able to serve the admin on a different port. Causing a few headaches!

**Comment by wojtek-krysiak** [comment]
nop - I see that there are lots of other more urgent issues and we need to focus on them atm. 

But writing a plugin is not super hard - take a look at express.js plugin and maybe you will be able to write it on your own (it is a matter of mapping AdminBro routes)

**Comment by johnstan** [comment]
No worries - we managed to get the Express one working inline with Koa on the same server and port so all is well!

**Comment by wojtek-krysiak** [comment]
check out @admin-bro/koa
