### ISSUE TITLE
Cannot read property 'showFilter' of undefined

### ISSUE THREAD

**Issue by alexgilbertDG** [SoftwareBrothers/admin-bro#138]
When I try to select my item inside the admin and click on Info or Edit, this error popup.

Version:
    "admin-bro": "^1.1.4",
    "admin-bro-expressjs": "^0.2.0",
    "admin-bro-mongoose": "^0.3.0",

Error in console:
`
   Uncaught TypeError: Cannot read property 'showFilter' of undefined
    at wa (app.bundle.js:14924)
`

My code:
`

     const set = (db) => {

	let store = null

	if (process.env.NODE_ENV === 'production') {
		// stores state with redis
		store =
			new RedisStore({
				host: '127.0.0.1',
				port: 6379
			})

	} else {
		store = new ExpressBrute.MemoryStore() // stores state locally, don't use this in production
	}

	const bruteforce = new ExpressBrute(store)

	try {

		AdminBro.registerAdapter(AdminBroMongoose)

		const adminBro = new AdminBro({
			databases: [db],
			rootPath: '/superadmin',
			logoutPath: '/superadmin/logout',
			loginPath: '/superadmin/login',
			branding: {
				companyName: 'Name',
				softwareBrothers: true,
			},
		})

		//Hidden information, that we shouldnt share
		const ADMIN = {
			email: 'HIDDEN',
			pwd: 'HIDDEN'
		}

		if (process.env.NODE_ENV === 'production') {
			//brute force issue solve
			router.use(bruteforce.prevent)
		}

		AdminBroExpress.buildAuthenticatedRouter(adminBro, {
			authenticate: async (email, password) => {
				if (ADMIN.pwd === password && ADMIN.email === email) {
					return ADMIN
				}
				return null
			},
			cookieName: 'superadmin',
			cookiePassword: 'HIDDEN',
		}, router)

	} catch (e) {
		let err = e
	}

	return router
    }
`

**Comment by wojtek-krysiak** [comment]
I will try to debug this at the end of next week (cannot earlier)

**Comment by wojtek-krysiak** [comment]
1. Please comment out this line: `router.use(bruteforce.prevent)` and check out again - maybe it is related to BruteForce?

2. if turning off `router.use(bruteforce.prevent)` wont help - please send the schema of resource which doesn't work.
