### ISSUE TITLE
Add record object to both isVisible and  isAccessible function in actions.

### ISSUE THREAD

**Issue by subhasis020299** [SoftwareBrothers/admin-bro#139]
I want to implement an action on a record only if a particular field has a true value. For that I'm trying to pass the record in the isVisible function, but then I realized that the default parameters passed to the isVisible function in context of the action doesn't include the record itself. 
I am trying to do something like this : 
`isVisible:data=>!data.record.params['sent_conf_mail']`
But it doesnt work as data.record doesn't exist inside the data object.
Please try to add this feature, or suggest me another way out.

**Comment by wojtek-krysiak** [comment]
yes - right now it doesn't have the `record` property. The only way of handing that is (if this is a custom action) simply throw an error in a `handler`. We will add this later on due to other features we are working on right now (ETA ~ start of november)

**Comment by wojtek-krysiak** [comment]
added this in version 1.3.0 - enjoy
