### ISSUE TITLE
using custom dashboard doesn't work

### ISSUE THREAD

**Issue by reactjs-lab** [SoftwareBrothers/admin-bro#140]
I get the following error when I try to change the dashboard
{ SyntaxError: Octal literal in strict mode (2:54) in C:\Users\Pavilian i5\Documents\1.Freelancer\Fiver Projects React\fork\testing\quora\backend\.adminbro\.entry.js
...

```
pos: 83,
  loc:
   { file:
      'C:\\Users\\Pavilian i5\\Documents\\1.Freelancer\\Fiver Projects React\\fork\\testing\\quora\\backend\\.adminbro\\.entry.js',
     line: 2,
     column: 54 },
  raisedAt: 85,
  frame:
   '1: AdminBro.UserComponents = {}\n2: import Component1 from \'C:\\Users\\Pavilian i5\\Documents\\1.Freelancer\\Fiver Projects React\\fork\\testing\\quora\\backend\\config\\adminDashboard\'\n                                                         ^\n3: AdminBro.UserComponents.Component1 = Component1',
  id:
   'C:\\Users\\Pavilian i5\\Documents\\1.Freelancer\\Fiver Projects React\\fork\\testing\\quora\\backend\\.adminbro\\.entry.js',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs' }
```

**Comment by wojtek-krysiak** [comment]
It is probably related to windows issue we have with custom components #136. Can you paste the content of your `.adminbro\.entry.js` file?

**Comment by reactjs-lab** [comment]
```
AdminBro.UserComponents = {}
import Component1 from 'C:\\Users\\Pavilian i5\Documents\1.work\Projects React\fork\testing\questions\backend\config\adminDashboard'
AdminBro.UserComponents.Component1 = Component1
```

**Comment by wojtek-krysiak** [comment]
yes - that is related to windows. I will try to fix this by passing relative paths instead of absolute. Hopefully, it will help. But this will happen end of next week.

**Comment by Chukstart** [comment]
Have you resolved this yet I think it's past a week 

> yes - that is related to windows. I will try to fix this by passing relative paths instead of absolute. Hopefully, it will help. But this will happen end of next week.

**Comment by wojtek-krysiak** [comment]
I've just changed paths to relative - can you try out the 1.1.5-beta.2 version and let me know if that helped

**Comment by wojtek-krysiak** [comment]
it duplicates #136

**Comment by Chukstart** [comment]
> it duplicates #136

This is the output of my hidden adminbro file 
`AdminBro.UserComponents = {}
import Component1 from '..\routes\my-dashboard-component'
AdminBro.UserComponents.Component1 = Component1`

**This is the error that I'm getting or rather output**
`outesmy-dashboard-component' is imported by .adminbro\.entry.js, but could not be resolved – treating it as an external dependency
outesmy-dashboard-component' in output.globals – guessing 'Component1'`

**This is how I'm importing the component**
` dashboard: {
        component: AdminBro.require('./my-dashboard-component')
    }`
what I'm i doing wrong?

**Comment by messcall** [comment]
> This is the output of my hidden adminbro file
> AdminBro.UserComponents = {} import Component1 from '..\routes\my-dashboard-component' AdminBro.UserComponents.Component1 = Component1
> 
> This is the error that I'm getting or rather output
> outesmy-dashboard-component' is imported by .adminbro\.entry.js, but could not be resolved – treating it as an external dependency outesmy-dashboard-component' in output.globals – guessing 'Component1'
> 
> This is how I'm importing the component
> dashboard: { component: AdminBro.require('./my-dashboard-component') }
> what I'm i doing wrong?


same error ;

Is there any known solution?
