### ISSUE TITLE
Can't render profile photo component as image

### ISSUE THREAD

**Issue by subhasis020299** [SoftwareBrothers/admin-bro#142]
I have a profile photo field in my database to store the link to the profile photo of the user. I want to render it in admin bro as an image but somehow the 'components' attribute of properties object is not working, and the link is being rendered as a simple span tag with text.

Here is my code inside the properties object :

`resource:Members,
options:{
    properties:{
                    profilePhoto:{
                                      components:AdminBro.require('./components/profile-photo-comp')
                                  }
                     }
     }
`
And here is the component : 
```import React from 'react';
const PhotoComp = props=>{
                      return (
                    ```
                        <div>
                            <img src={props.record.params.profilePhoto} alt="profile-photo" />
                         </div>
                   ```
                     );

export default PhotoComp;
```

**Comment by wojtek-krysiak** [comment]
there is a **where** missing.
```
resource:Members,
options:{
  properties:{
   profilePhoto:{
     **where**: components:AdminBro.require('./components/profile-photo-comp')
   }
  } 
}
```

**where** can be either: `list`, `show`, `edit` or `filter` - in your case probably you will have to override `list` and `show`.

**Comment by subhasis020299** [comment]
Nope, doesn't work. Still the same issue - photo link is rendered as a span tag, instead of img tag

**Comment by wojtek-krysiak** [comment]
sorry - my mistake:

```
resource:Members,
options:{
  properties:{
   profilePhoto:{
    components: {
     **where**: AdminBro.require('./components/profile-photo-comp')
    }
   }
  } 
}
```
