### ISSUE TITLE
Offline Support and Option to Hide AdminBro - title

### ISSUE THREAD

**Issue by kyawswarthwin** [SoftwareBrothers/admin-bro#146]
script and link tags in layout-template.js need internet connection. use node_modules 
instead of cdn and please also add option to hide AdminBro - in title tag.

**Comment by Chukstart** [comment]
AdminBro takes a list of options of the entire framework. All off them have default values, but you can easily tailor them to your needs

pass this option
` softwareBrothers :false `
**softwareBrothers | Boolean | <optional> |   | if Software Brothers logos should be shown in the sidebar footer
-- | -- | -- | -- | --**

**Comment by Chukstart** [comment]
> script and link tags in layout-template.js need internet connection. use node_modules
> instead of cdn and please also add option to hide AdminBro - in title tag.

AdminBro takes a list of options of the entire framework. All off them have default values, but you can easily tailor them to your needs

pass this option
` softwareBrothers :false `
**softwareBrothers | Boolean | <optional> |   | if Software Brothers logos should be shown in the sidebar footer
-- | -- | -- | -- | --**

**Comment by sinchanpokemon** [comment]
what is the command to run this project??
node index.js is not working??

**Comment by wojtek-krysiak** [comment]
In version admin-bro@1.2.0-beta.1 we removed hardcoded AdminBro from the title and also there is an (undocumented yet) option to fetch most of the externals (React, ReactDOM etc) from the local bundle.

```javascript
new AdminBro({ assets: { globalsFromCDN: false }})
```
