### ISSUE TITLE
Using Admin Bro for Pages and Sections

### ISSUE THREAD

**Issue by gabalicious** [SoftwareBrothers/admin-bro#147]
Hi guys.  I was wondering if it would make sense to have a type of model which will only have one record.  Example: I have homepage which has unique properties and a support page that has unique properties.  See images below of some pages and then some images of how this instance of Django CMS handles it. Maybe we could do something similar for Admin Bro.  

![digestible-content-1024x728](https://user-images.githubusercontent.com/241617/64640333-bd5e1600-d3d7-11e9-8d8e-039985d2b92f.png)
<img width="1431" alt="Screen Shot 2019-09-10 at 5 32 53 AM" src="https://user-images.githubusercontent.com/241617/64640388-de266b80-d3d7-11e9-8012-ce94cd497f8c.png">

![djangocms1](https://user-images.githubusercontent.com/241617/64640360-cfd84f80-d3d7-11e9-905c-cadaedfd722e.png)
![djangocms2](https://user-images.githubusercontent.com/241617/64640361-cfd84f80-d3d7-11e9-9fd1-0fd8a10c7bb7.png)

**Comment by wojtek-krysiak** [comment]
It is more like a CMS thing - AdminBro serves a slightly different purpose. Maybe someday there will be a plugin to AdminBro which behaves as you described. But for sure not this year.
