### ISSUE TITLE
Add documentation of how to do role based authentication

### ISSUE THREAD

**Issue by PRV88** [SoftwareBrothers/admin-bro#149]
I want a admin panel  with rbac . Can admin bro supports rbac system .

**Comment by wojtek-krysiak** [comment]
Yes - there is such thing - take a look at this issue: https://github.com/SoftwareBrothers/admin-bro/issues/141 and my answer there.

I will add an example rbac setup in tutorials section.

**Comment by PRV88** [comment]
Thanks sir 🙏.

**Comment by wojtek-krysiak** [comment]
updated a couple of things in Admin in version 1.3 regarding the roles. And there is an article describing this that: https://softwarebrothers.co/blog/how-to-add-role-based-admin-panel-to-node-js-app/
