### ISSUE TITLE
command to run this project????

### ISSUE THREAD

**Issue by sinchanpokemon** [SoftwareBrothers/admin-bro#150]

**Comment by wojtek-krysiak** [comment]
Can you write more details?

**Comment by wojtek-krysiak** [comment]
@sinchanpokemon this more library than an external project. You can attach it to your existing app. Example app can be found here: https://github.com/SoftwareBrothers/admin-bro-example-app and entire dev environment here https://github.com/SoftwareBrothers/admin-bro-dev

**Comment by sinchanpokemon** [comment]
i have problem with run this project with npm command .can you help me to run this project ????
i try to run this so many time. steps to run this project which is followed by me is:-
1) npm install
2)npm index.js

**Comment by wojtek-krysiak** [comment]
As this is a library, not the actual application, you add this to your project. Check out this [tutorial](https://softwarebrothers.github.io/admin-bro-dev/tutorial-00-installation-instructions.html).

Or (to speed things up) you can simply create new folder and init project there:
```
mkdir project-with-admin
cd project-with-admin
npm init -y

# install express with mongodb ODM
npm install mongoose express body-parser

# install admin-bro packages
npm install admin-bro admin-bro-mongoose admin-bro-expressjs
```

then create index.js file with this content (taken from [this tutorial](https://softwarebrothers.github.io/admin-bro-dev/tutorial-01-example.html))

```
// ==========  server.js ==============
// Requirements
const mongoose = require('mongoose')
const express = require('express')
const bodyParser = require('body-parser')
const AdminBro = require('admin-bro')
const AdminBroExpressjs = require('admin-bro-expressjs')

// We have to tell AdminBro that we will manage mongoose resources with it
AdminBro.registerAdapter(require('admin-bro-mongoose'))

// express server definition
const app = express()
app.use(bodyParser.json())

// Resources definitions
const User = mongoose.model('User', { name: String, email: String, surname: String })

// Routes definitions
app.get('/', (req, res) => res.send('Hello World!'))

// Route which returns last 100 users from the database
app.get('/users', async (req, res) => {
  const users = await User.find({}).limit(10)
  res.send(users)
})

// Route which creates new user
app.post('/users', async (req, res) => {
  const user = await new User(req.body.user).save()
  res.send(user)
})

// Pass all configuration settings to AdminBro
const adminBro = new AdminBro({
  resources: [User],
  rootPath: '/admin',
})

// Build and use a router which will handle all AdminBro routes
const router = AdminBroExpressjs.buildRouter(adminBro)
app.use(adminBro.options.rootPath, router)

// Running the server
const run = async () => {
  await mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true })
  await app.listen(8080, () => console.log(`Example app listening on port 8080!`))
}

run()
```

assuming that you have [mongodb](https://www.mongodb.com) running on your localhost - run this command:

```
node index.js
```

and visit `http://localhost:8080/admin`

**Comment by sinchanpokemon** [comment]
thanks a lot sir.
i have one more question regarding this ,can u help me??
 how can we implement Role Based Access control System using Admin bro??
in that system we specify the role of admin,superadmin and user

**Comment by wojtek-krysiak** [comment]
i am writing an article about how to do this. I will add i to tutorials in 1 week
