### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by LucasLeandro1204** [SoftwareBrothers/admin-bro#156]
Hey, I'm wondering if there's something planned about internationalization.
I can handle this issue if someone gives me the direction

**Comment by wojtek-krysiak** [comment]
I didn't have this in plans. I will add this issue to the backlog

**Comment by wojtek-krysiak** [comment]
Also in this task lets allow people to customize messages in AdminBro (#173)

**Comment by wojtek-krysiak** [comment]
I've just released v2.0.0-beta.21 with i18n support. 

Basically there is a [locale option](https://softwarebrothers.github.io/admin-bro-dev/v2/AdminBroOptions.html#locale) with [Locale](https://softwarebrothers.github.io/admin-bro-dev/v2/AdminBroOptions.html#Locale) as a type. And this in turn has [LocaleTranslations](https://softwarebrothers.github.io/admin-bro-dev/v2/AdminBroOptions.html#LocaleTranslations)

So you can pass there whatever you like and translate entire app. Here is an example for en translation: https://github.com/SoftwareBrothers/admin-bro/blob/staging/src/locale/en.ts

If something is missing let me know. It is still in beta

**Comment by LucasLeandro1204** [comment]
Thank you!! I'll test it asap
