### ISSUE TITLE
SMALLINT, JSON types support.

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#157]
Hello. Great admin-panel but we have some troubles with JSON and SMALLINT fields.
We use last versions of PostgreSQL. 
Dependencies:
- admin-bro: v1.2.0
- admin-bro-expressjs: v0.2.0
- admin-bro-sequelizejs: v0.2.6
- sequelize: v4.44.0

Warning kind of:
```
Unhandled type: SMALLINT
Unhandled type: SMALLINT
Unhandled type: SMALLINT
Unhandled type: SMALLINT
Unhandled type: JSON
Unhandled type: SMALLINT
Unhandled type: SMALLINT
Unhandled type: JSON
Unhandled type: SMALLINT
Unhandled type: SMALLINT
Unhandled type: JSON
```

P.S. For JSON type you can use some interactive editiror like [react-json-editor-ajrm](https://www.npmjs.com/package/react-json-editor-ajrm) or make it simple editable with textarea.

**Comment by wojtek-krysiak** [comment]
added this to the backlog

**Comment by sitvanit** [comment]
Hi, I'm having the same issue with the JSON type, can you please tell me when is it going to be implemented? 
thanks!

**Comment by wojtek-krysiak** [comment]
unfortunately not. now we are focused on v2 which should be released next week. will try to refine backlog then and let you know

**Comment by DoublG** [comment]
Hi @wojtek-krysiak I'm also facing the same issue with the JSON type, can you inform me as well ?
Thanks.

**Comment by wojtek-krysiak** [comment]
np - will post an update here

**Comment by memahesh** [comment]
Hi,
I am also in need of this feature. Can you tell me when is this planned ?
