### ISSUE TITLE
a couple of customization issues

### ISSUE THREAD

**Issue by doubletuna** [SoftwareBrothers/admin-bro#160]
Hello,

First of all, thanks for an awesome piece of software!

I'm trying to find documentation on how to disable record "Delete" action on all/some of the resources.

another issue is the addition of custom code, for some sort of an "event" log.

Cheers

DT

**Comment by doubletuna** [comment]
if you could update your docs @
https://softwarebrothers.github.io/admin-bro-dev/tutorial-05-actions.html

to show a full line like the below example, it would be great:
options: { name: 'X Table', actions: {show: {}, edit: {}, delete: { isVisible: false } } }

Cheers

**Comment by wojtek-krysiak** [comment]
Hi - regarding your first question;

There is something like ACTIONS - a list of all default actions: https://softwarebrothers.github.io/admin-bro-dev/AdminBro.html#.ACTIONS. you can override them for all resources in one place. So in your case:

```
ACTIONS.delete.isAccessible = false
```

Similarly, you can add an event log - by using an `after hook` (https://softwarebrothers.github.io/admin-bro-dev/Action.html#after) - in the function (https://softwarebrothers.github.io/admin-bro-dev/Action.html#After) you can access action, resourece, record etc.

**Comment by wojtek-krysiak** [comment]
Could you please

**Comment by doubletuna** [comment]
Thanks!

can you provide an example for the usage of the after hook?

**Comment by wojtek-krysiak** [comment]
just added that: https://softwarebrothers.github.io/admin-bro-dev/Action.html#After
