### ISSUE TITLE
Deprecations in Admin-Bro 1.3.1

### ISSUE THREAD

**Issue by JanChodorowski** [SoftwareBrothers/admin-bro#162]
While using the latest versions 
```
"admin-bro-expressjs": "^0.2.0",
 "admin-bro-mongoose": "^0.3.0",
```
The following warnings are shown:

`express-session deprecated undefined resave option; provide resave option node_modules/admin-bro-expressjs/plugin.js:131:14`

`express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules/admin-bro-expressjs/plugin.js:131:14`

**Comment by wojtek-krysiak** [comment]
according to https://github.com/expressjs/session you have to pass those 2 params.

Install admin-bro-expressjs@0.3.0 and pass them via `sessionOptions` (https://softwarebrothers.github.io/admin-bro-dev/module-admin-bro-expressjs.html)

**Comment by Swarag-N** [comment]
```
AdminBroExpressjs.buildAuthenticatedRouter(adminBro,{
	authenticate:async(email, password)=>{
		if (email === Admin.email && password === Admin.password) {
			return Admin
		}
    return null
  },
  cookieName: process.env.COOKIE_ADMIN_NAME || 'C-4-P',
  cookiePassword: process.env.COOKIE_ADMIN_PASSWORD || 'admin-bro',
  },
  adminRouter,
  {
      resave:true,
      saveUninitialized: true}
);

```

i did add them like this but the error keeps popping up.

**Comment by wojtek-krysiak** [comment]
most probably you have to uprade admin-bro-express version. Take a look here: https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3 - it is a working example without this errors

**Comment by naterexw** [comment]
> ```
> AdminBroExpressjs.buildAuthenticatedRouter(adminBro,{
> 	authenticate:async(email, password)=>{
> 		if (email === Admin.email && password === Admin.password) {
> 			return Admin
> 		}
>     return null
>   },
>   cookieName: process.env.COOKIE_ADMIN_NAME || 'C-4-P',
>   cookiePassword: process.env.COOKIE_ADMIN_PASSWORD || 'admin-bro',
>   },
>   adminRouter,
>   {
>       resave:true,
>       saveUninitialized: true}
> );
> ```
> 
> i did add them like this but the error keeps popping up.

You set it up wrong.  Check here for correct way:

```
const router = buildAuthenticatedRouter(admin, {
  cookieName: 'admin-bro',
  cookiePassword: 'superlongandcomplicatedname',
  authenticate: async (email, password) => {
    const company = await Company.findOne({ email });

    if (company && await argon2.verify(company.encryptedPassword, password)) {
      return company.toJSON();
    }
    return null;
  },
}, null, {
  resave: false,
  saveUninitialized: true,
});
```
