### ISSUE TITLE
Custom CSS colors

### ISSUE THREAD

**Issue by MVPZl0b** [SoftwareBrothers/admin-bro#165]
![image](https://user-images.githubusercontent.com/38388879/66499241-7114fd00-ea8d-11e9-8106-eafa7e21b564.png)
I edited all of the colors in the theme and my web page still looks like this 
`theme: {
      colors: {
        bck:'#2C2F33',
        defaultText: '#2C2F33',
        lightText: '#2C2F33',
        lightBck: '#2C2F33',
        superLightBack: '#2C2F33',
        border: '#2C2F33',
        borderOnDark: '#2C2F33',
        darkBck: '#2C2F33',
        superDarkBck: '#2C2F33',
        love: '#2C2F33',
        primary: '#2C2F33',
        primaryHover: '#2C2F33',
        success: '#2C2F33',
        successBorder: '#2C2F33',
        lightSuccess: '#2C2F33',
        error: '#2C2F33',
        lightError: '#2C2F33',
        warning: '#2C2F33',
      }
    }`

**Comment by wojtek-krysiak** [comment]
thanks for checking this out. I will try to add totally new 'black' skin to AdminBro and then fix it. But no ETA for now

**Comment by wojtek-krysiak** [comment]
And black theme was added: https://github.com/SoftwareBrothers/admin-bro-theme-dark (works with version 1.3.2)
