### ISSUE TITLE
how to generate react code ?

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#166]
I want to customize even more the administrator, for which the configuration of adminbro no longer serves me, can I generate the react code of the application to edit it directly?

**Comment by wojtek-krysiak** [comment]
yes - just run `yarn run bundle` in the root of admin-bro (assuming that you cloned the repo). This will watch for changes and bundle them.

**Comment by SantiagoAndre** [comment]
but with  my database and my config?, on my project
