### ISSUE TITLE
set navigation label in sidebar

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#168]
![imagen](https://user-images.githubusercontent.com/29509374/66610509-57ed7880-eb81-11e9-8f47-851ffcfc7d09.png)

**Comment by wojtek-krysiak** [comment]
I wanted to add this feature right now but eventually decided that this will have to be handled along with the i18n as a global/long term solution. That is why I am closing this one in favour of #156
