### ISSUE TITLE
resources without parents in sidebar

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#169]
![imagen](https://user-images.githubusercontent.com/29509374/66611265-8ec48e00-eb83-11e9-91b4-0a7a674f9b9c.png)

Acceptance Criteria:
* when `parent` is set to null - element should not be nested but be a separate element

**Comment by wojtek-krysiak** [comment]
interesting idea - adding this to the backlog

**Comment by wojtek-krysiak** [comment]
in added in admin-bro@2.1.0-beta.8

**Comment by marioguima** [comment]
I need this too
