### ISSUE TITLE
How to use ValidationError, Configuration error?

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#170]

**Comment by wojtek-krysiak** [comment]
* ValidationError is used by the adapters.
* Configuration error is internal error thrown by AdminBro when user messed up something with configuration (I am continuously adding it to the places for typical mistakes .

Is there anything more you want to know?

**Comment by SantiagoAndre** [comment]
## HOW TO CUSTOMIZE ERROR MESSAGES?
![image](https://user-images.githubusercontent.com/29509374/66689289-0b687280-ec3f-11e9-9508-70313ce90523.png)

**Comment by wojtek-krysiak** [comment]
right now thre is no such functionality
