### ISSUE TITLE
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#172]
I want use ImageUploader react module for upload images in component but I get an error saying that only javascript can be imported.

**Comment by wojtek-krysiak** [comment]
can you paste component code?

**Comment by SantiagoAndre** [comment]
when I want to import an image, with 'require' or with 'import' I also get the same error:
    ```import image from 'path/to/image'``` <=== mark error
    ```const image = require('path/to/image')``` <=== mark error

In this case this is the component code:
``` 
import React from 'react'
import ImageUploader from 'react-images-upload' // <========== ERROR HERE

export default class Dashboard extends React.Component {
  constructor(props) {
    super(props)
  }



  render() {
    return (
      <React.Fragment>
          <ImageUploader 
            withIcon={true}
            buttonText='Choose images'
            onChange={this.onDrop}
            imgExtension={['.jpg', '.gif', '.png', '.gif']}
            maxFileSize={5242880}
        />
      </React.Fragment>
    )
  }

}
```

**Comment by wojtek-krysiak** [comment]
(sorry for a late answer) - importing images with "import './image.png'" won't work in AdminBro.
