### ISSUE TITLE
Custom messajes

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#173]
## Messaje: not records
![image](https://user-images.githubusercontent.com/29509374/66693445-b6882480-ec5d-11e9-9697-12928745fbdd.png)
## Messaje: field is required
![image](https://user-images.githubusercontent.com/29509374/66693457-cacc2180-ec5d-11e9-884f-f6ce8ae8464d.png)
## Message: Action successfully
![image](https://user-images.githubusercontent.com/29509374/66693474-ecc5a400-ec5d-11e9-837b-2b237e81a4dd.png)
## Text button save
![image](https://user-images.githubusercontent.com/29509374/66693491-25657d80-ec5e-11e9-97ec-be3b0f6a15b3.png)

## Navigation label
![image](https://user-images.githubusercontent.com/29509374/66693524-9efd6b80-ec5e-11e9-9baa-e88ae87c6a70.png)

Tanks

**Comment by SantiagoAndre** [comment]
found how, in the 'handle' function of each action the success message or error messages are returned for each field, then those messages are edited before retoning them.
The last two cannot be edited.

**Comment by wojtek-krysiak** [comment]
We will handle this customization with #156
