### ISSUE TITLE
input file as customize component

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#174]
I want to save an image and for that I create a component that loads it, I use the `props.onChange('field',value)` method in the component to save the image in the `params` attribute of the parent component, but this method only receives `Strings` if I send it something else doesn't work, what can I do?
Thanks.

**Comment by wojtek-krysiak** [comment]
A believe that object you want to store has multiple fields: let say:

```
file: {
  name: 'xxx.xxx',
  data: 'yyyzzzz....',
}
```

so you can save each field separately (invoking props.onChange twice) or you can pass entire updated record to props.onChange like this:

```
props.onChange({
   ...props.record,
   params: {
       ...props.record.params,
       'file.name': file.name,
       'file.data': file.data // or change this to Base64 and then store
   }
})
```
