### ISSUE TITLE
Many to Many and translations ? 

### ISSUE THREAD

**Issue by AmbroiseVuaridel** [SoftwareBrothers/admin-bro#176]
admin bro looks great and is very promising, but i need 2 thing :
1) how do I get CRUD interfaces for many to many associations ? 
2) how can i add i18n support ? 

here's my code :
const adminBroRequire = require('admin-bro');
const adminBroExpressjs = require('admin-bro-expressjs');
const adminBroSequelize = require('admin-bro-sequelizejs');

adminBroRequire.registerAdapter(adminBroSequelize);
const db = require('./DB/models/models_DB_master');
const adminBro = new adminBroRequire({
    databases: [db],
    rootPath: '/test',
    //... other adminBroOptions
});

const adminBroRouter = adminBroExpressjs.buildRouter(adminBro)
app.use(adminBro.options.rootPath, adminBroRouter)

**Comment by wojtek-krysiak** [comment]
* regarding i18n - there is a task for that and it is in todo section (no eta for no though) (#156)
* for many to many relationships you would need to create a custom property and there, in its component, fetch all related models.

Check out this:
* https://softwarebrothers.github.io/admin-bro-dev/tutorial-04-customizing-resources.html (adding new properties)
* https://softwarebrothers.github.io/admin-bro-dev/tutorial-06-writing-react-components.html

and also you might need to use a ApiClient: https://softwarebrothers.github.io/admin-bro-dev/ApiClient.html and its resourceAction.

When I will have more time I will write detailed tutorial about this

**Comment by JohnyYer** [comment]
What about tutorial for many-to-many in typeorm? It will be great to read

**Comment by wojtek-krysiak** [comment]
yes I know - entire frontend section is not well documented. In v2 we changed entire ui and organised components in sections. After finishing v2 I will try to update docs.

PS: current v2 version is here: file:///Users/wojciechkrysiak/Documents/projekty/admin-bro-dev/docs/v2/index.html

**Comment by Vbubblery** [comment]
Hello, may I ask when the v2 will be released?

**Comment by wojtek-krysiak** [comment]
already released :)

**Comment by michalica** [comment]
@wojtek-krysiak you shared link of your local file system. Is there any turtorial about many to many relations? e.g with typeorm. Thanks

**Comment by wojtek-krysiak** [comment]
buahahahaha - will fix that. No - we don't have anuy tutorial yet. But I plan to add this this/next month in jscasts.tv

**Comment by GeiOoo** [comment]
@wojtek-krysiak any progress on a tutorial for implementing many to many in typeorm?

**Comment by nefas83** [comment]
> @wojtek-krysiak any progress on a tutorial for implementing many to many in typeorm?

I would also be interested in it. I currently do not get the Many-To-Many displayed.

**Comment by CarlosFandango** [comment]
Hey @wojtek-krysiak, I'm sure you're a busy guy but is there a plan to get out more documentation for AdminBro, especially Many-To-Many relationships with TypeORM.

**Comment by avirupdutta** [comment]
Adminbro is really great. And i am looking forward to use it in my next project. But I really need a support for many-to-many relationships using sequelize and mysql...

I dont think it fully supports m-m yet

**Comment by ohadch** [comment]
Still waiting for docs regarding Many-To-Many relationships. I am using TypeORM and this ability is essential for me.

@avirupdutta Regarding your issue, I have found the following [gist](https://gist.github.com/leibowitz/b94fc4eb2b8ab745267db99941757190), maybe it is helpful for your needs?

**Comment by cheyodevfarm** [comment]
any progress on a tutorial for implementing many to many in typeorm?

**Comment by franka107** [comment]
I implemented an example, it is tested with typeorm and postgresql,
You can test this project quickly with VSC dev containers, the example is in the many-to-many relationship User <-> Role, to enter the admin is localhost:3000/admin

https://github.com/franka107/nestjs-adminjs-manytomany-example

![Screenshot from 2022-12-14 11-49-27](https://user-images.githubusercontent.com/49798546/207657280-83c4d672-25ca-4de7-80a9-5d3de6c7a502.png)
![Screenshot from 2022-12-14 11-49-56](https://user-images.githubusercontent.com/49798546/207657324-51af5e0d-e7ae-4e72-9865-c087a72b7180.png)
![Screenshot from 2022-12-14 11-50-06](https://user-images.githubusercontent.com/49798546/207657359-53757312-6528-4cb2-b56e-3f0092e13eda.png)
