### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by marcdelalonde** [SoftwareBrothers/admin-bro#177]
Hey,

First of all, congrats for the great product !

This is what I get when I navigate through the admin interface :) the requests stayed in pending status...
![image](https://user-images.githubusercontent.com/5658057/66930304-acd33800-f034-11e9-8188-b807a79abe7c.png)

versions:
"admin-bro": "^1.3.2"
"admin-bro-expressjs": "^0.2.0"
"admin-bro-mongoose": "^0.3.0"

Do you have an idea ?

Thanks

**Comment by wojtek-krysiak** [comment]
how do you pass database/resources to the AdminBro?

**Comment by marcdelalonde** [comment]
Thank you,
I define resources like this:
![image](https://user-images.githubusercontent.com/5658057/66934097-405b3780-f03a-11e9-9295-35eec67c2502.png)

**Comment by marcdelalonde** [comment]
![image](https://user-images.githubusercontent.com/5658057/66936585-4226fa00-f03e-11e9-82fd-3ecf16944d3f.png)

**Comment by wojtek-krysiak** [comment]
try to connect with mongo before launching admin panel.

```
await mongoose.connect(...)
```

**Comment by marcdelalonde** [comment]
Thank you it was a ref problem :)
However, I get this error now when updating an object:

(node:60640) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:60640) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.

Thank you

**Comment by wojtek-krysiak** [comment]
finally got time to check this out. I think that the deprecation warning comes from your code, because we use `findOneAndUpdate`
