### ISSUE TITLE
Custom components using third-party React libraries

### ISSUE THREAD

**Issue by JonaszJestem** [SoftwareBrothers/admin-bro#178]
Hi,
I was trying to use custom component in AdminBro using the Material UI library. It looks like AdminBro has problem bundling the component's code. I can see that the request for `GET /admin/frontend/assets/components.bundle.js` never completes and the page does not load at all.
In server console I can see the error:
`Error: 'ForwardRef' is not exported by node_modules/react-is/index.js`

After removing the `import` statement from `Component.jsx` problem does not occur and AdminBro loads without any issues.

MVCE:
`Component.jsx`
```jsx
import React from 'react';
import { Typography } from '@material-ui/core';

const Component = () => {
  return <Typography>My custom component</Typography>;
};

export default Component;
```

`main.js`
```javascript
const { MongoMemoryServer } = require('mongodb-memory-server');
const AdminBro = require('admin-bro');
const AdminBroMongoose = require('admin-bro-mongoose');
const AdminBroExpress = require('admin-bro-expressjs');
const express = require('express');
const mongoose = require('mongoose');

const SomeModel = mongoose.model('SomeModel', { name: String });

const config = {
  resources: [{
    resource: SomeModel, options: {
      actions: { new: { component: AdminBro.bundle('./Component.jsx') } },
    },
  }],
};

async function start() {
  await setupMongoConnection();
  const app = express();
  await AdminSetup(app);
  await app.listen(3000);
}

const setupMongoConnection = async () => {
  const mongod = new MongoMemoryServer();
  const mongoUrl = await mongod.getConnectionString();
  await mongoose.connect(mongoUrl);
};

const AdminSetup = async (server) => {
  AdminBro.registerAdapter(AdminBroMongoose);
  const adminBro = new AdminBro(config);
  const router = AdminBroExpress.buildRouter(adminBro);
  server.use(adminBro.options.rootPath, router);
};

start();
```

`package.json`
```json
{
  "scripts": {
    "start": "node src/main"
  },
  "dependencies": {
    "express": "^4.17.1",
    "admin-bro": "^1.3.1",
    "admin-bro-expressjs": "^0.2.0",
    "admin-bro-mongoose": "^0.3.0",
    "mongoose": "^5.7.4",
    "mongodb-memory-server": "^5.2.8",
    "@material-ui/core": "^4.5.1"
  }
}
```

Error log:
[error.log](https://github.com/SoftwareBrothers/admin-bro/files/3740007/error.log)

node version: `12.6.0`
yarn version: `1.17.3`

**Comment by wojtek-krysiak** [comment]
we are using rollup which has some problems with different libraries. Right now there is no way to fix that with some configuration options, but... You can bundle files yourself with webpack/parcel and this should work (thou I never tested that)

1. let say you bundled files together to `my-bundle.js`. So you have to make it available in your express/hapijs server under let say: /admin/my-bundle.js
2. next you can put this to file to scripts in assets property: https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#assets
3. In the bundle let say you have `MyComponent` Component. Add this to 

```
AdminBro.UserComponents['MyComponentName'] = MyComponent.
```
4. instead of using `AdminBro.bundle('/path/')` you can simply pass 'MyComponentName' as a string.

**Comment by endel** [comment]
I can confirm this works. The only problem is when I enter the `/actions/new` URL directly, my component is not loaded yet, causing this error.

![Screenshot 2020-04-24 at 18 54 57](https://user-images.githubusercontent.com/130494/80232169-23dd2f00-865d-11ea-8a6e-57fee1f9893e.png)
