### ISSUE TITLE
ConfigurationError: handler of a recordAction should return a RecordJSON object

### ISSUE THREAD

**Issue by dhemas** [SoftwareBrothers/admin-bro#180]
I'm using Ubuntu 18.04 & MongoDB 4.2, when I try to delete a document the log will say:

`ConfigurationError: handler of a recordAction should return a RecordJSON object`

the document is deleted, but the web UI is not showing anything after clicking delete/remove. But when I use my code in Windows with the same MongoDB and Admin Bro version, it just work well

Admin Bro version:
"admin-bro": "^1.3.1",
"admin-bro-expressjs": "^0.2.0",
"admin-bro-mongoose": "^0.3.0",

**Comment by wojtek-krysiak** [comment]
update admin to the latest version and it will work
