### ISSUE TITLE
Interesting enhancements

### ISSUE THREAD

**Issue by marcdelalonde** [SoftwareBrothers/admin-bro#183]
Hey Admin bro team :)

It could be cool if only properties present in editProperties / showProperties could be sent in request GET / POST / PUT. To avoid someone to use the api and updates the others fields !

Thank you

**Comment by wojtek-krysiak** [comment]
I think it should be another setting. The idea of showProperties (and editProperties) is to limit just the default view. So let say you have `name`, and `surname` fields and you don't want to show them separately, so in showProperties you "turn them off" but you add a new field `fullName`. And in the custom component you join `name` and `surname`.
When we limit properties access as you mentioned - users won't have `name` and `surname` available in the frontend.

Leaving that open. Maybe someone will figure out how to do this.

**Comment by wojtek-krysiak** [comment]
at some point, we added a Before action hook which can be used to filter out the properties in the payload.

So closing this one
