### ISSUE TITLE
`Uncaught SyntaxError: Unexpected token '<'` when running in docker container w/ nginx

### ISSUE THREAD

**Issue by alex-a-pereira** [SoftwareBrothers/admin-bro#184]
Hey, the project looks super cool but I haven't been able to get it configured properly. I think this may be user error, but it looks like the react build is not successful. Possibly because I'm running my node server in a docker container through nginx locally. This is the most promising node admin panel app I've seen (really like Active Admin for rails) so I'd like to get this up and running.

The default AdminBro landing page renders for a split second, and then the development React app errors out. Here is the output of my chrome devtools console:
![image](https://user-images.githubusercontent.com/36137079/67252669-01662100-f442-11e9-96ad-afe4603a6ff8.png)

The first two errors are caused by `<!DOCTYPE html>` in `app.bundle.js` and `components.bundle.js`.

I'm pretty confident that my code is right (will post below anyways), because when the page flashes for a second I can see the name of the database and links under "navigation" for my two models.

**Am I missing something related to serving the development react build through nginx inside a container?**

I use react for my front end and have to enable a couple things in nginx for sockjs-node (hotreloading). I can't imagine that's related to what I'm seeing in admin-bro.

Here's the code for my `/routes/admin.js` route folder. I import the adminRouter in a file called `/routes/index.js` which is used in my server's index.js with `app.use(indexRouter)`, pretty standard convention for separating routes.
```
const AdminBro = require('admin-bro');
const AdminBroExpress = require('admin-bro-expressjs');
const AdminBroSequelize = require('admin-bro-sequelizejs');

const db = require('../db/models');

AdminBro.registerAdapter(AdminBroSequelize);

const adminBroRoot = '/admin';

const adminBro = new AdminBro({
  databases: [db],
  rootPath: adminBroRoot,
});

const adminRouter = AdminBroExpress.buildRouter(adminBro);

export { adminBroRoot, adminRouter };
```

**Thank you**

**Comment by alex-a-pereira** [comment]
I should also include my server's `index.js` file. Realized that it may be relevant that I'm serving the app not through express alone, but using node's `http.createServer(app)` since I needed to hook up socketio as well. server that listens for sockets is renamed to `SOCKET_SERVER` to hide top secret, super classified details.

```
import express from 'express';
import socket from 'socket.io';
import http from 'http';

import { router } from './routes';
import { sessionMiddleware } from './middleware/authMiddleware';
import { SOCKET_SERVER } from './SOCKET_SERVER'

const app = express();
const server = http.createServer(app);

const io = socket.listen(server);

server.listen(5000, () => console.log('API listening on port 5000!'));

let ss = new SOCKET_SERVER(io);
ss.initializeSocketIO();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(sessionMiddleware);

app.use('/api', router);
```

**Comment by wojtek-krysiak** [comment]
Hi, it looks that your server returns some error when trying to load the `app.bundle.js`. Can you paste here what exactly is returned from the server instead of the real `app.bundle.js` (it starts with <!DOCTYPE html>...).

You can fetch it from `yourdomain://admin/frontend/assets/app.bundle.js`
