### ISSUE TITLE
STRING-fields editing problem.

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#186]
Hello. 😃 

The problem is: No possibility to edit STRING/TEXT/VARCHAR fields with new line character (\n).
Possible solutions are:
- Make it editable with: `<textarea type="textarea" rows={1}/>` it will looking like `<input type="text"/>`

Or:
- Make it editable with: `<textarea type="textarea" rows={(value.match(/\n/g) || [1]).length}/>` 👍 

Best wishes,
Artem Zabolotnyi.

**Comment by wojtek-krysiak** [comment]
adding this to todo

**Comment by Arteha** [comment]
Thank you. so much

**Comment by getmmg** [comment]
Any update on this feature?

**Comment by wojtek-krysiak** [comment]
it was fixed in admin-bro@1.6.0-beta.3

**Comment by wojtek-krysiak** [comment]
in testing we found some issues. So in version 1.6.0-beta.4 I changed this. By default input fields works as they were, but when you change the[ type](https://softwarebrothers.github.io/admin-bro-dev/PropertyOptions.html#type) to 'textarea' - field will become a textarea

**Comment by wojtek-krysiak** [comment]
take a look at "content" field https://admin-bro-example-app.herokuapp.com/admin/resources/Comment/actions/new

**Comment by Arteha** [comment]
Perfect.
I can add a decorator `@Textarea()` in `admin-bro-typeorm`.
So, if property type is `"string"` and textarea meta-data are pinned, then return "textarea", else "string"

**Comment by cilere** [comment]
> Perfect.
> I can add a decorator `@Textarea()` in `admin-bro-typeorm`.
> So, if property type is `"string"` and textarea meta-data are pinned, then return "textarea", else "string"

Hello, I haven't seen there is Textarea in admin-bro-typeorm. It's still in plan?

**Comment by Arteha** [comment]
> > Perfect.
> > I can add a decorator `@Textarea()` in `admin-bro-typeorm`.
> > So, if property type is `"string"` and textarea meta-data are pinned, then return "textarea", else "string"
> 
> Hello, I haven't seen there is Textarea in admin-bro-typeorm. It's still in plan?

In admin-bro-typeorm v0.1.6-alpha.3+
https://github.com/Arteha/admin-bro-typeorm/blob/master/src/decorators/Textarea.ts
`import { Textarea } from "admin-bro-typeorm/decorators/Textarea"`

**Comment by cilere** [comment]
> > > Perfect.
> > > I can add a decorator `@Textarea()` in `admin-bro-typeorm`.
> > > So, if property type is `"string"` and textarea meta-data are pinned, then return "textarea", else "string"
> > 
> > 
> > Hello, I haven't seen there is Textarea in admin-bro-typeorm. It's still in plan?
> 
> In admin-bro-typeorm v0.1.6-alpha.3+
> https://github.com/Arteha/admin-bro-typeorm/blob/master/src/decorators/Textarea.ts
> `import { Textarea } from "admin-bro-typeorm/decorators/Textarea"`

Thanks!!!
Just notice, as I'm using ```"admin-bro-typeorm": "^0.1.6-alpha.9"``` The module path is ```admin-bro-typeorm/lib/decorators/Textarea```
