### ISSUE TITLE
Not editing Dashboard Wrapper Front-end with default-dashboard.tsx

### ISSUE THREAD

**Issue by harisrehmankhan** [SoftwareBrothers/admin-bro#187]
Hi, I want to edit the Dashboard wrapper but everytime I try to edit the file it doesn't reflect the changes on the web page, I have found its code from
\server\node_modules\admin-bro\src\frontend\components\app\default-dashboard.tsx

Following highlighted (In red rectangle) is the part that I want to remove from my project.

![FEND](https://user-images.githubusercontent.com/48333511/67387965-4a88b300-f5b1-11e9-8b10-b10864c83a13.jpg)

**Comment by wojtek-krysiak** [comment]
in order to edit that you should pass custom component to admin-bro options.

Take a look at tutorial here:
* https://softwarebrothers.github.io/admin-bro-dev/tutorial-07-custom-dashboard.html
and here:
* https://softwarebrothers.github.io/admin-bro-dev/tutorial-06-writing-react-components.html
