### ISSUE TITLE
Little visual problems.

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#189]
Hello. Here I am. 😃
I have a little list of bugs on version 1.4.0-beta.2:
- Wrong rows direction. (since v1.3.0)
![image](https://user-images.githubusercontent.com/22820043/67708936-5adbcc00-f9bd-11e9-8421-390046dc3cbc.png)
- Overflow problems in Filter component. (since v1.2.0 but not sure. didn't test old versions.)
![image](https://user-images.githubusercontent.com/22820043/67709675-b5295c80-f9be-11e9-943b-325ae81ecfe3.png)

**Comment by wojtek-krysiak** [comment]
Man - thanks. I am finishing one thing and will try to fix them out this week

**Comment by Arteha** [comment]
Tried 1.4.0-beta.4.
- Filter: is not scrollable and the problem still exists.
![image](https://user-images.githubusercontent.com/22820043/67955342-bf33a100-fbf2-11e9-9550-b0b0ff8d7a8b.png)
- Rows dirrection still inverted.
