### ISSUE TITLE
add a custom record action

### ISSUE THREAD

**Issue by doubletuna** [SoftwareBrothers/admin-bro#191]
Hello

is it possible to add a custom record action?
I've already removed the "delete" option and would like to add a custom update (change status from active to inactive or whatever)

Cheers

DT

**Comment by wojtek-krysiak** [comment]
sure - check out https://softwarebrothers.github.io/admin-bro-dev/tutorial-05-actions.html - there is an example for a record action on the bottom of the page. And there is a place where you can see all the properties for single action: https://softwarebrothers.github.io/admin-bro-dev/Action.html (probably your action should have component: false)

**Comment by wojtek-krysiak** [comment]
and checkout how delete action is implemented: https://softwarebrothers.github.io/admin-bro-dev/admin-bro_src_backend_actions_delete-action.ts.html
