### ISSUE TITLE
CORS issues when accessing admin page

### ISSUE THREAD

**Issue by bartekczyz** [SoftwareBrothers/admin-bro#192]
I'm getting following error when I'm accessing admin page:

```
Access to script at 'https://unpkg.com/react@16/umd/react.development.js' from origin 'https://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by pmourad** [comment]
I'm having a problem (which I believe could be a bug) that the admin platform loads without CSS. The input fields are not showing. 
![Screen Shot 2019-11-01 at 11 27 15](https://user-images.githubusercontent.com/8883090/68031561-b1d1f180-fc9a-11e9-88b1-5bf9feedc2ed.png)

**Comment by Gr8z** [comment]
Same

**Comment by mopcweb** [comment]
Hello. Same problem

**Comment by wojtek-krysiak** [comment]
Its probably related to: https://github.com/mjackson/unpkg/issues/176

for now to fix it in adminbro options set assets.globalsFromCDN to false (https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#assets)

**Comment by wojtek-krysiak** [comment]
changed globalsFromCDN to true by default (not released yet though)

**Comment by Lihaas** [comment]
SOLUTION Simple solution Again install the admin-bro , admin-bro-expressjs, and admin-bro-mongoose. After that, if error comes then try to install again.
