### ISSUE TITLE
 'bundle' of undefined

### ISSUE THREAD

**Issue by SirReaDy** [SoftwareBrothers/admin-bro#194]
AdminBro.require = AdminBro.bundle;
                            ^

TypeError: Cannot read property 'bundle' of undefined

How to fix

**Comment by wojtek-krysiak** [comment]
Hi, please write more details:

* when it happens (when you launch the server?, visit particular route)
* can you paste the intialization code?
* what is your AdminBro version and node version

**Comment by SirReaDy** [comment]
Was using the version from Github 
`+git (master version)`

Fixed by deleting the admin-bro folder and running again 
`npm install admin-bro admin-bro-expressjs`

Current build  "admin-bro": "^1.3.5",

**Comment by wojtek-krysiak** [comment]
a - ok, so when you want to work on local admin-bro version you have to build it first. There are 2 commands for that: 

```bash
# building .ts -> .js on the backend
yarn build
```

and

```bash
# bundling all frontend files together
yarn bundle
```

So when you download admin-bro - run those 2 commands and then you can link it to your project
