### ISSUE TITLE
Enchancement request/question: Add non-database backed links to the left hand navigation

### ISSUE THREAD

**Issue by dogleg69** [SoftwareBrothers/admin-bro#197]
I am hoping I missed how to do this in the documentation.  If so, please point me to it.  I would like the ability to add links to the left hand navigation that are not backed by a datastore (not a CRUD function).  In my case, I have a google data studio link which I can embed as an iframe.  

How I solved this today was to create a model that used mongoose in which the schema has just one element -- called page of type String.  I then defined a resource in which the 'show' was the only option turned on.  In the 'list' definition, I created an after function that would pass the page link that points to google data studio.  I also defined a custom component bundle to display the link.  The component retrieved the link that was setup in the resource and inserted it into an iframe.

All of this allowed my to define a resource in the AdminBroOptions that would show my iframe.  But was a large hack and it still has the All Records.  

![image](https://user-images.githubusercontent.com/45242504/68124464-1e383500-fed5-11e9-8b97-b93a30bfbf68.png)

I would rather have some type of stubbed out resource type (like mongoose and sequelizejs) that can point to a .jsx file for static data that does not come from a database.  Similar to the dashboard but not on the homepage.

Is that already possible?

**Comment by wojtek-krysiak** [comment]
right now it is not possible - added to todo

**Comment by wojtek-krysiak** [comment]
added this in version 1.6.0-beta.1 just right now: https://admin-bro-example-app.herokuapp.com/admin/pages/customPage

simply add "pages" property in AdminBroOptions. Example:

```
pages: {
    customPage: {
      label: "Custom page",
      handler: async (request, response, context) => {
        return {
          text: 'I am fetched from the backend',
        }
      },
      component: AdminBro.bundle('./components/some-stats'),
    },
  },
```
