### ISSUE TITLE
Setting `NODE_ENV` to anything other than 'production' prevents bundling

### ISSUE THREAD

**Issue by danetrata-bvsecurity** [SoftwareBrothers/admin-bro#198]
Setting the common environment variable `NODE_ENV` to anything other than `production`  prevents the building of components. This threw me off when I was testing new components in a development environment but wasn't seeing any changes.

https://github.com/SoftwareBrothers/admin-bro/blob/27db32db81cdba0197afcb795ddffd74fea9641c/src/admin-bro.ts#L143#L148

Could this change to `ADMIN_BRO_DEV_ENV` instead? I'd be happy to make the PR.

**Comment by wojtek-krysiak** [comment]
when you launch app in production env it bundles components during the starting process (the code you pointed. All consecutive code (regardless of the environment) checks if there is a bundled file already in .adminbro. if yes use this file, if not - bundle components on every requrest.

So what I think happend - you changed env to production and bundle file has been created in .adminbro folder in your app. So now all calls are fetching this file.
Removing entire .adminbro should help.

**Comment by danetrata-bvsecurity** [comment]
That explains it. I'll close the issue for now unless the behavior should change. I'll add my notes to the documentation.

**Comment by wojtek-krysiak** [comment]
perfect - thanks
