### ISSUE TITLE
Filtering by referenced fields

### ISSUE THREAD

**Issue by Gr8z** [SoftwareBrothers/admin-bro#201]
Due to a recent update, I don't see any fields that are using refs in the filtering menu.

For example:

An **orders** collection with a field with a reference to a user in another collection.
Clicking on the filter button in orders collection and filtering users using a dropdown.

It was working perfectly in an older version. Is it no longer turned on by default?

**Comment by Gr8z** [comment]
Sorry, its still there, I just couldnt see it because it was on the bottom and there was no scroll bar.

Was able to use it if I zoomed out.

**Comment by wojtek-krysiak** [comment]
i have a fix and will deploy it tomorrow

**Comment by wojtek-krysiak** [comment]
fixed in @1.4.1
