### ISSUE TITLE
Log out button is not showing?

### ISSUE THREAD

**Issue by hannyudayana** [SoftwareBrothers/admin-bro#202]
Hi, all. Thanks for the great work on this project, it's really helpful.

Recently I tried the authenticatedRouter and it works perfectly. The only problem was, there was no log out button. Below is my configuration for adminbro

> const adminBro = new AdminBro({
>   resources: resources,
>   rootPath: '/admin',
>   logoutPath: '/admin/logout',
>   loginPath: '/admin/login',
> });

> const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
>   authenticate: async (email, password) => {
>     let loginResponse = null;
>     try {
>       const loginRequest = await axios.post(
>         config.API_DOMAIN + config.ADMIN_LOGIN_PATH,
>         { email: email, password: password },
>         { withCredentials: true },
>       );
>       loginResponse = await loginRequest.data;
>     } catch (err) {
>       loginResponse = err.response.data;
>     }
>     if (loginResponse && loginResponse.success) {
>       return loginResponse
>     }
>     return null
>   },
>   cookieName: 'cookiename',
>   cookiePassword: 'cookiepassword',
> });

Versions:
"admin-bro": "^1.4.0-beta.15"
"admin-bro-expressjs": "^0.2.0"
"admin-bro-sequelizejs": "^0.2.6"

Any insight on this problem will be appreciated :)
Cheers

**Comment by wojtek-krysiak** [comment]
`loginResponse` has to return [CurrentAdmin](https://softwarebrothers.github.io/admin-bro-dev/AdminBro.html#CurrentAdmin). I updated the admin-bro-expressjs docs here: https://softwarebrothers.github.io/admin-bro-dev/module-admin-bro-expressjs.html#.Authenticate

I think missing email in response could be the problem
