### ISSUE TITLE
Remove button for schema type "Array of strings" clears all rows values.

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#203]
`const schema = new mongoose.Schema({
cities: [String]
})`

[https://ibb.co/0s5qSvf](url)
In admin panel we have ability to add multiple rows with string values, for each row we have Remove button. Let's say we added 5 rows, and I want to remove the last one. Pressing Remove button in the last row causes to remove all values from all rows.

**Comment by wojtek-krysiak** [comment]
fixed in admin-bro@1.4.2
