### ISSUE TITLE
couple more customization issues

### ISSUE THREAD

**Issue by doubletuna** [SoftwareBrothers/admin-bro#208]
Hello

would it be possible to remove the "Welcome on board!" page and add my own content?

is it possible to customize the sidebar so the navigation won't include the machine? (localhost / amazon server)

cheers

DT

**Comment by wojtek-krysiak** [comment]
1. yep - you have to create your dashboard component: https://softwarebrothers.github.io/admin-bro-dev/tutorial-06-writing-react-components.html and put it to the `dashboard.component` (https://softwarebrothers.github.io/admin-bro-dev/tutorial-07-custom-dashboard.html)
2. When you pass resources in [AdminBroOptions](https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#resources) you can modify their parent name (https://softwarebrothers.github.io/admin-bro-dev/ResourceOptions.html#parent)
