### ISSUE TITLE
Is it possible to have related resources to be edited in the same view ?

### ISSUE THREAD

**Issue by SiTox** [SoftwareBrothers/admin-bro#209]
Hi guys, 
Great project. I have a quick question: For example I want to show on one page, list of records and lower, have their details or related entities. Is it possible to customize admin-bro like that ? 
Thanks

**Comment by wojtek-krysiak** [comment]
yes - you have to define custom component for a property.

Take a look here: https://softwarebrothers.github.io/admin-bro-dev/tutorial-06-writing-react-components.html
and here https://softwarebrothers.github.io/admin-bro-dev/BasePropertyComponent.html
