### ISSUE TITLE
While adding resource actions component,it showing 'Cannot read params of undefined'.

### ISSUE THREAD

**Issue by maheshrapelli141** [SoftwareBrothers/admin-bro#210]
Hi, 
I tried to add component to new resource action, but it showing error as 
**"TypeError: Cannot read property 'params' of undefined
See development console for more details..."**

**Comment by wojtek-krysiak** [comment]
can you paste the component code?

**Comment by wojtek-krysiak** [comment]
since there is no answer - closing this one

**Comment by bhoodream** [comment]
How can it be that when rendering an action component, we have a prop `record` `underfined` from which we take the `params`?

I have the same problem. If you need a code, I can add it later.

AdminBro version: 3.2.5.

**Comment by bhoodream** [comment]
Hmm, after removing `.adminbro` and restarting the application, this folder was created with the correct `.entry.js` (it now included my component import) and it worked.

Can you explain, why the `.adimnbro` folder was not updated?

I found a recommendation to delete this folder here https://stackoverflow.com/questions/61745264/unable-to-use-custom-componets-in-adminbro
