### ISSUE TITLE
Application crashing when passing resources by giving entire database

### ISSUE THREAD

**Issue by uplabhijit** [SoftwareBrothers/admin-bro#212]
Passing resources by giving entire database not working

`node server2.js
(node:67259) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

`(node:67259) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'AdminBro' before initialization
    at run (/Users/--/Working/admin-pro/server2.js:22:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:67259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by wojtek-krysiak** [comment]
please write mongoose version and admin-bro* versions. also can you paste the code of server2.js?

**Comment by uplabhijit** [comment]
![image](https://user-images.githubusercontent.com/41364678/69476074-1e07c700-0dfb-11ea-86d4-ca430e455f47.png)
![image](https://user-images.githubusercontent.com/41364678/69476088-3a0b6880-0dfb-11ea-91f3-8e3bed057080.png)

`
// ==========  server2.js ==============
// Requirements
const AdminBro = require('admin-bro')
const AdminBroMongoose = require('admin-bro-mongoose')
const mongoose = require('mongoose')
AdminBro.registerAdapter(AdminBroMongoose)

// Initializ Database along with models
const User = mongoose.model('User', { name: String, email: String, surname: String })
const Admin = mongoose.model('Admin', { name: String, email: String})

const run = async () => {
  const mongooseDb = await mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true })

//   // Passing resources by giving entire database
//   const AdminBro = new AdminBro({
//     databases: [mongooseDb],
//     //... other AdminBroOptions
//   })

  // Passing resources one by one
  const AdminBro = new AdminBro({
    resources: [users, companies],
    //... other AdminBroOptions
  })
}

run()
// ... 
`

**Comment by wojtek-krysiak** [comment]
I see the error

```
 const AdminBro = new AdminBro({
   databases: [mongooseDb],
   //... other AdminBroOptions
})
```

should be changed to: 

```
 const adminBro = new AdminBro({
   databases: [mongooseDb],
   //... other AdminBroOptions
})
```

AdminBro -> adminBro

I will fix the docs
