### ISSUE TITLE
"Adding custom authentication" Documentation Edit Suggestion

### ISSUE THREAD

**Issue by amityaffliction** [SoftwareBrothers/admin-bro#213]
* Current documentation

```
let router = express.Router()
router.use((req, res, next) => {
  if (req.session && req.session.admin) {
    req.adminUser = req.session.admin
    next()
  } else {
    res.redirect(adminBro.options.loginPath)
  }
})
router = AdminBroExpress.buildRouter(adminBro, router)
```

Current documentation works well. But Logout button doesn't seem to appear. To work that around,

`req.adminUser = req.session.admin`
should be 
`req.session.adminUser = req.session.admin`

and `req.session.admin` must be object containing email field 

since current frontend component renders logout button with information inside `req.session.adminUser`

**Comment by wojtek-krysiak** [comment]
thx - I will add that in the next release (probably this week)
