### ISSUE TITLE
Questions regarding Adminbro's filter

### ISSUE THREAD

**Issue by hannyudayana** [SoftwareBrothers/admin-bro#214]
1. Is it possible to automatically close the filter window after applying filter?

2. Consider this scenario:
- I applied some filters to the list
- I opened the info page for one of the record
- Then I pressed back button on the info page
- The filters are reset so I have to re-apply the filters
- Is it possible to retain the filters instead of re-applying it again?

**Comment by wojtek-krysiak** [comment]
1. it is not possible.

2. possible fix :)
* hmm - when you hit back in the browser it should work.
* Back button in the UI always goes to the list. I could change this to taking the value from history (as a back button in the browser) but in case of going there from another resource (i.e. by clicking custom link) it will also redirect users there.

So right now closing this issue.
