### ISSUE TITLE
Unable to hide field while editing and saving separately.

### ISSUE THREAD

**Issue by princesoni1989** [SoftwareBrothers/admin-bro#216]
Hi All,

I want to hide one field named password while I am on edit/update page. If I use the below code
` password: {
        isVisible: { edit: false },
      }
`
It also hides the password filed while I am creating the record. Is there any way to hide field only while editing and not while creating.

**Comment by wojtek-krysiak** [comment]
no - they are bound together. The only way of showing different fields in show and in edit is to override entire action component. Or to override property component and check if record from [Props](https://softwarebrothers.github.io/admin-bro-dev/BasePropertyComponent.html#BasePropertyProps) has id

**Comment by yadavgoku** [comment]
Any workaround on this?

**Comment by anthonytison** [comment]
One solution would be to create a component which will hide or remove the data you don't wanna display.  

<pre>
import * as React from 'react';

const HideFiledComponent = ({record}) => {

    React.useEffect(() => {
        if(document.querySelector('YOUR TARGET')){
            document.querySelector('YOUR TARGET').remove();
        }
    }, []);

    return (
        <>
         
        </>
    )
}

export default AuthenticationComponent
</pre>

**Comment by gmeneguz** [comment]
I run in to a similar issue, i wanted to show a property in edit but not in new. The `layout` key solved my problem, maybe can help someone else too:

```
new AdminBro({
 resources: [{
   resource: Model,
   actions: {
      new: {
         layout: [  "property1", "property2"]  // Array with the properties
      }
   }
 }]
}) 
```

**Comment by Whitelion2021** [comment]
> I run in to a similar issue, i wanted to show a property in edit but not in new. The `layout` key solved my problem, maybe can help someone else too:
> 
> ```
> new AdminBro({
>  resources: [{
>    resource: Model,
>    actions: {
>       new: {
>          layout: [  "property1", "property2"]  // Array with the properties
>       }
>    }
>  }]
> }) 
> ```

Thanks buddy its working fine
