### ISSUE TITLE
Questions regarding Adminbro's date field

### ISSUE THREAD

**Issue by hannyudayana** [SoftwareBrothers/admin-bro#217]
1. Is it possible to change the date format of date fields in list and view mode?

**Comment by wojtek-krysiak** [comment]
you will have to override property component (take a look how to do this: https://softwarebrothers.github.io/admin-bro-dev/BasePropertyComponent.html#BasePropertyProps)

**Comment by sunitJindal** [comment]
> you will have to override property component (take a look how to do this: https://softwarebrothers.github.io/admin-bro-dev/BasePropertyComponent.html#BasePropertyProps)

This link is no longer functional
