### ISSUE TITLE
Can't save 

### ISSUE THREAD

**Issue by CaptainKO** [SoftwareBrothers/admin-bro#218]
I can't change some of the fields. I have no ideas why that is.[
![Capture](https://user-images.githubusercontent.com/32269291/70393822-f3d01f00-1a20-11ea-86ec-d8a71f4813b9.PNG)
](url)

**Comment by wojtek-krysiak** [comment]
can you write your ORM setup with the schema

**Comment by CaptainKO** [comment]
Thanks @wojtek-krysiak I have fixed the issue. It turned out I can't use mongoose schema to create model for admin-bro. :D
