### ISSUE TITLE
Resource "list" action switching through pages do not work

### ISSUE THREAD

**Issue by amityaffliction** [SoftwareBrothers/admin-bro#219]
I have Sequelize Tables

1. PlayList : this stores playlists
2. Video : this stores videos
3. PlayListVideo: this stores playlists and video association

I want to associate Video to PlayList at Admin Bro.  But there seems to be a bug when trying to "list" action 'through' table. When just clicking the menu it works fine. But when I try to go to page 2 and 3 and on, there is still loading "record" but when you refresh it it disappears. If I navigate through pages, this "loading record" keeps adding up. This only happens with many-to-many "through" table.

Could you please way to fix this or before that could you guys give me some workaround?

<img width="913" alt="스크린샷 2019-12-09 오후 4 02 41" src="https://user-images.githubusercontent.com/8777275/70414450-75fe2900-1a9d-11ea-90cb-1e1e36074163.png">
Picture 1. page 1
<img width="893" alt="스크린샷 2019-12-09 오후 4 02 50" src="https://user-images.githubusercontent.com/8777275/70414452-77c7ec80-1a9d-11ea-8223-03a29c89d242.png">
Picture 2. when navigated to page2
<img width="895" alt="스크린샷 2019-12-09 오후 4 02 57" src="https://user-images.githubusercontent.com/8777275/70414455-7991b000-1a9d-11ea-9d4d-e380aa18f87e.png">
Picture 3. when navigated to page3. you can see those adding up

**Comment by amityaffliction** [comment]
Currently, VideoID and PlayListID field's type is 'reference' so It gets Video and PlayList table's field where "isTitle" is set true.

**Comment by wojtek-krysiak** [comment]
do you have any errors in the terminal / chrome console?

**Comment by amityaffliction** [comment]
No. It does not show any errors on server nor client side. just bunch of deprecation warnings

```
Deprecation: this "ViewHelpers#listUrl" will be removed in the next versions.
      Please use "resourceActionUrl({ resourceId, actionName: 'list'})"
      instead

```

If I turn on server database query logging this shows

```
Executing (default): SELECT "createdAt", "updatedAt", "playListId", "videoId" FROM "playListVideos" AS "playListVideo" ORDER BY "playListVideo"."playListId" ASC LIMIT 10 OFFSET 0;
Executing (default): SELECT "id", "video_url", "title", "thumbnail_url", "description", "video_duration", "youtube_video_id", "published_at", "youtube_like_count", "youtube_view_count", "app_view_count", "app_like_count", "youtube_username", "youtube_user_image", "external", "createdAt", "updatedAt", "userId" FROM "videos" AS "video" ORDER BY "video"."title" ASC LIMIT 50 OFFSET 0;
Executing (default): SELECT "id", "public", "title", "thumbnail_url", "item_count", "description", "youtube_playlist_id", "published_at", "external", "createdAt", "updatedAt", "categoryId", "userId" FROM "playLists" AS "playList" ORDER BY "playList"."title" ASC LIMIT 50 OFFSET 0;
Executing (default): SELECT "id", "public", "title", "thumbnail_url", "item_count", "description", "youtube_playlist_id", "published_at", "external", "createdAt", "updatedAt", "categoryId", "userId" FROM "playLists" AS "playList" WHERE "playList"."id" IN (1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
Executing (default): SELECT "id", "video_url", "title", "thumbnail_url", "description", "video_duration", "youtube_video_id", "published_at", "youtube_like_count", "youtube_view_count", "app_view_count", "app_like_count", "youtube_username", "youtube_user_image", "external", "createdAt", "updatedAt", "userId" FROM "videos" AS "video" WHERE "video"."id" IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
GET /admin/api/resources/videos/search/ 200 63.724 ms - 97303
GET /admin/api/resources/playLists/search/ 200 84.741 ms - 42354
Executing (default): SELECT count(*) AS "count" FROM "playListVideos" AS "playListVideo";
GET /admin/api/resources/playListVideos/actions/list 200 147.524 ms - 38451
```
**Code 1. When I first click  "PlayListVideo" resource tab**

```
Executing (default): SELECT "createdAt", "updatedAt", "playListId", "videoId" FROM "playListVideos" AS "playListVideo" ORDER BY "playListVideo"."playListId" ASC LIMIT 10 OFFSET 10;
Executing (default): SELECT "id", "public", "title", "thumbnail_url", "item_count", "description", "youtube_playlist_id", "published_at", "external", "createdAt", "updatedAt", "categoryId", "userId" FROM "playLists" AS "playList" WHERE "playList"."id" IN (1, 1, 1, 1, 1, 1, 1, 2, 2, 2);
Executing (default): SELECT "id", "video_url", "title", "thumbnail_url", "description", "video_duration", "youtube_video_id", "published_at", "youtube_like_count", "youtube_view_count", "app_view_count", "app_like_count", "youtube_username", "youtube_user_image", "external", "createdAt", "updatedAt", "userId" FROM "videos" AS "video" WHERE "video"."id" IN (11, 12, 13, 14, 15, 16, 17, 18, 19, 20);
Executing (default): SELECT count(*) AS "count" FROM "playListVideos" AS "playListVideo";
GET /admin/api/resources/playListVideos/actions/list?page=2 200 83.050 ms - 38450
```
**Code 2. When I switch to page 2 of  "PlayListVideo" resource tab(Where that weird loading behavior occurs)**

**Comment by wojtek-krysiak** [comment]
ASC LIMIT 50 OFFSET 0 is for the filter (it populates select fields for all references)

**Comment by wojtek-krysiak** [comment]
can you set isTitle for createdAt field in Video resources and let me know if that helped?

```
resources: [..., {
resource: Video,
options: {
  properties: {
    createdAt: {isTitle: false, } // or created_at - depending on your schema,
  }
}

}]
```

**Comment by wojtek-krysiak** [comment]
can you check the payload returned by admin-bro after visiting 2nd page (it should be in the chrome terminal in Network tab - preview for list xhr action)

**Comment by amityaffliction** [comment]
Thank you for your reply. I was kind of lost. You are so kind.

<img width="1096" alt="스크린샷 2019-12-11 오후 2 32 50" src="https://user-images.githubusercontent.com/8777275/70594263-4a0cb000-1c23-11ea-859e-3bfe784a298b.png">
**Picture 1. Picture of page=2 getting error**. (after visiting page1, error propagates and even I visit other resource tab, same behavior happens)

[list?page=2.json.zip](https://github.com/SoftwareBrothers/admin-bro/files/3948619/list.page.2.json.zip)
This is chrome developer tab - network - XHR full response to JSON. 

There seems to be no errors in individual field.

If this helps,
<img width="323" alt="스크린샷 2019-12-11 오후 2 56 31" src="https://user-images.githubusercontent.com/8777275/70595420-b210c580-1c26-11ea-83a7-3e60e3d8171d.png">
<img width="1072" alt="스크린샷 2019-12-11 오후 2 55 16" src="https://user-images.githubusercontent.com/8777275/70595439-b9d06a00-1c26-11ea-82ad-1d6d221e9786.png">
**Picture 2,3. When I go to "PlayList" resource tab after visiting "PlayListVideo" resource tab**

 if I click "PlayListVideo" and go to other resource tab, same error seem to occur. Interestingly, you can see at "PlayList" resource, there seems to be a record with only 2 field(If I click "info" then it turns out that's "PlayListVideo"'s record). I have no idea but can this be related with rendering async data at front-end? because to me payload seems fine.

should I try to make example reproduces this behavior that you can try on? (sequelize, postgresql, many-to-many through table with two foreign keys )

**Comment by wojtek-krysiak** [comment]
It seems that your join table doesn't have an ID field. 
playlistId and videoId in the database are probably treated as the primary key but admin requires each resource to have an unique ID property.

Simply add id as primary key and it should solve the problem.

**Comment by amityaffliction** [comment]
Thank you so much :)
