### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by PixelsCommander** [SoftwareBrothers/admin-bro#222]
When making a decision on using a dashboard it is very important to understand the design system behind the project as it affects the set of widgets available. Which design system does your project use? If there is no design system now. Is there a plan to use the one from Ant, Microsoft or Shopify as they have the most complete list of widgets to the date? For us having a well-established design system in a dashboard is crucial.

**Comment by wojtek-krysiak** [comment]
right now it is built on https://bulma.io/ but we are thinking about moving to Ant.

regarding the timeframe, we will make a final decision on ~February, since now we are tesing ant on a different project.

**Comment by PixelsCommander** [comment]
Never heard of Bulma. Also, I do not see any date and color pickers which are crucial.
