### ISSUE TITLE
Ability to set custom favicon for admin

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#224]
It would be great to set custom favicon image for admin panel. May be to `branding` setting?
```
branding: {
	companyName: 'Company',
	logo: "/images/logo.png",
	softwareBrothers: false
}
```

**Comment by wojtek-krysiak** [comment]
thanks. I've just added this to admin-bro@1.5.0-beta.8

```
branding: {
  favicon: 'url-to-your-favicon',
}
```

I will update the docs after releasing 1.5.0 version (without beta)

**Comment by dmitryLagoda** [comment]
Thank you! And thanks for great product, btw!
