### ISSUE TITLE
Authorization is broken in new 1.5 beta release 

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#225]
Not sure, are you  aware of this issue, or may be authorization will be changed in new 1.5 release, but it current beta version it's broken. Looks like formidable brought the issue. Just so you know.
```
    "admin-bro": "^1.5.0-beta.7",
    "admin-bro-expressjs": "^0.4.0-beta.2",
```
`AdminBroExpressjs.buildAuthenticatedRouter`

**Comment by wojtek-krysiak** [comment]
it supposes to work with the latest admin-bro-expressjs :( - what exactly happens - do you have some errors in terminal?

**Comment by dmitryLagoda** [comment]
well, not too much. It just stucks. If I do downgrade to stable release 1.4.x it works again. If you can't reproduce, I will send my specific code, but it's all the same from admin-bro docs.
```
POST /admin/login 500 120004.930 ms - -
Error: Request aborted
    at IncomingMessage.<anonymous> (/Users/dima/projects/takjak-web/node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:210:5)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at abortIncoming (_http_server.js:492:9)
    at socketOnClose (_http_server.js:485:3)
    at Socket.emit (events.js:215:7)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at TCP.<anonymous> (net.js:658:12)
```

**Comment by wojtek-krysiak** [comment]
hmm - I cannot reproduce that. It works on the example from the docs in my case :( - can you provide some code?

**Comment by dmitryLagoda** [comment]
Thanks for response, indeed, the issue wasn't in adminbro module. 
The issue is in `express-formidable`. seems it doesn't work well with
`app.use(express.urlencoded({ extended: false }));` If i comment this line in my app setup admin login starts to work. 
There is an opened issue in formidable github: 
https://github.com/utatti/express-formidable/issues/22
What is your opinion how to better resolve this? For now I came up to this solution:
```
app.use('/admin', formidableMiddleware());
app.use(/^\/(?!admin).*/, express.urlencoded({ extended: false }));
```
but not sure it's good at all. May be you have better ideas? Still, this is good to mention for `DropArea` component docs.

**Comment by dmitryLagoda** [comment]
Hey, Wojciech! Sorry to bother you again, but I have issues with  `DropArea` in 1.5.0 release. It works fine with 
```
    "admin-bro": "1.5.0-beta.7",
    "admin-bro-expressjs": "^0.4.0",
    "admin-bro-mongoose": "^0.3.1",

```
I get the file object in after hook, everything is good. I use the code from the example your provided in https://github.com/SoftwareBrothers/admin-bro/issues/95
If I update to   "admin-bro": "1.5.0-beta.8" - I don't get `file` object anymore, it's empty. (File name, size, types still work). I tried to use both the code from 95'th issue and  the code from current docs  https://softwarebrothers.github.io/admin-bro-dev/DropArea.html , but without any success. 
May be you could add `DropArea` to your example app? May be I missed smth simple. Thank you!

**Comment by wojtek-krysiak** [comment]
I will try to make [jscast](jscasts.tv) "file upload in AdminBro) but it will be after Christmas, so leaving this open.

I thought about adding this to the example app but it will mean that some random people will be able to upload random things so I abandoned the idea.

**Comment by dmitryLagoda** [comment]
thank you, Wojciech! I think you can add just DropArea and after hook with console.log(file) object to example app, that still will be very useful.  And btw, does DropArea works fine for you with latest release?

**Comment by Chukstart** [comment]
> Thanks for response, indeed, the issue wasn't in adminbro module.
> The issue is in `express-formidable`. seems it doesn't work well with
> `app.use(express.urlencoded({ extended: false }));` If i comment this line in my app setup admin login starts to work.
> There is an opened issue in formidable github:
> [utatti/express-formidable#22](https://github.com/utatti/express-formidable/issues/22)
> What is your opinion how to better resolve this? For now I came up to this solution:
> 
> ```
> app.use('/admin', formidableMiddleware());
> app.use(/^\/(?!admin).*/, express.urlencoded({ extended: false }));
> ```
> 
> but not sure it's good at all. May be you have better ideas? Still, this is good to mention for `DropArea` component docs.

And what does your formidableMiddleware look like?

**Comment by dmitryLagoda** [comment]
Not sure I 

> > Thanks for response, indeed, the issue wasn't in adminbro module.
> > The issue is in `express-formidable`. seems it doesn't work well with
> > `app.use(express.urlencoded({ extended: false }));` If i comment this line in my app setup admin login starts to work.
> > There is an opened issue in formidable github:
> > [utatti/express-formidable#22](https://github.com/utatti/express-formidable/issues/22)
> > What is your opinion how to better resolve this? For now I came up to this solution:
> > ```
> > app.use('/admin', formidableMiddleware());
> > app.use(/^\/(?!admin).*/, express.urlencoded({ extended: false }));
> > ```
> > 
> > 
> > but not sure it's good at all. May be you have better ideas? Still, this is good to mention for `DropArea` component docs.
> 
> And what does your formidableMiddleware look like?

Not sure what you mean. formidableMiddleware is a https://github.com/utatti/express-formidable, which is used by AdminBro. I used express.urlencoded() middleware in order decode requests params, which is pretty  a standard by Express. Now I just don't use it for admin route. 
`app.use(/^\/(?!admin).*/, express.urlencoded({ extended: false }));`
