### ISSUE TITLE
Is current admin-bro able to add custom page at side bar?

### ISSUE THREAD

**Issue by amityaffliction** [SoftwareBrothers/admin-bro#228]
<img width="491" alt="스크린샷 2019-12-17 오후 2 40 19" src="https://user-images.githubusercontent.com/8777275/70967922-322da400-20db-11ea-917f-0f060f7b755e.png">

I would like to add custom page that can be accessed through side bar. 

But as far as I can find, only way to create item in the left side navigation bar is to add resource.

How can I customize left navigation bar so that I can create a custom page?

**Comment by amityaffliction** [comment]
Duplicated issue.

**Comment by ivan-lolivier-iugo** [comment]
@amityaffliction You should link the other issue ;)

**Comment by wojtek-krysiak** [comment]
you can use https://adminbro.com/AdminBroOptions.html#pages

**Comment by Naozumi520** [comment]
@wojtek-krysiak The link is not working anymore, it redirect me to the main page.
Was it still possible to do it?

**Comment by ElectroMyStyle** [comment]
> @wojtek-krysiakСсылка уже не работает, перенаправляет на главную. Было ли еще возможно это сделать?

https://docs.adminjs.co/AdminJSOptions.html#pages

**Comment by Naozumi520** [comment]
> https://docs.adminjs.co/AdminJSOptions.html#pages

Thanks!

**Comment by yashRechargezap** [comment]
Hi How to achieve this? the link is says page does't exists.

**Comment by sdepold** [comment]
https://docs.adminjs.co/ui-customization/writing-your-own-components#creating-custom-pages

**Comment by decamps-enmanuel** [comment]
Following up on this, how would one achieve adding a page under a resource's navigation parent?

For example:

Administration Zone
    |-> Resource 1
    |-> Custom Page


currently it's only leetting me create custom pages under the "Pages" Label and it's at the bottom of the sidebar.
