### ISSUE TITLE
sign out element doesnt show up

### ISSUE THREAD

**Issue by doubletuna** [SoftwareBrothers/admin-bro#230]
Hello,

First of all, thanks for all the latest addition & assistance!

I'm trying to add the sign out option, do I have to use currentAdmin or Authenticate?

login to the admin is done via passport

it would be great if you had a simple method of showing the sign out button, regardless.

Cheers

DT

**Comment by wojtek-krysiak** [comment]
In [authenticate method](https://softwarebrothers.github.io/admin-bro-dev/module-admin-bro-expressjs.html#.Authenticate) (assuming you use express) you have to return CurrentAdmin with email field. Then sign out button should appear.

**Comment by doubletuna** [comment]
yes, I'm using express
can I combine that into the passport process?

**Comment by wojtek-krysiak** [comment]
haven't use passport so far so I won't be able to help :(

**Comment by nogalasman** [comment]
use your passport.session to store the user: 
passport.session.user = user

then, in you router, in default route:
if (passport.session.user) {
      req.session.adminUser = passport.session.user
}
