### ISSUE TITLE
filtering resource by user role

### ISSUE THREAD

**Issue by doubletuna** [SoftwareBrothers/admin-bro#231]
Hello,

Is there a way to filter records in a specific resource, based on user role (or other param under user)

i.e. 

table vehicles - id, model, type
values:
1, 'fiat', 'truck'
2, 'alpha romeo', 'sports car'
..

I'd like to be able to show all records to specific user, limit 'truck' records to another user and 'sports car' to a third user.

Cheers

DT

**Comment by wojtek-krysiak** [comment]
it is possible - you will have to handle [Before hook](https://softwarebrothers.github.io/admin-bro-dev/Action.html#before) for list action to pass filter there. Also you will have to disable property 'model' in filter sidebar.

It could look something like this:
```
{
actions: {
  list: {
    before: async (request, context) => {
      const { currentAdmin } = context
      return {
        ...request,
        query: {
           ...request.query,
           'filters.model': currentAdmin.isTrucker ? 'truck' : 'fiat'
        }
      }
    },
  }
},
properties: {
   model: {
     isVisible: {filter: false, show: true, edit: true, list: true},
   }
}
```

**Comment by doubletuna** [comment]
@wojtek-krysiak right, but how/where can I init currentAdmin? (I also need that for the logout option)

**Comment by wojtek-krysiak** [comment]
it is returned by the "authenticate" method in [buildAuthenticatedRouter](https://softwarebrothers.github.io/admin-bro-dev/module-admin-bro-expressjs.html#.buildAuthenticatedRouter).

You can take a look at this tutorial: https://softwarebrothers.github.io/admin-bro-dev/tutorial-08-rbac.html - it covers authentication with the roles

**Comment by doubletuna** [comment]
@wojtek-krysiak awesome, I've managed to apply the filter

is it possible to change a resource "list" to list: { isVisible: false } dynamically? (i.e. hide or show tables in the sidebar based on role)

cheers

DT

**Comment by wojtek-krysiak** [comment]
yes both isVisible and isAccesible can take a function. Take a look at Action interface documentation: https://softwarebrothers.github.io/admin-bro-dev/Action.html#isAccessible

**Comment by nadaaskora** [comment]
@wojtek-krysiak can we apply filter upon to a certain role like if a user is admin show all and if he is a user filter according to his data
