### ISSUE TITLE
Can't update any fields since 1.5

### ISSUE THREAD

**Issue by Gr8z** [SoftwareBrothers/admin-bro#234]
Hi,

I am currently on 1.5.2, and I can no longer update and save any fields through the admin panel.

I update a field, click save. It shows a success message but the DB stays unaffected and the changes are not saved.

Proof:
![demo](https://i.imgur.com/0vjfYL7.gif)

**Comment by wojtek-krysiak** [comment]
what framework do you use? is it express, if so, do you use the latest version of admin-bro-expressjs?

**Comment by Gr8z** [comment]
Oh I see, I was using an older version of admin-bro-expressjs. Updating to 0.4 fixed the issue completely. 


Thanks
