### ISSUE TITLE
Postgres ENUM type Search problem

### ISSUE THREAD

**Issue by amityaffliction** [SoftwareBrothers/admin-bro#236]
I am currently using PostgreSQL with Admin Bro.

I currently have **PlayList table** which has attribute **type** which is **ENUM('free','premium','user')**. Everything seemed fine but when I view model with **list** action and perform **search** with specific ENUM value there seems to be a problem. ( in case below, I searched with "type=premium")

```
    sql: `SELECT "id", "title", "thumbnail_url", "item_count", "description", "youtube_playlist_id", "published_at", "external_updated_at", "type", "createdAt", "updatedAt", "categoryId", "userId" FROM "playLists" AS "playList" WHERE "playList"."type" LIKE '%premium%' ORDER BY "playList"."title" ASC LIMIT 10 OFFSET 0;`,
    parameters: undefined
  },
  original: error: operator does not exist: "enum_playLists_type" ~~ unknown
```

I think this part is problem **WHERE "playList"."type" LIKE '%premium%'** . How can I properly search on the ENUM types?

**Comment by mahnunchik** [comment]
Related https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/19

**Comment by wojtek-krysiak** [comment]
@amityaffliction I've just merged that. Please download the latest admin-bro and admin-bro-sequelize
