### ISSUE TITLE
 error TS2304: Cannot find name 'FileList'.  8 declare type OnUpload = (files: FileList | null) => void;   

### ISSUE THREAD

**Issue by lp-bayramali** [SoftwareBrothers/admin-bro#237]
## Description

After installing the AdminBro I'm not able to run tsc command to create a dist version of my project. Post install tsc command retrieves this error:

```
node_modules/admin-bro/types/src/frontend/components/app/drop-area.d.ts:8:33 - error TS2304: Cannot find name 'FileList'.

8 declare type OnUpload = (files: FileList | null) => void;
```

## Versions:
"admin-bro": "^1.5.2",
"admin-bro-expressjs": "^0.4.0",

## Package manager: 
npm

## Superset:
typescript

**Comment by wojtek-krysiak** [comment]
you have to add DOM types to tsconfig. Take a look at this example: https://github.com/SoftwareBrothers/admin-bro-dev/blob/master/example-typeorm/tsconfig.json
