### ISSUE TITLE
records do not show 

### ISSUE THREAD

**Issue by nattts** [SoftwareBrothers/admin-bro#238]
records do not show after being saved. 

in the latest release v1.6.0-beta.5

**Comment by wojtek-krysiak** [comment]
which versions and kind of the adapter do you use?

**Comment by nattts** [comment]
@wojtek-krysiak 
i'm using admin-bro-mongoose@0.2.0

**Comment by wojtek-krysiak** [comment]
please try to install 0.4.0-beta.0 and let me know how it works for you (this particular version is installed on [example app](https://admin-bro-example-app.herokuapp.com/admin) right now).

**Comment by nattts** [comment]
@wojtek-krysiak 
thanks, it solved the problem.
