### ISSUE TITLE
frontend ts conflict during compilation

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#240]
Who didn't set `"skipLibCheck": true` or `"lib": ["dom" ... ]` to `tsconfig.json` will see the error all the time.
```
c7:22:29 PM - File change detected. Starting incremental compilation...

node_modules/admin-bro/types/src/frontend/components/app/drop-area.d.ts(8,33): error TS2304: Cannot find name 'FileList'.
```
Not such a big probem.
Possible solution: splitting backend and frontend to different packages.

**Comment by Arteha** [comment]
v1.6.0-beta.5

**Comment by wojtek-krysiak** [comment]
duplicates #237 - simly add DOM types to tsconfig. But regarding spliting you are right. I am thinking about extracting frontend components to a separate repository but this is the plan for march probably
