### ISSUE TITLE
Left side menu item is not selected if we open admin page from direct url

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#241]
Let's say we have resource `User`.
If I click the menu item for this resource in left side menu it displays `List` page for users. Menu item `Users` is selected and highlighted.
But if we open this page from the url `.../admin/resources/User/actions/list` menu item is not selected. 
<img width="759" alt="Screen Shot 2019-12-26 at 3 45 13 PM" src="https://user-images.githubusercontent.com/2717056/71478211-1fac1c80-27f7-11ea-8cc1-40a86d81ab65.png">

**Comment by wojtek-krysiak** [comment]
fixed with the release:  admin-bro@1.6.0-beta.12
