### ISSUE TITLE
Enhancement: display applied filter in the grid

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#242]
Right now if the filter is applied and right side filter panel is hidden,  it's hard to understand if the content is filtered or no. E.g. if you opened filtered page from the url.
It'd be awesome to display that info for the grid.
I would add `Filters applied: email=="aaa"` after `All Record 46` and highlight the Filter button as well. 
<img width="1309" alt="Screen Shot 2019-12-26 at 4 44 03 PM" src="https://user-images.githubusercontent.com/2717056/71479894-1c1c9380-27ff-11ea-9c6b-13877da20f45.png">

**Comment by wojtek-krysiak** [comment]
similar as #246 - closing because filters will be rewritten
