### ISSUE TITLE
All params are strings

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#243]
![image](https://user-images.githubusercontent.com/22820043/71494521-15663e80-2848-11ea-8e80-5e2c961e743f.png)
Should I convert params like `convertFilter(params)` does? Currently I have problems with boolean. I can't set true.

**Comment by wojtek-krysiak** [comment]
yes - all fields are strings. I would fix that in 'prepareParamsBeforeSave' method: https://github.com/Arteha/admin-bro-typeorm/blob/master/src/Resource.ts#L217

**Comment by Arteha** [comment]
No worries I'll add this also. You're so busy with the rest.

**Comment by Arteha** [comment]
Fixed in `admin-bro-typeorm@0.1.6-alpha.5`
