### ISSUE TITLE
Enhancement: do not drop the filter after returning from Info page

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#246]
1) Apply filters to the grid
2) Go to resource model Info page (or Edit page)
3) go back using the back button on the page (not browser back button), filters are dropped.

**Comment by wojtek-krysiak** [comment]
Hi, @dmitryLagoda. Thanks for the suggestion. We will rebuild the UI a little bit in version 2.0 that filters will be probably in a list  (there wont be a "slide" filters bar). So I am closing this one since it will be rewritten either way
