### ISSUE TITLE
If property is 0 it looks like null

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#247]
![image](https://user-images.githubusercontent.com/22820043/71546809-3343b880-299a-11ea-997d-b183ee4e1645.png)
![image](https://user-images.githubusercontent.com/22820043/71546815-46ef1f00-299a-11ea-958b-e79e0b85c172.png)
but there are zeros:
![image](https://user-images.githubusercontent.com/22820043/71546825-671ede00-299a-11ea-835c-a47c7f8e0cd2.png)

**Comment by wojtek-krysiak** [comment]
fixed with 1.6.0-beta.11
