### ISSUE TITLE
Possibility to set null into fk field

### ISSUE THREAD

**Issue by Arteha** [SoftwareBrothers/admin-bro#250]
Hello. Extremly needed basic feature.
![image](https://user-images.githubusercontent.com/22820043/71589197-4c787080-2b24-11ea-83df-33c8540fc251.png)
Like a cross in a filter 
![image](https://user-images.githubusercontent.com/22820043/71589304-b6911580-2b24-11ea-9af5-4f4bb0f4632e.png)

**Comment by wojtek-krysiak** [comment]
duplicates #161
