### ISSUE TITLE
Login keeps pending

### ISSUE THREAD

**Issue by derkweijers** [SoftwareBrothers/admin-bro#252]
Hi!

I'm re-adding admin-bro to my project, however I'm having a hard time getting the authentication to work.

I'm building the following router:
```
const ADMIN = {
  email: 'test@example.com',
  password: 'password',
};

const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
    authenticate: async (email, password) => {
      console.log('debug');
      if (ADMIN.password === password && ADMIN.email === email) {
        return ADMIN;
      }
      return null;
    },
    cookieName: 'adminbro',
    cookiePassword: 'somepassword',
  },
);

module.exports = router;
```

I'm then using the exported router in my entry file to mount it in the express app:
`app.use('/admin', adminRouter);`

The login page successfully loads, but as soon as I try to login nothing happens. In the Chrome Debug I see that the call to the `/admin/login` endpoint, but it just keeps pending.

Am I missing something? I'm pretty lost at this moment.

Thanks!

**Comment by wojtek-krysiak** [comment]
do you have any information in the terminal (where you launch the express app)?. Usually, it should print something.

You can add console.log/debugger here: https://github.com/SoftwareBrothers/admin-bro-expressjs/blob/master/plugin.js#L157 (you will find this file in your node_modules/admin-bro-expressjs/plugin.js

**Comment by derkweijers** [comment]
The only things I see in the terminal are:
```
express-session deprecated undefined resave option; provide resave option node_modules/admin-bro-expressjs/plugin.js:138:14
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules/admin-bro-expressjs/plugin.js:138:14
AdminBro: bundle ready
MongoDB connected!
Article indexing complete
Blog indexing complete
```

As for the console.log/debugger, nothing happens. As if the entire authenticate method isn't even called.

**Comment by derkweijers** [comment]
After more testing, I found that the following plugins cause this problem:
```
app.use(express.urlencoded({ extended: false }));
app.use(bodyParser.urlencoded({ extended: false }));
```
No idea why though.

**Comment by wojtek-krysiak** [comment]
can you put them after the AdminBro setup? and please let me know if that helped

**Comment by derkweijers** [comment]
That works

**Comment by wojtek-krysiak** [comment]
perfect - happy coding!

**Comment by ahmadnakouzi** [comment]
I have tried to disable both the bodyParser and  formidableMiddleware and it doesn't work for me.
Still can't log in and login page still loading.

***Code Goes Here***
const ADMIN = {
    email: 'test@test.me',
    password: 'testtest'
};
const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
    authenticate: async (email, password) => {
        if (ADMIN.password === password && ADMIN.email === email) {
            return ADMIN
        }
        return null
    },
    cookieName: 'adminBro',
    cookiePassword: 'testtest'
});
module.exports = router;

**Comment by ahmadnakouzi** [comment]
I have removed both bodyparser and formidableMiddleware and still doesn't work for me.
Login page opens normally but still loading once login button pressed.

***My Code Goes Here***
const ADMIN = {
    email: 'test@imaginelabs.me',
    password: 'testtest'
};

const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
    authenticate: async (email, password) => {
        if (ADMIN.password === password && ADMIN.email === email) {
            return ADMIN
        }
        return null
    },
    cookieName: 'adminBro',
    cookiePassword: 'testtest'
});
module.exports = router;

**Comment by ahmadnakouzi** [comment]
I have removed both bodyparser and formidableMiddleware and still doesn't work for me.
Login page opens normally but still loading once login button pressed.

***My Code Goes Here***
const ADMIN = {
email: 'test@imaginelabs.me',
password: 'testtest'
};

const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
authenticate: async (email, password) => {
if (ADMIN.password === password && ADMIN.email === email) {
return ADMIN
}
return null
},
cookieName: 'adminBro',
cookiePassword: 'testtest'
});
module.exports = router;
