### ISSUE TITLE
Mongoose Array field with enum elements are not shown in new/edit dropdown menu?

### ISSUE THREAD

**Issue by djbange** [SoftwareBrothers/admin-bro#253]
![image](https://user-images.githubusercontent.com/27759915/71668973-1d1a6b80-2d91-11ea-9e9d-a222663d8d0c.png)

It doesn't show drop down menu for an array type. Is there any option that I'm missing?

**Comment by wojtek-krysiak** [comment]
can you paste your schema?

in the meanwhile, you can try to force enums by adding `availableValues` to property options

```
resource: Resource,
options: {
  identifiers: {
    availableValues: [{name: 'xxx', value: 'zzz'}, ...]
  }
}

**Comment by djbange** [comment]
Thank you.
Here is the schema :
var roleSchema = new Schema({
    ...
    identifiers : {type : [String], enum : permissionArray, required : true},
})
Also does admin bro supports new temporary collection from multiple collections?

**Comment by djbange** [comment]
@wojtek-krysiak  Thanks for the help. I added `availableValues: [{label: 'xxx', value: 'zzz'}, ...]` and values are displaying  in the drop down menu. 
Now I'm having issue with array of objects. Values are not displayed in a object only keys are displayed as shown in the image.
![image](https://user-images.githubusercontent.com/27759915/71722133-e2c2d400-2e4d-11ea-9e78-115b98a7c9a7.png)
Schema for this field is : 
```
tiers :[{
                "starting_unit" : Number,
                "ending_unit" : Number,
                "price" : Number
 }]
```

**Comment by wojtek-krysiak** [comment]
which version `admin-bro` and `admin-bro-mongoose` do you use? asking because we had an error (fixed already) when "0" has been presented as an empty value.

**Comment by djbange** [comment]
package and it's versions :-1: 
```
"admin-bro": "^1.5.2",
"admin-bro-expressjs": "^0.4.0",
"admin-bro-mongoose": "^0.3.1",
```

**Comment by wojtek-krysiak** [comment]
please upgrade to the latest and let me know if that helped:
```
"admin-bro": "1.6.0",
"admin-bro-expressjs": "^0.4.0",
"admin-bro-mongoose": "^v0.4.0", (why I added this `v` to the version???? - will change that in the next release btw)
```

**Comment by djbange** [comment]
Yeah, It worked Thanks for the help :+1:

**Comment by djbange** [comment]
@wojtek-krysiak  While saving Array of objects, values are returns in the following format 
```
tiers.0.ending_unit:"15"
tiers.0.price:"1111"
tiers.0.starting_unit:"1"
tiers.1.ending_unit:"1000"
tiers.1.price:"2222"
tiers.1.starting_unit:"16"
```
Is this expected format?

**Comment by wojtek-krysiak** [comment]
yes. you can use unflatten to merge them back:

```
import { unflatten } from 'flat'

 const tiersObject = unflatten(tiers)
```

**Comment by djbange** [comment]
Thanks :+1:
