### ISSUE TITLE
before edit hook called twice (when opening edit page and when submitting)

### ISSUE THREAD

**Issue by haythamlabrini** [SoftwareBrothers/admin-bro#257]
Hi! 

I am working with addresses, and I am geolocating them in the backend.
This is expensive, hence I d like to only run it if there was a change in the address key.

Right now, it seems the hook is running when I open the `edit page` and when I `submit the change`.

Is there a reason for this behaviour?

I should be able to bypass this, but still thinking it might be better to not call that hook twice.

**Comment by wojtek-krysiak** [comment]
One hook to rule them all :) - both `post` and `get`. 

before hook takes [request](https://softwarebrothers.github.io/admin-bro-dev/Action.html#ActionRequest) as the parameter. Simply use that to verify if it is a 'post' or 'get' request.
