### ISSUE TITLE
propertyInEdit and array of references

### ISSUE THREAD

**Issue by haythamlabrini** [SoftwareBrothers/admin-bro#260]
Hello!
Thanks again for AdminBro!

I got 2 resources, `place` and `category`, and
```
IPlace {
  categories: ICategory[]
}
```

I am writing a component to edit categories.
The categories are available when using the common component but they are not available when using the custom component.

Any suggestion on how to grab them?

Thanks in advance!

**Comment by haythamlabrini** [comment]
I used this in the end, I am however not sure if this is the approach you would advise.

```
useEffect(() => {
    const fetchData = async () => {
      const result = await api.searchRecords({resourceId: "Category", query:""})
      console.log({result})
    };
    fetchData();
  }, []);
```

**Comment by wojtek-krysiak** [comment]
Hi, we populate all the relations in BaseRecord instance and put them into a "populated" property: https://softwarebrothers.github.io/admin-bro-dev/RecordJSON.html#populated

This is how to get them:

```
const MyComponent = (props) => {
  const { record } = props
  
  // assuming your relation is 'categories'
  const populatedCategories = record.populated['categories']
  
  return (...)
}

To see all the data in `record` you can open the chrome terminal on the "network" tab and see what is returned from the API.

Alternatively you can fetch them with a [resourceAction](https://softwarebrothers.github.io/admin-bro-dev/ApiClient.html#resourceAction) like this:

```
// params are query params which you can see in the URL of your browser
// when visit categories in the AdminBro and filter them by place.
const params = 'filters.place=YOUR_PLACE_ID'
await api.searchRecords({resourceId: "ICategory", actionName:"list", query})
```

**Comment by kiminohero** [comment]
@haythamlabrini How do you filter them then? What is the query that you pass? I am try it somewhat like `<name of the property>=${<the value i want to equate it with>}` in the query field but it returns no results

**Comment by iamraffe** [comment]
@kiminohero did you end up figuring out how to filter them? I also get an empty array no matter what I do

**Comment by kiminohero** [comment]
@iamraffe  I passed the query as an empty string and ran a filter function to get whatever required from the results. I am not sure what version you are using current but I am using adminbro version 1.6.6. I hope this helps you in some way. I am sorry if it didn't.
