### ISSUE TITLE
[Feature] Nextjs Support

### ISSUE THREAD

**Issue by Gr8z** [SoftwareBrothers/admin-bro#261]
Hi there,

You guys have an amazing tool out here, are there any plans to create a plugin that integrates nicely with projects using **NextJS** pages API without express?

**Comment by wojtek-krysiak** [comment]
Hmm - I've just checked out the next.js docs and don't see a way to do this easier than by using express inside the next.js.

So this is how I would integrate admin with next.js:

1. On the next page there is a link to an example expressjs integration: https://github.com/zeit/next.js/tree/canary/examples/custom-server-express

2. Check out this file in particular: https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/server.js

so I would remove lines 11-23 and change them to the regular admin-bro-express setup. Finally, I would leave out

```
server.all('*', (req, res) => {
    return handle(req, res)
})
```

(so all other routes will be handled by next.js). And this should work :)

Please let me know if you managed to do this integration.

**Comment by Gr8z** [comment]
That is actually a great solution, thank you.

**Comment by dhwaj1902** [comment]
Have anyone managed to integrate adminjs with nextjs?
Please share the reference code.
