### ISSUE TITLE
Extract the admin panel as Express + React project

### ISSUE THREAD

**Issue by lp-bayramali** [SoftwareBrothers/admin-bro#268]
Do we have a way to get the admin project extracted as React and Express.js + TypeORM project? It would be cool to edit freely admin project. At least for React side

**Comment by wojtek-krysiak** [comment]
We don't have such setup already prepared but in a couple of days, we will update our [boilerplate project](https://github.com/SoftwareBrothers/nest-typeorm-boilerplate) to use the latest admin-bro version.
