### ISSUE TITLE
Filtering returns no results even when records with queried data exist

### ISSUE THREAD

**Issue by areksb** [SoftwareBrothers/admin-bro#270]
Some of the filters response with false results - they don't reflect the actual data. For example: filtering the "is favourite: no" does not show any results, when they actually exist

![admin-filters-1](https://user-images.githubusercontent.com/38556503/72418500-3ea92900-377b-11ea-9f75-0ab0f38870eb.png)
![admin-filters-2](https://user-images.githubusercontent.com/38556503/72418498-3ea92900-377b-11ea-91df-5501d32fe601.png)

I've also encountered timeouts and responses with no filtered results

**Comment by wojtek-krysiak** [comment]
fixed in 2.0
