### ISSUE TITLE
Unable to make custom dropdown menu

### ISSUE THREAD

**Issue by kiminohero** [SoftwareBrothers/admin-bro#271]
I want to add a dropdownMenu like this in the edit view of a resource. But it only shows a input field instead.
![Screenshot from 2020-01-16 17-22-36](https://user-images.githubusercontent.com/41645361/72523083-08f06700-3885-11ea-9ea4-f9b651edcaf5.png)

**Comment by saurshaz** [comment]
@kiminohero Could u help me with, how u did this 
?

**Comment by prabhasprd** [comment]
properties: {
        Current_status: {
          availableValues: [
            { value: 'active', label: 'active' },
            { value: 'de-active', label: 'de-active' },
            { value: 'pending', label: 'pending' },
            { value: 'reject', label: 'reject' },
          ],
        }
      },
