### ISSUE TITLE
Error 403 on assets when rootPath is "/"

### ISSUE THREAD

**Issue by Valdomar** [SoftwareBrothers/admin-bro#272]
Hello,

So I have a problem with AdminBro, everything is working perfectly but If I try to set rootPath to "/", It loads but without any assets (no css, no js). He is trying to making every request without the domain name like "http://frontend/assets/icomoon.css"

Network tab of Chrome DevTools:
<img width="611" alt="403" src="https://user-images.githubusercontent.com/39741566/72592701-6925ee00-3903-11ea-9561-1313361fd80c.png">

Tried on localhost, tried on production = same result.
Tried in a new project with only express & adminbro = same result.

Here is a snippet to reproduce the error (the same as the one in Get Started page)

```javascript
const AdminBro = require('admin-bro')
const AdminBroExpress = require('admin-bro-expressjs')

const express = require('express')
const app = express()

const adminBro = new AdminBro({
  databases: [],
  rootPath: '/',
})

const router = AdminBroExpress.buildRouter(adminBro)

app.use(adminBro.options.rootPath, router)
app.listen(8080, () => console.log('AdminBro is under localhost:8080/admin'))
```

package.json

```json
{
    "admin-bro": "^1.6.0",
    "admin-bro-expressjs": "^0.4.0",
}
```

Thanks

**Comment by Valdomar** [comment]
No update ?

**Comment by wojtek-krysiak** [comment]
sorry, we are occupied by a version 2.0. which should be released next week. After that I will take a look at your issue.
