### ISSUE TITLE
searchRecords() produces malformed URLs because resourceID is not a string

### ISSUE THREAD

**Issue by illarionvk** [SoftwareBrothers/admin-bro#273]
The admin panel can not display related entities (references) because the AdminBro frontend is sending requests to the backend using invalid URLs:

```
/api/resources/[object Object]/search/
```

It happens because the `searchRecords()` function expects the `resourceID` variable to be a string, but receives an object instead. Please take a look at the attached screenshots.

![malformed-request-url-because-resourceId-is-object](https://user-images.githubusercontent.com/5012724/72629782-47535800-3951-11ea-8d26-54899165842e.png)

![reference-property-actual](https://user-images.githubusercontent.com/5012724/72629811-56d2a100-3951-11ea-90b7-e74e74e846f0.png)

![reference-property-declared](https://user-images.githubusercontent.com/5012724/72629821-5afebe80-3951-11ea-8325-1faf9e1eccbf.png)

**Comment by wojtek-krysiak** [comment]
@illarionvk 

1. which database adapter do you use (mongoose || sequelize || typeorm)? 
2. is it still occurring in the latest version?
3. do you have some snippet (db schema and admin config) you can share?

**Comment by wojtek-krysiak** [comment]
closing this one due to the lack of info.
