### ISSUE TITLE
Authentication Problem: Unable to login

### ISSUE THREAD

**Issue by naseebbajracharya** [SoftwareBrothers/admin-bro#275]
Even after following the documentation I'm not able to log in. After providing Email and Password in the Admin Login Form, it takes lots of time and throws an error in console.

Error: Request aborted
at IncomingMessage.<anonymous>..
at...
at..
at..
at..

**Comment by wojtek-krysiak** [comment]
if you use express plugin please turn off all other middlewares and let me know if that helped.

if not, please paste your config and write your admin-bro and admin-bro-express version

**Comment by naseebbajracharya** [comment]
yeah, it worked after removing body-parser middleware.

**Comment by wojtek-krysiak** [comment]
I think it is related to #252 - try to put body parser after the adminbro setup

**Comment by naseebbajracharya** [comment]
yeah thanks, it works perfectly now 👍
