### ISSUE TITLE
Wrap search action within resourceAction - the same as list action.

### ISSUE THREAD

**Issue by jxnata** [SoftwareBrothers/admin-bro#279]
Original Request:

I need to customize the **search** action to only return results from the logged user.
I have already done this with the **list** action, however, when registering or editing products, for example, suppliers registered by other users appear in the dropdown.

**list** action:

![Captura de Tela 2020-01-23 às 12 58 04](https://user-images.githubusercontent.com/22618276/73000759-215e0580-3de0-11ea-8c05-73462182e32e.png)

Acceptance criteria:
* add new search action to the ResourceOptions[actions]
* change frontend that it hits resourceAction(actionName: 'search'...) instaed of old search
* remove old routes from Router
* remove obsolete calls from ApiClient and ViewHelpers (if there are any)
* ensure that search action can have before and after hook
* handle is visible and is accessible set to false.

**Comment by wojtek-krysiak** [comment]
not possible right now :(. i added this to the todo in v2.0.0 (releasing probably next week)

**Comment by wojtek-krysiak** [comment]
and as usual, there is a delay in a release - just letting you know that I haven't forgotten about it and it will be in v2.

**Comment by jxnata** [comment]
@wojtek-krysiak Ok, thank you very much, I'm waiting!

**Comment by jxnata** [comment]
Any news about that?

**Comment by jxnata** [comment]
@wojtek-krysiak Any news about that?

**Comment by wojtek-krysiak** [comment]
nope - sorry. Now I am revising a backlog and let you know guys when we will do this

**Comment by wojtek-krysiak** [comment]
published in v2.3.0-beta.1

**Comment by aastroem** [comment]
@jxnata I'm looking to solve the exact same problem, did you get this working ?

**Comment by wojtek-krysiak** [comment]
In the latest version you can modify search [action](https://adminbro.com/Action.html) the same as you can do it with `list` action.

**Comment by nickharder88** [comment]
From what I see, you can actually only filter with the name property, not the same way you can generically filter with the list action. This make's it hard because, per his use case (and mine), I don't frequently have a reference as the name of my resource.
