### ISSUE TITLE
Typescript usage problem

### ISSUE THREAD

**Issue by aminktb** [SoftwareBrothers/admin-bro#281]
Thanks for your nice admin solution. I have used admin-bro in express.js before and it worked nicely, but recently I tried to use it in an express.js project with typescript and it gets the following error while compiling:

`node_modules/admin-bro/types/src/frontend/components/app/filter.d.ts:2:37 - error TS7016: Could not find a declaration file for module 'react-router'. '/home/amin/tatami-projects/dadehbazi-backend/node_modules/react-router/index.js' implicitly has an 'any' type. 
Try npm install @types/react-router if it exists or add a new declaration (.d.ts) file containing declare module 'react-router'; 
2 import { RouteComponentProps } from 'react-router';`

Suggestion: including @types/... in "dependencies", not "devDependencies", might solve the problem for typescript projects using admin-bro

**Comment by wojtek-krysiak** [comment]
Hi, 

I don't want to add types to dependencies because not everyone is using TypeScript.
In our TypeScript projects, we simply add these types by installing them in the apps which uses admin-bro.

**Comment by ex3ndr** [comment]
This causes huge issues for us: Multiple conflicts of types, have to edit yarn.lock manually and looking at admin-bro lock file to try to match types.

Many libraries nowadays include typings in it and it works well.
