### ISSUE TITLE
Enhancement: add `Resource` without displaying it in the side bar

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#285]
Sometimes it's necessary to have the resource, but do not display it in the side bar. E.g. users can have accounts, and you just display accounts for selected user, but don't want to display all accounts table.

**Comment by Co0sh** [comment]
Do you mean hiding a resource completely or displaying only some records of the resource?

In the first case you can already do this. When configuring resources you can set `isVisible` option of "list" action to false, something along the lines of:

```js
new AdminBro({
  resources: [
    {
      resource: connection.model("User"),
      options: {
        actions: {
          list: { isVisible: false }
        }
      }
    }
  ]
});
```

**Comment by dmitryLagoda** [comment]
No, I meant just do not add the resource to Side Bar panel, but still will be able to open resource table from the url. Like we would have a value for `Resource Parent` option -> Hidden.
`parent: {name: "Users", icon: "fas fa-users"}`

**Comment by wojtek-krysiak** [comment]
You can specify in isVisible a function like that:

```
new AdminBro({
  resources: [
    {
      resource: connection.model("User"),
      options: {
        actions: {
          list: { isVisible: (context) => context.currentUser && context.currentUser.email === YOU }
        }
      }
    }
  ]
});
```

so no one will see the table except you.
Regarding `hidden` option - we won't implement this because combo isAccessible + isVisible is too complicated alrady
