### ISSUE TITLE
Multiple database with same tablename, every resource page is the same

### ISSUE THREAD

**Issue by stelone** [SoftwareBrothers/admin-bro#286]
When you have multiple database, with same tablename, the ressource page is the same for every database. 
The resource don't group well too. For User I have made a custom resource. 

![image](https://user-images.githubusercontent.com/8436858/73949503-c73e6380-48fa-11ea-909c-ce2a24a2b104.png)

How can I help fixe this ?
version: 1.6.6
database: mssql
database-driver: sequelize / tedious

**Comment by wojtek-krysiak** [comment]
Hi - thanks for using our tool. When we designed this I knew that this would be the issue at some point :).

Right now I solved this in version 2.0.0-beta.15 by adding an option to change the Id of a resource in [resource options](file:///Users/wojciechkrysiak/Documents/projekty/admin-bro-dev/docs/v2/ResourceOptions.html#id) - this is the link to v2 documentation.

so you can set id for one resource 'users1' and for the second 'users2'

**Comment by BrunoYottabyte** [comment]
How can I list all my banks from my multitenancy software?
