### ISSUE TITLE
Primary Key not 'id'

### ISSUE THREAD

**Issue by genp** [SoftwareBrothers/admin-bro#287]
I have a table where the pk is not called `id`. If I want to edit properties of records in this table, there is an error where the generated sql tries to index by a pk called `id` instead of what the pk actually is (here `user_id`). What can I do to change what pk AdminBro is using for a particular table?

Error:
```
STATEMENT:  SELECT "user_id", "username", "first_name", "last_name", "created_at", "updated_at" FROM "user_profile" AS "UserProfile" WHERE "UserProfile"."id" IN (<uuid>);
{ SequelizeDatabaseError: column UserProfile.id does not exist
...
```
This is failing because the WHERE clause should be `WHERE "UserProfile"."user_id" IN (<uuid>);`
The sequelize model for `UserProfile` specifies `user_id` as the pk:

```
const UserProfile = Model.define(
  'UserProfile',
  {
    user_id: {
      type: DataType.UUID,
      primaryKey: true
    },
...
```

**Comment by wojtek-krysiak** [comment]
Hi - first of all, thanks for trying out AdminBro.

Fields different than "id" as Primary Keys weren't supported until today morning :) - So please upgrade your admin-bro-sequelizejs adapter to v0.3.2.
But also you will have to add `autoIncrement: true` to user_id in your Model.define function. Otherwise, it won't work.

**Comment by genp** [comment]
High-five Bros! Thank you! I'll update asap.

**Comment by genp** [comment]
I'm sorry but this issue should be re-opened. I updated my dependency and tried again, but not all actions work on records that don't have an `id` field. Example: I tried to delete from the UserProfile table used in the first example and have this error:

```
Executing (default): DELETE FROM "user_profile" WHERE "id" = <uuid>
<timestamp>: DatabaseError [SequelizeDatabaseError]: column "id" does not exist
```

**Comment by wojtek-krysiak** [comment]
sure. i will retest today and post an update

**Comment by wojtek-krysiak** [comment]
please try out `v0.3.3` of sequelizejs adapter and let me know if that helped. (Not closing the issue until that)

**Comment by genp** [comment]
Yes delete is working on that table now! Thanks!

**Comment by wojtek-krysiak** [comment]
np, glad I could help.
