### ISSUE TITLE
Redirect to the custom page after saving a new record is not working

### ISSUE THREAD

**Issue by djbange** [SoftwareBrothers/admin-bro#289]
I have specified redirect url like `redirectUrl: "/admin/customPage"` in the new action handler response. However It's not redirecting to given path. Just replaces url in the browser.

**Comment by wojtek-krysiak** [comment]
probably becasue there is no route `/admin/customPage` - you probably ment `/admin/pages/customPage`. You can use [ViewHelper#pageUrl](https://softwarebrothers.github.io/admin-bro-dev/ViewHelpers.html#pageUrl) to generate urls automaticaly.
