### ISSUE TITLE
Uncaught TypeError: styled.img is not a function

### ISSUE THREAD

**Issue by SantiagoAndre** [SoftwareBrothers/admin-bro#292]
In the version  1.3.5 my code works.
In the new version I get this error in the jsx files
file.jsx:46 Uncaught TypeError: styled.img is not a function
file.jsx:46 Uncaught TypeError: styled.div is not a function

thanks.

**Comment by wojtek-krysiak** [comment]
what is under file.jsx:46?

**Comment by SantiagoAndre** [comment]
Dashboard.jsx

**Comment by SantiagoAndre** [comment]
https://gitlab.com/santiagandre/yupay-app/-/tree/master/src/admin/components
i have a some custom components, in FileInputPreview on line 47 mark that error.
![image](https://user-images.githubusercontent.com/29509374/74294143-07428380-4d0b-11ea-8189-7cb86ce819a3.png)

**Comment by wojtek-krysiak** [comment]
please try add on the top:

```
import styled from 'styled-components';
```

and let me know if that helped

**Comment by SantiagoAndre** [comment]
I added it and it didn't work but I realized that I was using version 1.3, I changed it to 1.4 and it already worked, thank you very much
