### ISSUE TITLE
change path of DropArea

### ISSUE THREAD

**Issue by lavanphat** [SoftwareBrothers/admin-bro#297]
![image](https://user-images.githubusercontent.com/45566810/74439459-d8f5ad00-4e9e-11ea-8587-98a92b02f6e1.png)
I want to change the file storage path when uploading files. What should I do?

**Comment by wojtek-krysiak** [comment]
you cannot do this via options. The only way would be to fork admin-bro-expressjs and put special options to formidableMiddleware (change this line: https://github.com/SoftwareBrothers/admin-bro-expressjs/blob/master/plugin.js#L143) like: uploadDir
