### ISSUE TITLE
Use another authentication 

### ISSUE THREAD

**Issue by stelone** [SoftwareBrothers/admin-bro#298]
Hello, 

In my app, we already implemented authentication with an identity provider.
We want to use this identity in AdminBro to filter access to resources. 

In the example, I understand that login page is implemented in AdminBro, but we already have in authentication with identity provider.  

How can we implement use our implementation of authentication to have the identity of the user ? 

And thanks for this wonderfull framework :)

**Comment by wojtek-krysiak** [comment]
I guess you are using admin-bro-expressjs to render AdminBro. If that is the case you can use buildRouter function and pass there a preconfigured router (predefinedRouter).
In this predefinedRouter router, you can create any authentication logic you want.

Take a look at how `buildAuthenticatedRouter` is build: https://github.com/SoftwareBrothers/admin-bro-expressjs/blob/master/plugin.js#L132 I think that instead `AdminBro.renderLogin` you will need to use your login page, and simple handle POST method to login the user, and store the user object in `req.session`, so you can use it in AdminBro actions.
