### ISSUE TITLE
Filtering resources inside a complicated mongoose model

### ISSUE THREAD

**Issue by MariaRoblesSpin** [SoftwareBrothers/admin-bro#300]
It is possible to filter resources?
I have one model called "Uploads". 
It will be some kind of repo to storage pdfs, images and videos.  
Inside another model called "Page" I want to show one image of my repo previously created.
I need to link the "page model" with the "uploads model" (like in the complicated example of the live demo) but filtered by mimeType or extension. 
I can't find the way to do this.
It is possible to do it?
Any suggestion?

**Comment by wojtek-krysiak** [comment]
It is one to many relationship (so one Page has many uploads). We will implement this in an easy way in #282 . Right now the only way of doing this is to

1. create an After hook for show action in Page resource
2. in this After hook fetch all the uploads you need (you can use raw mongoose or sequelize models)
3. then you have to add this fetched uploads to the response.record.populated:

```
after: async (originalResponse, request, context) => {
  const uploads = await Upload.fnd({pageId: context.record.id(), mimeType: ....})

  // you can modify this that it doesn't mutate the originalResponse
  originalResponse.record.populated.uploads = uploads.map(u => u.toJSON())

  return response
}
```

4. Finally you have to create custom property like "uplaods" in Page resource.

```
properties: {
  uploads: {
    comopnents: {
      show: AdminBro.bundle('./show.uploads.component.tsx')
    }
  }
}
```

```
// ./show.uploads.component.tsx

```
import React from 'react'

const ShowUploads = (record) => {
  const { uploads } = record.populated

  // or render <img> or something of some use :)
  render JSON.stringify(uploads)
}

```
