### ISSUE TITLE
Custom components using styled-components do not load

### ISSUE THREAD

**Issue by Co0sh** [SoftwareBrothers/admin-bro#302]
When using `styled-components` package to style custom components the transpilation process outputs code that calls `hasOwnProperty` method on the `styled` object and crashes the component because it's `undefined`.

It's called in `components.bundle.js` file in the place that is the import statement in the original code. The issue only appears when compiling the project using `tsc` and then running the output with Node. It's working fine when using `ts-node` to run the code.

I've checked the Rollup and Babel configurations that are used inside admin-bro and it seems both are exactly the same, regardless of whether `tsc` or `ts-node` is used.

**Comment by wojtek-krysiak** [comment]
it was problem with paths to components after the build
