### ISSUE TITLE
hide checkbox in the TableHeader when all records doesn't have bulkaActions (right now it stays there)

### ISSUE THREAD

**Issue by dmitryLagoda** [SoftwareBrothers/admin-bro#313]
Add ability to hide Delete Bulk Action and Checkboxes column for Resource

**Comment by wojtek-krysiak** [comment]
just set [isAccessible](https://softwarebrothers.github.io/admin-bro-dev/Action.html#isAccessible) for that method (bulkDelete) that it returns false

**Comment by dmitryLagoda** [comment]
Thanks, Wojciech! Is there the way also to remove the checkbox in the Resource table header? Which is supposed to select all records, if bulkAction is enabled. Currently after disabling bulkAction there is the checkbox in the header, it does nothing, but it exists.

**Comment by wojtek-krysiak** [comment]
it is a bug - reopening the issue

**Comment by wojtek-krysiak** [comment]
fixed in version 2.0.0-beta.31 (will be released in a couple of minutes)

**Comment by carmof** [comment]
I'm having the same issue with version "adminjs": "^7.8.13"
