### ISSUE TITLE
better handle expressjs errors by adding .next when error occures

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/admin-bro#316]

**Comment by mjlawrence83** [comment]
I would really benefit from this feature. At the moment I'm using Express + Sequelize, and the database password is rotated every 90 days. I want to be able to update the password adminbro is using programatically, but at the moment I've no easy way of intercepting the error. I can see `SequelizeAccessDeniedError:` being thrown in the console log, but that's about it.

**Comment by wojtek-krysiak** [comment]
fixed
