### ISSUE TITLE
Rest - Postcode page

### ISSUE THREAD

**Issue by chyupatwo** [SoftwareBrothers/admin-bro#33]
clicking on page 6 will render the pagination in a wierd way

![screenshot from 2018-12-11 12-44-42](https://user-images.githubusercontent.com/36953988/49795407-94263180-fd42-11e8-9e46-1bc754824c18.png)

**Comment by wojtek-krysiak** [comment]
Thanks - it was fixed yesterdays with the release v0.2.3
