### ISSUE TITLE
Deploy app on serverless (gcloud or aws)

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/admin-bro#330]

**Comment by JonaszJestem** [comment]
Does it mean that there will be a centralized Admin Bro API for all projects?

**Comment by wojtek-krysiak** [comment]
no - it is just a deployment of admin-bro to cloud functions. I am on it - and solved that with new admin-bro-firebase adapter.

**Comment by wojtek-krysiak** [comment]
we implemented admin-bro-firebase-functions plugin
