### ISSUE TITLE
Add translation to "Add new item" and "Yes/No"

### ISSUE THREAD

**Issue by jxnata** [SoftwareBrothers/admin-bro#333]
Please add the possibility to translate the text of the "Add new item" button and the text "Yes / No" (when the resource property is of the boolean type)

**Comment by wojtek-krysiak** [comment]
in https://github.com/SoftwareBrothers/admin-bro/releases/tag/v2.2.9 I partially fixed this issue - I added Yes/No to translations.

('Add New Item' left)

**Comment by wojtek-krysiak** [comment]
closed in  https://github.com/SoftwareBrothers/admin-bro/releases/tag/v2.2.10
