### ISSUE TITLE
Avatar should be changable

### ISSUE THREAD

**Issue by genp** [SoftwareBrothers/admin-bro#338]
In the `LoggedUser` component, the `email` is a prop but the displayed avatar image is hard coded:
```
<img src="https://api.adorable.io/avatars/24/softwarebrothers.png" alt="avatar" />
```

Can you update the image src to come from a prop as well?

**Comment by genp** [comment]
This may be a duplicate of #329

**Comment by wojtek-krysiak** [comment]
yep it is duplicate of #329 - will be closed soon.
