### ISSUE TITLE
Component Export in v2 breaking from v1

### ISSUE THREAD

**Issue by genp** [SoftwareBrothers/admin-bro#339]
I just upgraded to v2 (yay!) but some components that worked for me in v1 are now not importing correctly. 

For example, my dashboard is based on the dashboard from the v1 tutorial and exports like this in `component/dashboard.jsx`:
```
export default class Dashboard extends React.Component {
  constructor(props) {
...
```

My `AdminBroOptions` specifies the dashboard component using:
```
component: AdminBro.bundle('./components/dashboard')
```
(also from the v1 docs)

But I am getting this error in the web console: 
```
Javascript Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Dashboard`.
```

How should I procede?

**Comment by wojtek-krysiak** [comment]
we are in the process of writing the migration guide. Most (almost all) of frontend components were rewritten so if you used WrapperBox or something like that - it won't work.  

Most probably you have errors in node terminal saying that some components don't exist anymore.

You can write your own dashboard like this:

```
import React from 'react'
import {Box} from 'admi-bro'

const Dashboard = () => {
  return (
    <Box>My Dashboard Goes here</Box>
  )
}
```

and gradually fill <Box> with the content of your old dashboard and see what is working and what doesn't

Here is the example of the default dashboard:https://github.com/SoftwareBrothers/admin-bro/blob/v2.0/src/frontend/components/app/default-dashboard.tsx

You can use all the components from design system by simply importing them like this:

```
import { Box, H2, H5, H4, Text, Illustration, IllustrationProps, Button } from 'admin-bro'
```

PS: We have a couple of new cool components like: [Illustration](https://softwarebrothers.github.io/admin-bro-dev/v2/Illustration.html) or hooks like: https://softwarebrothers.github.io/admin-bro-dev/v2/useRecord.html

**Comment by wojtek-krysiak** [comment]
closing :)
