### ISSUE TITLE
Theme not settable in v2

### ISSUE THREAD

**Issue by genp** [SoftwareBrothers/admin-bro#340]
I recently switched from v1 to v2 and the css I had set in the `theme` property of the `branding` in my `AdminBroOptions` stopped applying. My theme is: 

```    
theme: {
      colors: {
        bck: '#000',
        defaultText: '#FFF',
        lightText: '#999',
        border: '#555',
        borderOnDark: '#2E324A',
        innerBck: '#000',
        darkBck: '#444',
        lightBck: '#666',
        superLightBack: '#999',
        inputBck: '#000',
        lightSuccess: '#008340',
        lightError: '#660040'
      }
    }
```

which appears as a mostly black theme in v1, under v2 I get the default white theme.

**Comment by wojtek-krysiak** [comment]
we rewrote entire UI to our own design system and along with that we also changed all theme variables. Check out the docs for theme in v2: https://softwarebrothers.github.io/admin-bro-dev/v2/Theme.html
