### ISSUE TITLE
Admin Bro default list ordering 

### ISSUE THREAD

**Issue by JonaszJestem** [SoftwareBrothers/admin-bro#341]
By default AdminBro sorts lists by first property name. That breaks the Firebase adapter.
For example, we have a record `{id: '1'}`
Admin Bro requests ordering by `name` as it is a first property defined. Firestore does not return that record as the property `name` is not defined in it. 

Proposition: change in `sort-setter.ts`
```typescript
  const params = {
    direction: computedDirection === 'asc' ? 'asc' : 'desc' as 'asc' | 'desc',
    sortBy: sortBy || options.sortBy // || firstPropertyName , <- that's probably not needed as sortBy is optional property
  }
```

**Comment by wojtek-krysiak** [comment]
@JonaszJestem I think that this should be handled on the adapter end - I would perform 2 calls:
* one with the regular sort
* second where the sorted property is set to undefined
So the user will always see the same number of records regarding sorting.

If we unset sortBy in first call data will be presented in totally random order in all other adapters.

Let's discuss this maybe tomorrow :)
