### ISSUE TITLE
handling null

### ISSUE THREAD

**Issue by sureshvarman** [SoftwareBrothers/admin-bro#342]
https://github.com/SoftwareBrothers/admin-bro/blob/b39ce5beb64ee69d5745c71ef7d5f783e6df3bec/src/frontend/components/actions/record-to-form-data.ts#L23

incase of NULL values from table will break this and stop submitting the form.

But i would like to keep them as null.

**Comment by mjlawrence83** [comment]
I've seen the #370 fix go in, but it changes all NULLs to be blank string.

I'm planning to have admin-bro working with an existing MSSQL DB via sequelize, and at the moment it will be changing pre-existing records replacing NULLs with `''`. I can't afford to allow data changing unexpectedly. Is there a plan to have it handle NULLs or will it continue as its currently implemented?

**Comment by wojtek-krysiak** [comment]
hmm - atm I don't have a fix in admin-bro core for that. We are sending all the data from the frontend to the backend as a FormData. So it requires to have all the values as strings or File objects.

To fix your particular problem I would strip the request in before hook of edit action. Like this:

```
before: (request) => {
  if (request.method === 'post') {
    const { canBeNullProperty1, canBeNullProperty2, ...rest } = request.payload
   
    return {
      canBeNullProperty1: canBeNullProperty1 === '' ? null : canBeNullProperty1,
      ...rest
    }
  }
  return request
}
```

This is an example - probably in your case you can build more elegant code but you get the point.
