### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by farmgameowner** [SoftwareBrothers/admin-bro#343]
Hey guys! 
const adminBro = new AdminBro({
  locale: {
	buttons: {
		filter: '<new_filter_button_name>'
	}
  },
Does not work. Why?

Also when install 2.0.0-beta.32 or 21 error  AdminBro.renderLogin

**Comment by wojtek-krysiak** [comment]
you missed translations :) 

```
locale: {
  translations: {
    buttons: ....
  }
}
```

**Comment by wojtek-krysiak** [comment]
regarding error in .32 - you have to upgrade admin-bro-expressjs / hapijs to latest beta versions as well.

**Comment by farmgameowner** [comment]
thank you)
