### ISSUE TITLE
prepare example store backend app

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/admin-bro#350]
Right now there is an example app: https://admin-bro-example-app.herokuapp.com/admin which shows default admin features. Since we use AdminBro in a couple of web stores it will be good to have an example backend showing all the possibilities of AdminBro for E-Commerce use-case.

working name: _**Bromence**_ (AdminBro for E-Commerce)

Acceptance criteria: 

in general: build admin panel for e-commerce page
* database should have:
** products
** variants
** nested categories (n to n)
** orders with order items
** photos
** users
* in the AdminBro UI there should be a
** dedicated page for adding product and variants (ideally on one page)
** dedicated page for managing orders
* it will have to be deployed somewhere (heroku, firebase etc)

Next
* in a separate task we could add an example frontend to it.

**Comment by pawlakzn** [comment]
Can you explain it in more details. Could you give any example?

**Comment by wojtek-krysiak** [comment]
@pawlakzn I update the description - long story short it is about Bromance example

**Comment by Swarag-N** [comment]
can you share the source code of the heroku deployed website

**Comment by wojtek-krysiak** [comment]
https://github.com/SoftwareBrothers/admin-bro-example-app

**Comment by wojtek-krysiak** [comment]
WIP of the app is inside the repo (/app) - we will be constantly working on it so closing this task
