### ISSUE TITLE
NULL VALUE IN FORM DOESN'T UPDATE RECORDS

### ISSUE THREAD

**Issue by divyansheccentric** [SoftwareBrothers/admin-bro#351]
Hi, I am using admin-bro-mongoose, with admin-bro.

if I have one of the fields as null value in my form, on clicking save it just doesn't update the record and reloads the page @wojtek-krysiak

**Comment by wojtek-krysiak** [comment]
please take a look at what is returned from the backend (via chrome inspector - network tab). Maybe you have some validation errors.

Also maybe it is related to #304 ?

**Comment by divyansheccentric** [comment]
@wojtek-krysiak  yes u are right.

on Console it shows  `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

and on network tab, unless i fill all the fields it just doesnt send any request. So i guess it's to do with form. I am using version 2.0 of admin bro. Is there any fix for that? @wojtek-krysiak

**Comment by divyansheccentric** [comment]
Do we have a fix? Kindly someone reply me on this. That'll be a great help. 
Thanks.

**Comment by wojtek-krysiak** [comment]
Hi - there is a [before action hook](https://softwarebrothers.github.io/admin-bro-dev/Action.html#before) where you can strip or add any data to the payload to prebare `request` object before being handled by an actual action handler.

there you can remove any field from the request that they won't get to the handler. This is an example:

```
actions: {
  new: {
    before: async (request) => {
      if(request.payload.myNullableMethod === '') {
        const { myNullableMethod, ...rest } = request.payload
        request.payload = rest
      }
      return request
    },
  }
}
```

does this helps?

**Comment by divyansheccentric** [comment]
Well,I could use it to convert the null fields to empty " " string. But the point is that I want to keep the value as null only in db. Can I achieve that in some way ? through any kind of hook or something? It will help a lot @wojtek-krysiak  Thanks

**Comment by wojtek-krysiak** [comment]
does the example I provided not solve your problem? In the code snippet I extracted the "myNullableMethod" so AdminBro does not know of its existence - it shouldn't update it, so it was null it will be null.

**Comment by divyansheccentric** [comment]
No, Its still giving the same behaviour. 
Also I noticed few things.

1. I tried console logging request.payload on edit : before hook. I saw that it just returns an empty object there
2. It works fine, when I create a new record i.e It takes null values and creates the entry normally. Only when I try to edit an existing record. It causes the problem.
@wojtek-krysiak  hope this helps.
Thanks

**Comment by miqayel-manvelyan** [comment]
Hey, 

Here is the issue from Console:

http://prntscr.com/re6vio

http://prntscr.com/re6w1c

**Comment by wojtek-krysiak** [comment]
can you send me your schema - the part which causes the problem. I will try to recreate that and write you a solution

**Comment by miqayel-manvelyan** [comment]
Hey @wojtek-krysiak 
Thanks for your reply

```
module.exports = (sequelize, DataTypes) => {
    const Test = sequelize.define('Test', {
        name: {
            type: DataTypes.STRING
        },
        text: {
            type: DataTypes.STRING
        }
    }, {});

    Test.associate = (models) => {
    };

    return Test;
};
```

1. Create record
2. http://prntscr.com/re7cw5
3. Edit
4. http://prntscr.com/re7e5d

**Comment by miqayel-manvelyan** [comment]
@wojtek-krysiak 
I solved this problem like this:

```
module.exports = (sequelize, DataTypes) => {
    const Test = sequelize.define('Test', {
        name: {
            type: DataTypes.STRING,
            defaultValue: ''
        },
        text: {
            type: DataTypes.STRING,
            defaultValue: ''
        }
    }, {});

    Test.associate = (models) => {
    };

    return Test;
};
```

But it’s very inconvenient.


Thanks for your time

**Comment by divyansheccentric** [comment]
Yes @wojtek-krysiak we can resolve the issue like this but it wont work for the records that are already there in db when i try to edit them. it only works with new record created.  And i really wanna keep records as null instead of quoted string. Will there be any fix soon @wojtek-krysiak  thanks

**Comment by wojtek-krysiak** [comment]
working on it right now

**Comment by wojtek-krysiak** [comment]
I created the same schema you send and played with it.

This is the solution I came up with:

```
const nullifyEmptyProperties = (request) => {
  const { method, payload } = request
  if (method === 'post') {
    request.payload = Object
      .entries(payload)
      // this will remove keys with values "" from the payload
      .filter(([, value]) => value !== '')
      // this converts the entries array back to key: value object
      .reduce((memo, [key, value]) => ({
        ...memo,
        [key]: value,
      }), {})
  }
  return request
}

// in ResourceOptions:
actions: {
    edit: {
      before: nullifyEmptyProperties
    },
    new: {
      before: nullifyEmptyProperties
    }
  }
```

but this solution won't work in cases where you have your record in the database with some values and want to set them to "", because nullifyEmptyProperties will filter them out.

another way would be to change values from "" to null like that:

```
const nullifyEmptyProperties = (request) => {
  const { method, payload } = request
  if (method === 'post') {
    request.payload = Object
      .entries(payload)
      .reduce((memo, [key, value]) => ({
        ...memo,
        [key]: value === '' ? null : value,
      }), {})
  }
  return request
}
```

does it help?

**Comment by miqayel-manvelyan** [comment]
No :(
![Peek 2020-03-11 10-16](https://user-images.githubusercontent.com/34510969/76388129-cc6f5200-6381-11ea-9154-88335963eeb9.gif)

**Comment by divyansheccentric** [comment]
> No :(
> ![Peek 2020-03-11 10-16](https://user-images.githubusercontent.com/34510969/76388129-cc6f5200-6381-11ea-9154-88335963eeb9.gif)

Yes, I am also receiving the same error, when using the fix that you mentioned @wojtek-krysiak

**Comment by divyansheccentric** [comment]
Hey @wojtek-krysiak  hope you're doing great
 Any fix for this issue yet?

**Comment by wojtek-krysiak** [comment]
nop. Sorry... dug into other things: #coronavirus

**Comment by maurocen** [comment]
@divyansheccentric I had that issue and it was fixed with PR #370 .

**Comment by divyansheccentric** [comment]
Yes, I was able to fix the issue with that PR. But now I cant render any of my custom components
[https://pasteboard.co/J0MzV51.png](url)

This issue wasn't there before I upgraded. 
 
Are u facing any similar issue @maurocen 
@wojtek-krysiak

**Comment by maurocen** [comment]
Not having that problem, no. 

Do you have any output to share?

**Comment by divyansheccentric** [comment]
> Not having that problem, no.
> 
> Do you have any output to share?

Sorry, I am replying really late here, due to covid-19 we're facing strict lockdown across entire India.
Thanks for your concern, yes, so that's what I see when i try to render my custom component.
Even though, I have exported my component, still I cant see my custom component in version 2, In version 1 it works all fine. @maurocen  @wojtek-krysiak 

![Screenshot from 2020-04-04 19-58-11](https://user-images.githubusercontent.com/32994707/78453383-ec5b1280-76ae-11ea-8385-b6f2a7e6cec9.png)
