### ISSUE TITLE
Support for Sequelize Array

### ISSUE THREAD

**Issue by sarriaroman** [SoftwareBrothers/admin-bro#353]
Original description:
When I define a Sequelize.ARRAY(Sequelize.TEXT) the field is shown as a Text Field, is there any way to show it as an String Array like in the Mongoose interface?

Acceptance criteria:
* handle Arrays in sequelize adapter
* write unit tests which cover new feautre

**Comment by wojtek-krysiak** [comment]
it will have to be implemented in admin-bro-sequelizejs. Leaving this open - maybe someone will add this feature.

**Comment by sarriaroman** [comment]
Is there any kind of documentation on how the Adapter works? Probably I can make the implementation and share the PR.

**Comment by wojtek-krysiak** [comment]
There is a task to do the documentation here #306 (there is a brief description)

but regarding the array fields in sequelize: 

1. you have to implement isArray() method in [property.js](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/property.js) (like [mongoose implementation](https://github.com/SoftwareBrothers/admin-bro-mongoose/blob/master/src/property.js#L93)) - basically you can use admin-bro-mongoose as a reference
2. make sure that type() returns the type of nested objects (string for array of strings etc).
3. the same with reference() (Reference is the name of a resource in `many to one` relationships - its property is a `user_id` then reference() should return 'users' (table name)). So when you have an array of references it should be handled as well.
4. and this should render all the fields in admin UI, but you will need to handle [creating](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/resource.js#L116) and [updating](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/resource.js#L129) records.
5. All the properties are flattened. Which means that if you have an array of strings: `names: [string]` like: `['john', 'doe', 'benny', 'agnes']` it will be sent to create/update methods as:

```
{
  'names.0': 'john',
  'names.1': 'doe',
  'names.2': 'benny',
  'names.3': 'agnes',
}
```

not sure if sequelize will handle that. In mongoose we unflatten them first (with `flat` npm package).

and this should be it.
