### ISSUE TITLE
Can't handle Sequelize UniqueConstraintError

### ISSUE THREAD

**Issue by blurey8** [SoftwareBrothers/admin-bro#354]
My model:
```
const Superuser = sequelize.define('superuser', {
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
   ...
}
```

When I create new instance with existing email on admin bro dashboard, the debug console throw `SequelizeUniqueConstraintError: Validation error`  and the loading on save button didn't stop. I want to prevent this error just like Sequelize ValidationError. Since UniqueConstraintError is subclass of ValidationError, I suggest change on `resource.js` on `admin-bro-sequelizejs`.

before:
```
if (error.name === SEQUELIZE_VALIDATION_ERROR) {
    throw this.createValidationError(error)
}
```

suggested:
```
const SequelizeValidationError = require('sequelize').ValidationError
...
if (error instanceof SequelizeValidationError) {
    throw this.createValidationError(error)
}
```

And all works just like ValidationError.

Can we get update on `admin-bro-sequelizejs` or is there something I can do to fix this? (either make PR or change something in my code to handle this).

I also post this issue [here](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/17)

**Comment by wojtek-krysiak** [comment]
seems that it has been released recently - take a look here: https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/17 - in case of any followup errors - simply reopen SoftwareBrothers/admin-bro-sequelizejs#17
