### ISSUE TITLE
Custom class name

### ISSUE THREAD

**Issue by farmgameowner** [SoftwareBrothers/admin-bro#361]
Original question:

Hi! How can i set my custom class to table to tr tag. I what to make possible to change background of custom rows.

Acceptance criteria:
* to each design system component add a css class with `admin-bro_` prefix like `admin-bro_Button` etc.

**Comment by wojtek-krysiak** [comment]
classes are now handled by styled-components and are generated automatically. I will change the description of this task to add some custom class names to all design-system components

**Comment by wojtek-krysiak** [comment]
after this being done you will be able to use regular CSS selectors to change particular elements.

**Comment by wojtek-krysiak** [comment]
until then you can try to inject your custom css: https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#assets and select those elements via css selectors which don't require class names (you can utilise `data-testid` css property)

**Comment by wojtek-krysiak** [comment]
closed in verson 2.1.0-beta.7

**Comment by mding5692** [comment]
@wojtek-krysiak how do we inject the css file for custom css?

I tried this: 

```
  const adminBro = new AdminBro({
    assets: {
      styles: [AdminBro.bundle('./index.css')],
    },
    ....
  }
```

but not working

**Comment by mding5692** [comment]
Nevermind figured it out using this answer: https://stackoverflow.com/a/58046155/4297337
