### ISSUE TITLE
Error message: You have to specify "recordId" for record action

### ISSUE THREAD

**Issue by dhemas** [SoftwareBrothers/admin-bro#367]
**Describe the bug**
AdminBro gives me error about unspecified **recordId** as shown below

![screenshot](https://user-images.githubusercontent.com/23565404/76627697-1026af00-656e-11ea-9639-32a404636f44.png)

**Installed libraries and their versions**

* admin-bro@2.0.3
* admin-bro-expressjs@2.0.0
* admin-bro-sequelizejs@0.3.4

**To Reproduce**
1. Init sequelize with `sequelize-cli init`
2. Generate sequelize models with `sequelize-auto`
3. Run app with minimal config (mostly default)

**AdminBroOptions with schema**
```
// adminbro options
const adminBro = new AdminBro({
  // databases: [db],
  resources: [{
    resource: db.user_status,
    options: {
      //...
    }
  }],
  rootPath: '/admin',
})

// schema
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('user_status', {
    id: {
      type: DataTypes.INTEGER(4),
      allowNull: false,
      primaryKey: true
    },
    status: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: true
    }
  }, {
    tableName: 'user_status'
  });
};

```

**Desktop (please complete the following information if relevant):**
 - OS: [Windows 10 18363]
 - Browser [Chrome]
 - Version [80.0.3987.132]

**Comment by dhemas** [comment]
NVM, I just realized that sequelize model should have an auto increment primary key

**Comment by wojtek-krysiak** [comment]
please paste content from options:
```
resources: [{
    resource: db.user_status,
    options: {
      //... PASTE WHAT IS HERE
    }
  }],
```

most probably you define some after hooks which returns objects without { record } property

**Comment by uvios** [comment]
@wojtek-krysiak I am facing this issue 
    const adminBro = new AdminBro({
      rootPath: '/admin',
      // logoutPath: '/xyz-admin/exit',
      // loginPath: '/xyz-admin/sign-in',
      // databases: [mongooseConnection],
      resources: [{ resource: DstvPackages, options: {}}],
      branding: {
        companyName: 'abc',
      },
    })

**Comment by uvios** [comment]
node version v10.19.0

**Comment by uvios** [comment]
also it works fine with sample data. but when i connect it data previously used by application I am facing this

**Comment by wojtek-krysiak** [comment]
maybe because the previous records didn't have this primary Id column?
