### ISSUE TITLE
Is it possible to hide a resource from side menu?

### ISSUE THREAD

**Issue by maurocen** [SoftwareBrothers/admin-bro#377]
I'd like to hide a resource completely but still be able to access it via other resources relations.

Basically I want a resource not to show up on the side menu.

Is this currently possible?

Thanks in advance

**Comment by maurocen** [comment]
Possible via resource configuration:

Example with sequelize:

```js
const { Model } = require('../models');

module.exports = {
    resource: Model,
    options: {
        properties: { ... },
        actions: {
            list: {
                isAccessible: false, // This hides it from the panel but SHOW is still accessible via links.
            },
        },
    },
};
```

Found the answer on [this example](https://github.com/SoftwareBrothers/admin-bro-example-app/blob/master/admin/resources/blog-post.js)

**Comment by wojtek-krysiak** [comment]
there is also a new option href: https://softwarebrothers.github.io/admin-bro-dev/ResourceOptions.html#href which allows you to redirect users to show action
