### ISSUE TITLE
How to show record from reference table without custom component

### ISSUE THREAD

**Issue by hannyudayana** [SoftwareBrothers/admin-bro#378]
Hi,

I have been using adminbro for a while using the sequelize adaptor

Let's say I have 2 tables:
1. user. Fields: name, email
2. customer. Fields: user_id

Customer table have a user_id FK
On the customer list, can I show the fields from User table?
Can I also filter the list by those fields?

Any help would be appreciated :) Thanks

**Comment by wojtek-krysiak** [comment]
maybe this example will be a hepl: https://github.com/SoftwareBrothers/admin-bro-example-app. This is our "example" app - there is a User model and FavouritePlace and the latter belongs to User (So I think this is the exact case).

**Comment by puzpuz** [comment]
I also facing the similar problem with @hannyudayana , when I saw your example @wojtek-krysiak , I don't think it explain the problem (at least that I face). 

Maybe I can put it this way, from your example, how to show User's First Name and Last Name in the FavouritePlace record?

**Comment by wojtek-krysiak** [comment]
@puzpuz its not possible right now in an easy way :( - there is a tasks #279 which will allow doing that. The workaround would be to: 

* create a new property in the `users` table: `fullName` where you will "cache" `firstName` + `lastName`
* in admin set this fullName property as a title property: http://adminbro.com/PropertyOptions.html#isTitle (for the previous "title property" you have to set isTitle to false)
