### ISSUE TITLE
Override actions with custom page

### ISSUE THREAD

**Issue by maurocen** [SoftwareBrothers/admin-bro#379]
Is it possible to replace a resource's action page with a custom one build in React, without necessarily modifying the action handler?

Something like:

```js
const AdminBro = require('admin-bro');
const { Model } = require('./db');

module.exports = {
    resource: Model,
    views: {
        show: AdminBro.bundle('./ModelShow.jsx'),
        list: AdminBro.bundle('./ModelList.jsx'),
    },
};
```

I don't know if this is possible, or if it's possible by modifying the action's handler.

Thanks!

**Comment by wojtek-krysiak** [comment]
yes - there is a component property in each action: https://softwarebrothers.github.io/admin-bro-dev/Action.html#component

so
```
module.exports = {
    resource: Model,
    actions: {
        show: {component: AdminBro.bundle('./ModelShow.jsx')},
        list: {component: AdminBro.bundle('./ModelList.jsx')},
    },
};
```

but in order to modify the list I would modify components of each property.
