### ISSUE TITLE
Custom page's handler not being called

### ISSUE THREAD

**Issue by maurocen** [SoftwareBrothers/admin-bro#380]
Following example in [documentation](https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#pages)

I have a custom page defined

`Admin Bro options:`

```js
options: {
    customPage: {
        label: 'Custom page',
        component: AdminBro.bundle('./CustomPage.jsx'),
        handler: async (request, response, context) => {
              console.log(request, response);

              return {
                  text: 'I am fetched from the backend',
              };
            },
      },
},
```

`CustomPage.jsx:`

```jsx
import React from 'react';
import { Box } from 'admin-bro';

const CustomPage = (props) => {
  console.log(props);

  return (
    <Box variant="grey">
      <Box variant="white">
        <span>Hello</span>
      </Box>
    </Box>
  );
};

export default CustomPage;
```

But nothing is received in the `CustomPage.jsx` props (empty object `{}`). 
Furthermore, the `console.log` in the handler is not being printed, which makes me think the handler is not being called at all.

So I looked into the code a little bit more and found out the `handler` is called when making a request on `ADMINBRO_ROOT_URL/api/pages/CustomPage`, but not on `ADMINBRO_ROOT_URL/pages/CustomPage`.

I'm also not being able to see `console.log` defined in the dashboard handler function as specified [here](https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#dashboard).

Am I doing something wrong? I thought the handler would be called when accessing the pages in the browser so I could define `res.resource` and other props for the `CustomPage` to render.

**Comment by maurocen** [comment]
So I looked into the code a little bit more and found out the `handler` is called when making a request on `ADMINBRO_ROOT_URL/api/pages/CustomPage`, but not on `ADMINBRO_ROOT_URL/pages/CustomPage`.

How can I then load information and pass it as props to display in my custom page?

**Comment by maurocen** [comment]
I'm also not being able to see `console.log` defined in the dashboard handler function as specified [here](https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#dashboard).

**Comment by johnstan** [comment]
I think it's missing from the docs - similar to the dashboard (getDashboard()) you need to call getPage() to make the handler execute: https://adminbro.com/ApiClient.html#getPage
