### ISSUE TITLE
RTL feature for adminBro

### ISSUE THREAD

**Issue by ZahraDelkashroudsari** [SoftwareBrothers/admin-bro#382]
Hello there,

is it possible to make the whole admin panel right to left ? if so, would yo please give me a hint.

**Comment by wojtek-krysiak** [comment]
oh - it will be complicated but there is a way :). So there is an option to pass a custom stylesheet file to the adminbro, where you can rewrite all the interface as you want. Here it is: http://adminbro.com/AdminBroOptions.html#assets

basically you can use it like this:
```
const admin = new AdminBro({
  // your options,
  assets: {
    styles: [
      './path/to.custom.css',
    ]
  }
})
```

but remember that you have to host this css file somehow. If you use express take a look at this: https://expressjs.com/en/starter/static-files.html

**Comment by ZahraDelkashroudsari** [comment]
Thanks, it works just perfect.
