### ISSUE TITLE
Boolean values mis-display

### ISSUE THREAD

**Issue by AbdoElsaed** [SoftwareBrothers/admin-bro#384]
when i try to access any resource in the admin panel, boolean values displayed as No for both true and false values. and when i upgraded to the latest version 2.1.2 it doesn't show any value but only the field name. and when i try to edit , it show unchecked check-boxes for true and false values!
but it works fine when i try to filter by these values.

for example , in the below images , email verified and market joined are boolean fields with true and false values and there isn't something to indicate that !

please help ! and let me know if there is something wrong within my configurations.

![Screenshot_4](https://user-images.githubusercontent.com/24434547/77985802-b0722700-7315-11ea-9e12-aa2d6688d165.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/24434547/77985812-b49e4480-7315-11ea-8fcd-4f83e4406479.jpg)

**Comment by wojtek-krysiak** [comment]
which version of admin-bro-mongoose/sequelize do you use? can you share some configuration/schema code?

**Comment by AbdoElsaed** [comment]
@wojtek-krysiak 
I'm using admin-bro-mongoose@0.4.2.
 
```
const adminBro = new AdminBro({ 
databases: [mongoose],
resources: [
    {
      resource: User,
      options: {
        properties: {
          name: {
            isVisible: { list: true, filter: true, show: true, edit: false }
          }, email: {
            isVisible: { list: true, filter: true, show: true, edit: false }
          },
          password: {
            isVisible: { list: false, filter: false, show: false, edit: false }
          },
          phoneNumber: {
            isVisible: { list: true, filter: true, show: false, edit: false }
          },
          nationality: {
            isVisible: { list: true, filter: true, show: true, edit: false }
          }
        },
        parent: { name: 'User-Related' }
      }
    },
    {
      resource: Workspace
    },
    {
      resource: Job
    },
    {
      resource: Category
    },
    {
      resource: Invitation
    }],
  rootPath: '/admin',
  branding: {
    companyName: 'bla bla',
    softwareBrothers: false,
    logo: '/assets/images/logo.png'
  }
});
const Admin = {
  email: process.env.ADMIN_EMAIL || 'bla bla bla ',
  password: process.env.ADMIN_PASSWORD || 'bla bla bla'
};

const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
  cookieName: process.env.ADMIN_COOKIE_NAME || 'admin-bro',
  cookiePassword: process.env.ADMIN_COOKIE_PASS || 'supersecret',
  authenticate: (email, password) => {
    if (email === Admin.email && password === Admin.password) {
      return Admin;
    }
    return null;
  }
}); 
```

**Comment by AbdoElsaed** [comment]
@wojtek-krysiak hi, is there any update ?
