### ISSUE TITLE
Custom component Error: STACK does not have a file url. Check out if the node version >= 8

### ISSUE THREAD

**Issue by stelone** [SoftwareBrothers/admin-bro#388]
**Describe the bug**
Error `Error: STACK does not have a file url. Check out if the node version >= 8` when I try to load a custom component. 

**Installed libraries and their versions**

* admin-bro@2.1.2
* admin-bro-expressjs@2.0.0
* admin-bro-sequelizejs@0.3.4
* express@4.17.1
* mssql 
* node@12.14.1
* windows@10
* typescript@3.6.3

**To Reproduce**
1. Add custom resources
```
{
  options: {
    properties: {
      submodel: {
        component: {
          new: AdminBro.bundle('./admin-bro/SubModel.tsx'),
        }
      }
    }
  }
}
```

**Expected behavior**
`AdminBro.bundle` generate an error : `UnhandledPromiseRejectionWarning: Error: STACK does not have a file url. Check out if the node version >= 8`.
Same for  `AdminBro.require`. 

**Desktop:**
 - OS: windows 10
 - Browser chrome
 - Version 80.0.3987.149 

**Additional context**
I inspect a code of `AdminBro.bundle`, and I see : 
```
    if (src[0] === '/') {
      filePath = src;
    } else {
      const stack = (new Error().stack || '').split('\n');
      const m = stack[2].match(/\((.*):[0-9]+:[0-9]+\)/);

      if (!m) {
        throw new Error('STACK does not have a file url. Check out if the node version >= 8');
      }

      filePath = path.join(path.dirname(m[1]), src);
    }
```

`stack[2]` is equal to `at C:\Users\...\src\server\Routers\AdminRouter.ts:198:43`

**Comment by wojtek-krysiak** [comment]
I think it is related to #364 - can you downgrade node to v10 and see if that works?

**Comment by stelone** [comment]
Ok so I downgrade to v10 and it's working like a charm. 
This is a little annoying... my production server is on v12. 
v12 is the recommanded version.

**Comment by wojtek-krysiak** [comment]
yep I know - this issue will be fixed sooner rather than later

**Comment by wojtek-krysiak** [comment]
duplicates #364

**Comment by wojtek-krysiak** [comment]
duplicates #364
