### ISSUE TITLE
another property in BulkDelete rather than Email

### ISSUE THREAD

**Issue by ZahraDelkashroudsari** [SoftwareBrothers/admin-bro#392]
Hello dear,

by default, when we would like to delete or bulkDelete records we get a slide out which shows us selected records by users' emails. is it possible to change it to another property like phone number?
I changed the position in properties but it is still email.

thanks for any assistance,

**Comment by wojtek-krysiak** [comment]
yes - it is [`isTitle` property](https://adminbro.com/PropertyOptions.html#isTitle). Please set isTitle for email to false, and isTitle to this `other` property to true.
