### ISSUE TITLE
Errors in Documentation

### ISSUE THREAD

**Issue by stelone** [SoftwareBrothers/admin-bro#396]
**Describe the bug**
There are some errors in documentation : 
It's not : 
 * component but components => http://adminbro.com/tutorial-writing-react-components.html 
 * availableOptions but availableValues => http://adminbro.com/tutorial-customizing-resources.html

Thanks :) 

**Installed libraries and their versions**

* admin-bro@2.0.1

**Comment by wojtek-krysiak** [comment]
@stelone thanks. fixed.
