### ISSUE TITLE
Custom page position

### ISSUE THREAD

**Issue by kirovtome** [SoftwareBrothers/admin-bro#398]
**Describe the bug**
Is there a way to place custom page above the resources tab though?

**Installed libraries and their versions**

* admin-bro@2.1.2
* admin-bro-expressjs@2.0.0
* admin-bro-sequelizejs@0.3.4

**Comment by wojtek-krysiak** [comment]
you can achieve that by passing a custom stylesheet and there change the order of divs manually

**Comment by wojtek-krysiak** [comment]
closing the issue for now. If this won't help, let me know and reopen the issue,
