### ISSUE TITLE
Constant redirect

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/admin-bro#400]
**Describe the bug**

when loginUrl is `/app` and rootUrl `app/admin` it always redirects to the login when there is redirectUrl in the response - frontend thinks that user has been logout - we have to change `match` to endWith

**Installed libraries and their versions**

* admin-bro@2.2.4

**Expected behavior**
It should redirect only when the redirectUrl match exactly to loginUrl

**Comment by wojtek-krysiak** [comment]
the error doesn't occurs anymore

**Comment by chinaza-max** [comment]
> the error doesn't occurs anymore

Am having issues trying to make use of my own login page  with addmin bro

**Comment by chinaza-max** [comment]
I need help please
