### ISSUE TITLE
CUSTOM COMPONENT NOT RENDERING IN V2.0

### ISSUE THREAD

**Issue by divyansheccentric** [SoftwareBrothers/admin-bro#403]
I created a custom admin and exported it as a class component. still I cant see my custom component in version 2, In version 1 it works all fine. Below is the screenshot of the error that I get from panel @wojtek-krysiak 

![78453383-ec5b1280-76ae-11ea-8385-b6f2a7e6cec9](https://user-images.githubusercontent.com/32994707/78919943-4ba29380-7ab0-11ea-8d8e-6d2810c4fdd1.png)

**Comment by wojtek-krysiak** [comment]
what development console is saying? (in chrome console tab)

**Comment by divyansheccentric** [comment]
It just says the same thing, that is written inside error boundary box

**Comment by divyansheccentric** [comment]
Can Someone please help me in fixing this @wojtek-krysiak @michlask

**Comment by wojtek-krysiak** [comment]
1. do you have any errors in the terminal which runs node script?

2. can you write here your component?

**Comment by divyansheccentric** [comment]
1. I just see this error in console
![Screenshot from 2020-04-27 00-46-08](https://user-images.githubusercontent.com/32994707/80317284-8894b700-8820-11ea-8c5b-4a52d6dce00f.png)


2. Code for my Custom Dashboard


`import React from "react";
import { WrapperBox } from "admin-bro";
import { ViewHelpers, ApiClient } from "admin-bro";

export default class Dashboard extends React.Component {
  constructor(props) {
    super(props);
    this.h = new ViewHelpers();
    this.state = {
      data: {
        TotalUsers: 0,
        TotalPrelimsSeries: 0,
        TotalMainsSeries: 0,
        TotalTestSets: 0,
        TotalPayment: 0
      }
    };
  }
  componentDidMount() {
    const api = new ApiClient();
    api.getDashboard().then(response => {
      this.setState({ data: response.data });
    });
  }

  render() {
    return (
      <WrapperBox>
        <h2
          className="is-size-3-desktop is-size-4 -mobile is-size-4-tablet"
          style={{
            textAlign: "center",

            fontFamily: "roboto"
          }}
        >
          <i className="fas fa-user-shield"></i> Welcome to Rankerstack Admin
          Panel !
        </h2>
        <div
          style={{ marginTop: "1rem" }}
          className="columns is-multiline  is-centered"
        >
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",

              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column  level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                className="fas fa-users is-size-4-desktop is-size-5-mobile"
              />
              Total Users
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                fontFamily: "Roboto",
                textAlign: "center",
                color: "#fff"
              }}
            >
              {this.state.data.TotalUsers}
            </h3>
          </div>
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="is-size-4-desktop is-size-5-mobile"
              />
              Total Mains Series
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalMainsSeries}
            </h3>
          </div>
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="far fa-paper-plane is-size-4-desktop is-size-5-mobile"
              />
              Total Prelims Series
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalPrelimsSeries}
            </h3>
          </div>
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="fas fa-heart is-size-4-desktop is-size-5-mobile"
              />
              Total Test Sets
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalTestSets}
            </h3>
          </div>
        </div>
        <div
          style={{ marginTop: "1rem" }}
          className="columns is-multiline  is-centered"
        >
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="fas fa-heart is-size-4-desktop is-size-5-mobile"
              />
              Total Daily Mains
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalDailyMains}
            </h3>
          </div>
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="fas fa-heart is-size-4-desktop is-size-5-mobile"
              />
              Total Candidates
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalCandidates}
            </h3>
          </div>
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="fas fa-heart is-size-4-desktop is-size-5-mobile"
              />
              Total Payment
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalPayment}
            </h3>
          </div>
          <div
            style={{
              background: "#0082c8",
              minHeight: "200px",
              height: "auto",
              margin: "1rem",
              boxShadow: "0px 0px 8px 1px rgba(46,74,117,1)",
              borderRadius: "2ch"
            }}
            className="column level-item"
          >
            <h2
              className="is-size-4-desktop is-size-5-mobile"
              style={{ fontFamily: "Roboto", color: "#fff" }}
            >
              <i
                style={{
                  textAlign: "center",
                  marginRight: "2rem",

                  color: "#fff"
                }}
                class="fas fa-heart is-size-4-desktop is-size-5-mobile"
              />
              Total Mail Sent
            </h2>
            <h3
              className="is-size-2-desktop is-size-5-mobile"
              style={{
                marginTop: "2rem",
                textAlign: "center",

                color: "#fff"
              }}
            >
              {this.state.data.TotalMailSent}
            </h3>
          </div>
        </div>
      </WrapperBox>
    );
  }
}
`



3. Code Where I am importing my custom Dashboard

`dashboard: {
    handler: async () => {
      return {
        TotalUsers: await User.countDocuments(),
        TotalPrelimsSeries: await User.find({
          SeriesType: "Prelims"
        }).countDocuments(),
        TotalMainsSeries: await TestSeries.find({
          SeriesType: "Mains"
        }).countDocuments(),
        TotalDailyMains: await DailyMains.countDocuments(),
        TotalCandidates: await Candidate.countDocuments(),
        TotalMailSent: await Mail.countDocuments(),
        TotalTestSets: await TestSet.countDocuments(),
        TotalPayment: await FetchPayment()
      };
    },
    component: AdminBro.bundle("../components/Dashboard.jsx")
  },`



@wojtek-krysiak

**Comment by wojtek-krysiak** [comment]
in v2 there is no WrapperBox component - you have to change it to <Box>

**Comment by divyansheccentric** [comment]
Thanks I just removed wrapper box and added a div. It Worked @wojtek-krysiak

**Comment by wojtek-krysiak** [comment]
jeeeey :)
