### ISSUE TITLE
Create multiple row in new and edit

### ISSUE THREAD

**Issue by stelone** [SoftwareBrothers/admin-bro#404]
When user click on save in edit or new screen, is there a way to insert multiple row in the same time in database ?

**Comment by wojtek-krysiak** [comment]
you will have to override handlers for `edit` and `new` actions.

**Comment by wojtek-krysiak** [comment]
this is the original code: https://github.com/SoftwareBrothers/admin-bro/blob/master/src/backend/actions/edit-action.ts#L29 (not super complicated)

**Comment by stelone** [comment]
thanks !
