### ISSUE TITLE
Image Upload for the latest version of adminBro

### ISSUE THREAD

**Issue by AmiXDev** [SoftwareBrothers/admin-bro#405]
Hello there,

Before submitting a report, I worked on image upload functionality #95. But came across this Javascript error

### Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `ImageUpload`.

but whenever I switch my adminBro panel to these following version the image upload works fine.

yarn add admin-bro@1.5.0-beta.5
yarn add admin-bro-expressjs@0.4.0-beta.2
yarn add express-formidable

it seems to me that #95 does not match quite well with the latest version of adminBro.

thanks a bunch for any assistance.

**Comment by wojtek-krysiak** [comment]
yes - it was a couple of versions before - please check out if there are any errors in the terminal

**Comment by ZahraDelkashroudsari** [comment]
Hello, once again

I have got no errors in the terminal except these following ones

### 'useState' is imported from external module 'react' but never used
### 'BasePropertyProps' is imported from external module 'admin-bro' but never used

and in development console I get couple of these js errors

### Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

thanks for the support.

**Comment by mohamed-nazmi** [comment]
Hello,

With these following versions:
    "admin-bro": "^2.2.4"
    "admin-bro-expressjs": "^2.0.4"

and the following import in my .tsx file:
import { BasePropertyProps, DropArea, PropertyInEdit } from 'admin-bro'

I get the following two errors:
**Module '"./node_modules/admin-bro"' has no exported member 'DropArea'. Did you mean to use 'import DropArea from "./node_modules/admin-bro"' instead?**

**Module '"./node_modules/admin-bro"' has no exported member 'PropertyInEdit'. Did you mean to use 'import PropertyInEdit from "./node_modules/admin-bro"' instead?**


I can't find the drop-area.tsx file in the node_modules' path as written in the documentation:
admin-bro/src/frontend/components/app/drop-area.tsx

However, at the old version of admin-bro@1.5.0-beta.5, I found the file and there were no errors.

I'd be thankful for any help.

**Comment by wojtek-krysiak** [comment]
in v2 drop area had been changed to DropZone. Property in edit doesnt exist anymore, use FormGroup instead (with Label). take a look at the examples here: https://adminbro.com/FormGroup.html

**Comment by spadgeaki** [comment]
@wojtek-krysiak Hello, whats the current way of changing records from my custom action component?

I have custom action defined:
```js
// in the middle of resource options
passwordLink: {
    actionType: 'record',
    icon: 'Password',
    isVisible: true,
    showInDrawer: true,
    handler: async (req, res, context) => {
        const Client = context._admin.findResource('client')
        const current = await Client.findOne(req.params.recordId)
        return {
            record: current.toJSON(context.currentAdmin),
        }
    },
    component: AdminBro.bundle('./components/PasswordLink'),
}
```
I tried using useRecord hook like this:
```js
const PasswordLink = (props) => {
    const { record, handleChange, submit } = useRecord(props.record, props.resource.id)

    const handleGenerateLink = async () => {
        handleChange("temp_token", generateToken())
        const res = await submit()
        console.log("res", res)
    }

    return (
        <Box>
            <Drawer>
                <DrawerContent>
                    <FormGroup>
                        <Text>
                            Click bellow to generate password link.
                        </Text>
                        <Button size="sm" onClick={handleGenerateLink}>
                            <Icon icon="Password" />
                            Generate link
                        </Button>
                    </FormGroup>
                </DrawerContent>
            </Drawer>
        </Box>
    )
}

export default PasswordLink
````

But I get this error with wrong link to documentation. :/

![Screenshot 2020-06-23 at 18 07 34](https://user-images.githubusercontent.com/1612627/85427728-73b47580-b57c-11ea-9c8e-0f493ff698b5.png)

Commenting out `handleChange` line makes error disappear but then I wont change any data. :)

Thank you for great project tho, looking forward to working with it!

**Comment by spadgeaki** [comment]
Also I managed to find [this screencast](https://www.youtube.com/watch?v=7WtKcFqJHho) which helped me a lot but not with my use case of having whole separate form for editing only one property of record.

**Comment by wojtek-krysiak** [comment]
it looks that your component is not properly bundled or there is an error in the react code. So:

1. Is there an error in the terminal? (nodejs terminal where you launch the admin bro)
2. maybe you run your app locally with NODE_ENV === production - in that case AdminBro will create a bundled file in `.adminbro` folder. In this case, simply remove `.adminbro` folder.

**Comment by wojtek-krysiak** [comment]
I am closing this issue because there is a tutorial describing Image Upload here: https://www.youtube.com/watch?v=7WtKcFqJHho

**Comment by GithubMuler** [comment]
I follow the video but finally it says the following:                  
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `BasePropertyComponent`.
See development console for more details.............

**Comment by GithubMuler** [comment]
![adminpanel1](https://user-images.githubusercontent.com/70884370/184552027-3f0c0b98-1c14-4a59-b8c4-120621cd0986.PNG)
![component1](https://user-images.githubusercontent.com/70884370/184552030-f988f052-62cf-43e6-bdb1-020f99c1fc4f.PNG)
![error](https://user-images.githubusercontent.com/70884370/184552031-f1849805-cee7-4e33-a382-cbc7c1a88def.PNG)
![model1](https://user-images.githubusercontent.com/70884370/184552032-ef9ad777-ec88-4f62-86b1-607d99b81f27.PNG)

**Comment by Vo0oX** [comment]
> ![adminpanel1](https://user-images.githubusercontent.com/70884370/184552027-3f0c0b98-1c14-4a59-b8c4-120621cd0986.PNG)
> ![component1](https://user-images.githubusercontent.com/70884370/184552030-f988f052-62cf-43e6-bdb1-020f99c1fc4f.PNG)
> ![error](https://user-images.githubusercontent.com/70884370/184552031-f1849805-cee7-4e33-a382-cbc7c1a88def.PNG)
> ![model1](https://user-images.githubusercontent.com/70884370/184552032-ef9ad777-ec88-4f62-86b1-607d99b81f27.PNG)

how you fix it ?
