### ISSUE TITLE
Unable to fetch second degree referenced data with mongoose models

### ISSUE THREAD

**Issue by dorkmania** [SoftwareBrothers/admin-bro#408]
Hi,

I'm using 
 ```
    "admin-bro": "^2.1.2",
    "admin-bro-expressjs": "^2.0.0",
    "admin-bro-mongoose": "^0.4.2", 
```

I have 3 models.
F = Fabric (Defines characteristics of a specific Fabric) 
FP = FabricPurchase (Defines details of purchase of specific Fabrics)
FQC = FabricQualityCheck (Defines results of quality check performed on Fabric Purchases)

FP holds a reference to an F instance and FQC holds a reference to FP. 
When I try to set an 'after' action handler on 'show' or 'list' for FQC, the record(s) is/are populated only with the data from FP but not the underlying F. 

How can the indirectly referenced data from F be accessible in action handlers for FQC?

**Comment by wojtek-krysiak** [comment]
it populates just one level down :( - You will have to manually populate it in after hook.
