### ISSUE TITLE
Boolean fields edit only works with True values

### ISSUE THREAD

**Issue by nathanguigui** [SoftwareBrothers/admin-bro#410]
using AdminBro@2.2.4

Hello in AdminBro 2.2.4 when you edit boolean fields with the default edit it only update in the DB when the boolean is set to True  .
When the boolean is set to False  then the fields set to False disappears from the request

**Comment by wojtek-krysiak** [comment]
hi - please try out 2.2.6

**Comment by wojtek-krysiak** [comment]
fixed that in the latest release. Please update admin-bro to: 2.4.3
