### ISSUE TITLE
some of my DB isn't showing up

### ISSUE THREAD

**Issue by andrew-lovato** [SoftwareBrothers/admin-bro#414]
I am using the 'databases' option when getting DB information into AdminBro. my 'Products' and 'Admin' are showing up. my 'Articles' shows, but the content is inaccessible. my 'Orders' and 'Users' aren't displaying at all. I was wondering if there was a known fix for this issue. Thank you so much in advance. 

// Passing resources by giving entire database
  const adminBro = new AdminBro({
    databases: [mongoose],
  rootPath: '/admin',
  })

**Comment by wojtek-krysiak** [comment]
did you require schemas for those 2 collections before running AdminBro???

```
require('my/model1.js')
require('my/model2.js')

const run = async () => {
  await connection = await mongoose.connect(....)
  const AdminBro = new AdminBro({})
}
```

btw remember to connect with the database before creating AdminBro instance

**Comment by andrew-lovato** [comment]
I will try those, thank you so much!

**Comment by wojtek-krysiak** [comment]
closing the issue for now - please reopen if it happens again
