### ISSUE TITLE
express-formidable doesn't work with bodyParser

### ISSUE THREAD

**Issue by vikash766** [SoftwareBrothers/admin-bro#415]
**Describe the bug**

I am using bodyParser in my app but its not letting me save the data.
can someone please suggest some alternative or a workaround?

import path from 'path';
import { Request, Response, NextFunction, Router, Application } from 'express';

import express from "express";
import formidableMiddleware from 'express-formidable';

import bodyParser from 'body-parser';
import mongoose from 'mongoose';
import { diskStorage } from "multer";
import multer from 'multer';
import authRoutes from './routes/auth'
import appsRoutes from './routes/apps'
import adminRoutes from './routes/admin'

import usersettingsRoutes from './routes/usersettings'
let app = express();
app.use(formidableMiddleware());

const fileStorage = diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'images');
  },
  filename: (req, file, cb) => {
    cb(null, new Date().toISOString() + '-' + file.originalname);
  }
});

const fileFilter = (req: Request, file: any, cb: any) => {
  if (
    file.mimetype === 'image/png' ||
    file.mimetype === 'image/jpg' ||
    file.mimetype === 'image/jpeg'
  ) {
    cb(null, true);
  } else {
    cb(null, false);
  }
};

app.use(bodyParser.json()); 

app.get('/', (req, res) => res.send('Hello World!'))

app.use(
  multer({ storage: fileStorage, fileFilter: fileFilter }).single('image')
);
app.use('/images', express.static(path.join(__dirname, 'images')));

app.use('/auth', authRoutes);
app.use('/apps', appsRoutes);
app.use('/settings', usersettingsRoutes);
app.use('/admin', adminRoutes);

app.use((error: any, req: Request, res: Response, next: NextFunction) => {
  console.log(error);
  const status = error.statusCode || 500;
  const message = error.message;
  const data = error.data;
  res.status(status).json({ message: message, data: data });
});

mongoose
  .connect(
    'mongodb://localhost/appss'
  )
  .then(result => {
    app.listen(8080);
  })
  .catch(err => console.log(err));

  export default app;

**Installed libraries and their versions**

    "admin-bro": "^2.2.5",
    "admin-bro-expressjs": "^2.0.4",
    "admin-bro-mongoose": "^0.5.1",
... mongo, express (whatever you think is relevant)

Error Received***

Error: Request aborted
    at IncomingMessage.<anonymous> (/Users/Desktop/Projects/Nodeapp/node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:209:13)
    at abortIncoming (_http_server.js:492:9)
    at socketOnClose (_http_server.js:485:3)
    at Socket.emit (events.js:214:15)
    at TCP.<anonymous> (net.js:658:12)

**Comment by wojtek-krysiak** [comment]
`adminRoutes` is a router created with `build(Authenticated)Router` function. 

So to fix that you need to invoke

app.use('/admin', adminRoutes);

before

app.use(bodyParser.json());

**Comment by vikash766** [comment]
Hi Wojtek, thanks for quick reply.

I tried your solution, but it didn't worked, after some google search and trying various solutions i found formidableMiddleware  is incompatibe with body-parser.

still looking for some workaround!

**Comment by vikash766** [comment]
it worked...i just had to move formidableMiddleware after bodyParser.
Thanks a ton!
