### ISSUE TITLE
You have to specify "recordId" for record action

### ISSUE THREAD

**Issue by DimaDevel** [SoftwareBrothers/admin-bro#417]
I got an error while trying to go to the /admin/resources/User page
Error: you must specify "recordId" for the record action

**Installed libraries and their versions**

* admin-bro@2.2.5
<img width="1907" alt="Screenshot 2020-04-22 at 14 12 08" src="https://user-images.githubusercontent.com/42233432/79975478-b9cd5a00-84a3-11ea-837a-49de31460931.png">

* admin-bro-expressjs@2.0.4
* admin-bro-mongoose@0.5.1
... mongo, express (whatever you think is relevant)

How can I fix this error?

**Comment by wojtek-krysiak** [comment]
did you made some modifications? custom components?

**Comment by DimaDevel** [comment]
No, I didn't make any modifications. I tried to use a snippet of code from your documents.

**Comment by shathaku** [comment]
Facing similar issue. 
I was trying to add AdminBro to my existing application. 

Installed libraries:

"admin-bro": "^2.2.7",
"admin-bro-expressjs": "^2.0.4",
"admin-bro-sequelizejs": "^0.4.0"

**Comment by shathaku** [comment]
I think i got the issue .
Suppose this is my Model.

const testUser = sequelizeClient.define('TestUser', {
    id: {
      type: DataTypes.STRING,
      allowNull: false,
      primaryKey: true,
      field: 'ID'
    },
    fullName: {
      type: DataTypes.STRING,
      allowNull: true,
      field: 'Fullname'
    },
    role: {
      type: DataTypes.STRING,
      allowNull: true,
      field: 'Role'
    },
    email: {
        type: DataTypes.STRING,
        allowNull: true,
        field: 'Email'
      }
  }

Here, the attribute name does not exactly match the 'field' name I provided for the attribute. Once i made them exactly same (matching the case) it started working. Like this:

const testUser = sequelizeClient.define('TestUser', {
    id: {
      type: DataTypes.STRING,
      allowNull: false,
      primaryKey: true,
      field: 'id'
    },
    fullName: {
      type: DataTypes.STRING,
      allowNull: true,
      field: 'fullName'
    },
    role: {
      type: DataTypes.STRING,
      allowNull: true,
      field: 'role'
    },
    email: {
        type: DataTypes.STRING,
        allowNull: true,
        field: 'email'
      }
  }

Now i would like to know, what could we do in case i want my 'field' value different from the attribute name.
