### ISSUE TITLE
property.availableValues could be taken into account on list and in show actions too, not only when editing

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/admin-bro#418]
**Describe the problem feature solves**
property.availableValues can change display of values in edit screen, but values are still visible as raw in show and on list. I would have to create React component just to display exactly the same there.
**Describe the solution you'd like**
property.availableValues could also change display of property in show and list actions.

**Acceptance criteria**
property.availableValues are used on show action
property.availableValues are used on list instead of raw value

**Comment by wojtek-krysiak** [comment]
released in v2.2.9
