### ISSUE TITLE
Separating logic for action GET and action POST in handler.

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/admin-bro#419]
**Describe the problem feature solves**
Some handlers have logic for both get requests and post requests, for example [bulkDelete](https://adminbro.com/admin-bro_src_backend_actions_bulk-delete-action.ts.html). It's a bit problematic when customizing part of handler, for example modifying post action only.

**Describe the solution you'd like**
Simplified concept:
```
actions: {
      bulkDelete: {
        getHandler: async (req, res, context) => { 
            //...
        },
        postHandler: async (req, res, context) => { 
            //...
        },
        handler: async (req, res, context) => {
          if (request.method === 'get') {
             return getHandler(req, res, context)
          }
          if (request.method === 'post') {
             return postHandler(req, res, context)
          }
        },
      },
    },
}
```

**Comment by wojtek-krysiak** [comment]
I think that it will complicate the system too much. We will have to implement this also for all the hooks and then maintain these 3 ways of passing functions. That is why I am closing this one
