### ISSUE TITLE
Setting a title to property is sometimes ignored and default title is taken instead

### ISSUE THREAD

**Issue by SimonB407** [SoftwareBrothers/admin-bro#420]
**Describe the bug**
When changing property to be the title, adminbro sometimes ignores this setting and goes with default title instead. Might be related to properties order. This can be seen for example on bulk delete drawer.

**Installed libraries and their versions**
* admin-bro@2.2.6

**To Reproduce**

**Expected behavior**
When setting
```
properties: {
   property: {
      isTitle: true,
   },
}
```
this property should become title.

**AdminBroOptions with schema**
Model schema:
```
const schema = new Schema({
  email: {
    type: String,
    lowercase: true,
    trim: true,
  },
  auth: {
    password: {
      type: String,
    },
  },
  name: {
    type: String,
    required: true,
    trim: true,
  },
  publicName: {
    type: String,
    required: false,
    trim: true,
  },
  // ... more fields
});
```
  
Admin bro resource options:
```
options: {
    listProperties: ['status', '_id', 'publicName', 'email', /*some more not related props*/],
    sort: {
      direction: 'desc',
      sortBy: 'createdAt',
    },
    properties: {
      publicName: {
        isTitle: true, // email is set as title in this config
      },
    },
}
```

**Additional context**
Can be solved, as a dirty hack, by setting default title property to have `isTitle` set to false, f.e. in my case:
```
publicName: {
  isTitle: true,
},
email: {
  isTitle: false,
},
```

**Comment by wojtek-krysiak** [comment]
created a task to change that: #568
