### ISSUE TITLE
Custom Reference Field values in edit/new/filter

### ISSUE THREAD

**Issue by djbange** [SoftwareBrothers/admin-bro#421]
Is there any way to select different field or  combination of fields from reference collection to display it in dropdown of edit/new/filter ? I have lot's of duplicates values in default field selected  to display values in dropdown.

**Comment by wojtek-krysiak** [comment]
you will need to override the component for this property

**Comment by wojtek-krysiak** [comment]
related to #279

**Comment by wojtek-krysiak** [comment]
since #279 is closed also close this one

**Comment by loagencydev** [comment]
any solutions for this one? seems like the #279 doesn't actually address this issue
