### ISSUE TITLE
admin-bro-sequelizejs

### ISSUE THREAD

**Issue by ksewo** [SoftwareBrothers/admin-bro#423]
Hello.

I have a question. Is admin-bro-sequelizejs officialy supported and safe to use?
I have been waiting for over 2 weeks and I got 0 response for my PR.

This PR changes only 2 LOC and fixes one bug.
https://github.com/SoftwareBrothers/admin-bro-sequelizejs/pull/23

I know I shouldn't open here issue for other library, but it looks like it's official library for admin-bro and It's been over 17 days and no response.

**Comment by wojtek-krysiak** [comment]
np - already merged - missed that one.
