### ISSUE TITLE
Property formatter method

### ISSUE THREAD

**Issue by MaxVynohradov** [SoftwareBrothers/admin-bro#424]
Use case 1: we have date time  field or any other type of field, and we want to show it as text, or any other standard type of property field, but format this to the human-readable text.

Use case 2: URLs to the images, for instance. Usually we store in DB just path to url without base url (it depends on ENV / STAGE), and it will be great to format this url on back-end side

**Comment by wojtek-krysiak** [comment]
Sorry for late response - tbh I was wandering if we should implement that. But you can use after hook to change the action response or write a custom component to simply render it in a different format. That is why we don't want to introduce this new option.
