### ISSUE TITLE
the list records not shown in mobile view

### ISSUE THREAD

**Issue by jsotoca** [SoftwareBrothers/admin-bro#429]
hi i can't see list of records from a smartphone

**libraries**
"admin-bro": "^2.2.7",
"admin-bro-expressjs": "^2.0.4",
"admin-bro-mongoose": "^0.5.1",
 "express-formidable": "^1.2.0",
 "mongoose": "^5.9.10"
![Anotación 2020-04-29 220544](https://user-images.githubusercontent.com/51462077/80667753-a010b180-8a65-11ea-9711-2c0f36dda0c5.png)

**Comment by wojtek-krysiak** [comment]
you have to set one column as `isTitle`: https://adminbro.com/PropertyOptions.html#isTitle

**Comment by ivictbor** [comment]
@wojtek-krysiak and then you will see only this one column, right?
Is it possible to config admi js to have table on mobile? I am now switching to Desktop mode on my mobile chrome  to at least access the table data, though they are look very wierd anyway, also seams like pagination in this mode is not working. Probably there are at least some plugins?
