### ISSUE TITLE
Filter records based on array values

### ISSUE THREAD

**Issue by KalleVuorjoki** [SoftwareBrothers/admin-bro#438]
## Describe the problem feature solves
On example [repository](
https://admin-bro-example-app-staging.herokuapp.com/admin/resources/Complicated
)'s `ComplicatedSchema` there's one field that is defined as an array.

```
  stringArray: {
    type: [String],
    required: true,
  },
```
However one cannot filter records based on array values.

## Describe the solution you'd like
Ability to select one or multiple values of array. Can be checkboxes or select2 element.

**Before:**

<img width="401" alt="before" src="https://user-images.githubusercontent.com/3080364/80959412-7235bf00-8e0f-11ea-9cdf-c257a8e13a0a.png">

**After:**

<img width="400" alt="after" src="https://user-images.githubusercontent.com/3080364/80959428-782ba000-8e0f-11ea-93a1-9a880fc83c40.png">

## Acceptance criteria
- Being able to filter records with multiple array values.

**Comment by Gr8z** [comment]
+1

**Comment by iblessedi** [comment]
+1

**Comment by l0renc** [comment]
+1

**Comment by wojtek-krysiak** [comment]
sorry for the delay - we did a MAJOR code refactor and this took much longer than expected (the wors - no feature but better code). But added this issue is in 3.3 milestone

**Comment by wojtek-krysiak** [comment]
we wont make it in 3.3 - delayed to 4.0 :( - created a separate big task for filter improvements: #251
