### ISSUE TITLE
Exclude node_modules from babel

### ISSUE THREAD

**Issue by TaylorBriggs** [SoftwareBrothers/admin-bro#440]
**Describe the bug**
Babel is processing files in node_modules that shouldn't be transpiled.

**Installed libraries and their versions**

* admin-bro@2.3.0
* admin-bro-expressjs@2.0.5
* admin-bro-mongoose@0.5.2
* mapbox-gl@1.9.1

**To Reproduce**
I'm using a custom component that requires `mapbox-gl`.  Running the app logs the following in the console:

```
[BABEL] Note: The code generator has deoptimised the styling of [project_path]/node_modules/mapbox-gl/dist/mapbox-gl.js as it exceeds the max of 500KB.
'fs' is imported by node_modules/jsonlint-lines/lib/jsonlint.js, but could not be resolved – treating it as an external dependency
'path' is imported by node_modules/jsonlint-lines/lib/jsonlint.js, but could not be resolved – treating it as an external dependency
'fs' is imported by commonjs-external-fs, but could not be resolved – treating it as an external dependency
'path' is imported by commonjs-external-path, but could not be resolved – treating it as an external dependency
```

**Expected behavior**
Babel should not transpile anything in `node_modules`.

**Screenshots**
![Screen Shot 2020-05-05 at 12 28 55 PM](https://user-images.githubusercontent.com/1335519/81096486-0e250080-8ecc-11ea-85ef-15ecc31406c5.png)
![Screen Shot 2020-05-05 at 12 28 39 PM](https://user-images.githubusercontent.com/1335519/81096493-111ff100-8ecc-11ea-984d-d9460d72e2b2.png)

**Desktop (please complete the following information if relevant):**
 - OS: macOS 10.15.4
 - Browser Firefox
 - Version 76.0

**Additional context**
Removing the import for `mapbox-gl` returns the admin app to normal.

**Comment by wojtek-krysiak** [comment]
I wasn't aware of this option in rollup. Thanks a lot for pointing this out.
