### ISSUE TITLE
Can't fetch resource. There are no errors in the console

### ISSUE THREAD

**Issue by TalbotGooday** [SoftwareBrothers/admin-bro#441]
I'm trying to add custom resources like this
`const adminBro = new AdminBro({
    resources: [db.Phrase],
   ...
}`
The Phrase model looks like this:
```javascript
'use strict';

const Sequelize = require('sequelize');

exports.default = class Phrase extends Sequelize.Model {
    static init(sequelize) {
        return super.init({
            originalText: Sequelize.TEXT,
            transliteration: Sequelize.TEXT,
            translationKey: Sequelize.STRING
        }, {
            sequelize: sequelize,
            tableName: 'phrases',
            timestamps: true,
            paranoid: true,

        });
    }

    static associate(models) {
        this.belongsTo(models.User, {as: 'author'});

        this.belongsTo(models.CategoryPhrase, {
            as: 'category',
            foreignKey: {
                allowNull: false
            }
        })

        this.hasMany(models.TranslationPhrase, {
            constraints: false,
            as: 'titles',
            foreignKey: 'key',
            sourceKey:'translationKey'
        })
    }
}
```
When trying to get this model in the admin interface I get an error:
**There was an error fetching records, Check out console to see more information**

But there are no errors in the console. Probably it's 'cause in the `use-records.ts` the `fetchData` method does not log any errors and only shows `errorFetchingRecords` message.

This problem does not occur if you connect the database directly:
`const adminBro = new AdminBro({
    databases: [db]
}`

___
Also I get a react warning:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Async, Select
___
* "admin-bro": "^2.3.0",
* "admin-bro-expressjs": "^2.0.5",
* "admin-bro-sequelizejs": "^0.4.2",

**Comment by wojtek-krysiak** [comment]
maybe you haven't connected with the database?

**Comment by wojtek-krysiak** [comment]
closing the issue due to the lack of the comunication
