### ISSUE TITLE
JSONB field does not render properly

### ISSUE THREAD

**Issue by mtjn** [SoftwareBrothers/admin-bro#444]
**Describe the bug**
A JSONB field in postgresql is not rendered properly by admin-bro using default settings. A react error is generated for trying to render an object as a react element

**Installed libraries and their versions**
* admin-bro@2.3.0
* admin-bro-expressjs@2.0.5
* admin-bro-sequelizejs@0.4.2

**To Reproduce**
1. Create and populate postgresql database with jsonb field
2. initialize admin-bro
3. open the admin interface

**Expected behavior**
The JSONB data is stringified and rendered in a formatted code block.

**Screenshots**
![image](https://user-images.githubusercontent.com/26892660/81301733-b926ed00-9079-11ea-9605-1c1afce4f43c.png)

**Desktop (please complete the following information if relevant):**
 - OS: Ubuntu 20.04
 - Browser: Chromium
 - Version: 81.0.4044.138 (Official Build) snap (64-bit)

**Comment by wojtek-krysiak** [comment]
this was probably fixed in 3.3.0-beta along with other fixes regarding nested schemas
