### ISSUE TITLE
Can someone please review #26 admin-bro-sequelizejs

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [SoftwareBrothers/admin-bro#447]
**Describe the bug**
Could someone please take a look at #26 admin-bro-sequelizejs? This is a major issue for us. We'd like to deploy AdminBro to production but would like to do it without having to use a custom version of AdminBro Sequelizejs
https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/26

Thanks,
Michael

**Comment by wojtek-krysiak** [comment]
@MichaelLeeHobbs I am closing this one since the PR has been closed. Let's move the discussion to https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/26
