### ISSUE TITLE
Dashboard Tutorial Links 404

### ISSUE THREAD

**Issue by mattdelliott** [SoftwareBrothers/admin-bro#449]
**Describe the bug**
Dashboard tutorial links are busted. Whenever I click on one, it takes me to a URL that doesn't exist. Looks like the number in them is no longer there. https://adminbro.com/tutorial-03-passing-resources.html -> https://adminbro.com/tutorial-passing-resources.html

**Installed libraries and their versions**

* admin-bro@2.3.1
* admin-bro-hapijs@2.0.0
* admin-bro-sequelize@0.4.2

**To Reproduce**
1. Go to 'Dashboard
2. Click on 'Adding Resources' (or any other link)
3. See error

**Expected behavior**
Links to go to valid pages.

**Screenshots**
<img width="1106" alt="Screen Shot 2020-05-11 at 12 50 15@2x" src="https://user-images.githubusercontent.com/340321/81599714-fba43e80-9385-11ea-9eb7-3c83fa5a2eb6.png">
<img width="1295" alt="Screen Shot 2020-05-11 at 12 50 29@2x" src="https://user-images.githubusercontent.com/340321/81599762-02cb4c80-9386-11ea-8937-21054784faf1.png">

**Comment by DimaDevel** [comment]
I have the same problem
