### ISSUE TITLE
Given file "./my-dashboard-component", doesn't exist.

### ISSUE THREAD

**Issue by vinyll** [SoftwareBrothers/admin-bro#454]
When following the [steps to create and use a custom component](https://adminbro.com/tutorial-writing-react-components.html), Node returns the following error:

```
…/node_modules/admin-bro/lib/admin-bro.js:370
      throw new _configurationError.default(`Given file "${src}", doesn't exist.`, 'AdminBro.html');
            ^

ConfigurationError:
    Given file "./my-dashboard-component", doesn't exist.
    More information can be found at: https://softwarebrothers.github.io/admin-bro-dev/AdminBro.html

    at Function.bundle (…/node_modules/admin-bro/lib/admin-bro.js:370:13)
    at default (file://…/src/admin.mjs:16:27)
    at file://…/src/index.mjs:39:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:141:24) {
  name: 'ConfigurationError'
}
```

My admin file:

```js
  AdminBro.registerAdapter(AdminBroMongoose)
  const adminBro = new AdminBro({
    rootPath: route,
    branding: {
      companyName: 'My Admin',
    },
    dashboard: {
      component: AdminBro.bundle('./my-dashboard-component')
    },
```

And I created the _my-dashboard-component.jsx_ in the same folder, as the example says.

**Installed libraries and their versions**

    "admin-bro": "^2.2.9",
    "admin-bro-expressjs": "^2.0.5",
    "admin-bro-mongoose": "^0.5.1",

Also, the content of my .adminbro/.entry.js is only:
```
AdminBro.UserComponents = {}
```

Extra: OS: MacOSX Catalina, Node v13.6.0

**Comment by wojtek-krysiak** [comment]
1. can you try to use node 12? - admin relies on errors format thrown by node so this could be it.
2. if it won't help I have a question: do you use either babel or typescript? - they can change paths of the files in build process

**Comment by vinyll** [comment]
Using Node 12 did not help.

I don't use babel not typescript; I use module import.

`cat admin.mjs`:
```js
import AdminBro from 'admin-bro'
import AdminBroExpress from 'admin-bro-expressjs'
import AdminBroMongoose from 'admin-bro-mongoose'

import { Article } from './articles/models.mjs'

export default function (app, route) {
  AdminBro.registerAdapter(AdminBroMongoose)
  const adminBro = new AdminBro({
    rootPath: route,
    branding: {
      companyName: 'My Admin',
    },
    dashboard: {
      component: AdminBro.bundle('./my-dashboard-component')
    },
   …
```

cat `my-dashboard-component.jsx`:

```js
import React from 'react'
import { Box } from 'admin-bro'

const Dashboard = (props) => {
  return (
    <Box>My custom dashboard</Box>
  )
}

export default Dashboard
```

Then I just run my express server.

Is there a step to run in order to make the jsx file available and register it somewhere?

**Comment by wojtek-krysiak** [comment]
i think .mjs could cause this problem. Can you change it to a regular require statements?

**Comment by vinyll** [comment]
Thanks for your reply. 
I've refactored the project accordingly to use only `.js` files instead of `.mjs` and running Node 12… Still no luck.
My `.adminbro/.entry.js` is still only containing `AdminBro.UserComponents = {}`.

I also tried workarounds like (admin.js):
```js
…
    dashboard: {
      component: function() { return `Hey bro` }
    },
```
The server runs but I'm surprised the default dashboard component still displays without breaking.
Is there a way to manually register the component and/or skipping the magic?

**Comment by wojtek-krysiak** [comment]
to skip the magic:

```
    dashboard: {
      component: 'SomeRandomNameOfTheComponent'
    },
```

```
// .entry.js
AdminBro.UserComponents = {}
import SomeRandomNameOfTheComponent from '../path-to-your-component'
AdminBro.UserComponents.SomeRandomNameOfTheComponent = SomeRandomNameOfTheComponent
```

**Comment by vinyll** [comment]
Great. I like the idea and it would still be simple and explicit :)

In __.adminbro/.entry.js__:

```js
AdminBro.UserComponents = {}
import StringList from '../src/string-list'
AdminBro.UserComponents.StringList = StringList
```

However, when refreshing the admin page from the browser, the _.adminbro/.entry.js_ clears up and only displays:
```js
AdminBro.UserComponents = {}
```

Not great to workaround the issue, but quite a good news as it means the adminbro has control over that file.

Still wondering what can possibly go wrong 🤔

**Comment by wojtek-krysiak** [comment]
in admin-bro you will need to comment out line `node_modules/admin-bro/lib/backend/bundler/user-components-bundler.js#62`

let me know if that helps.

BTW: here is an example app with custom components: https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3 - can you download it and see if it works on your environment?

**Comment by vinyll** [comment]
Commenting out node_modules/admin-bro/lib/backend/bundler/user-components-bundler.js#62 stops resetting the entry file. However it still does not render the component.

https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3 works smoothly out of the box. Changing the component also updates the entry file and displays accordingly.

I guess I'll need to work from what works merging [my existing project](https://github.com/etceterra/naturapeute/blob/master/src/admin.mjs#L42) with the [working example](https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3).

BTW the JSCasts-episodes with AdminBro look great! :)

**Comment by wojtek-krysiak** [comment]
thanks - so closing this issue for now - fingers crossed :)

**Comment by Chukstart** [comment]
> Commenting out node_modules/admin-bro/lib/backend/bundler/user-components-bundler.js#62 stops resetting the entry file. However it still does not render the component.
> 
> https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3 works smoothly out of the box. Changing the component also updates the entry file and displays accordingly.
> 
> I guess I'll need to work from what works merging [my existing project](https://github.com/etceterra/naturapeute/blob/master/src/admin.mjs#L42) with the [working example](https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3) to be able to report more exactly what is blocking.
> 
> BTW the JSCasts-episodes with AdminBro look great! :)

This is very outdated

**Comment by ddresch** [comment]
> This is very outdated

Is there a current example how to implement custom components using `import`?

**Comment by kavyamfluid** [comment]
> Commenting out node_modules/admin-bro/lib/backend/bundler/user-components-bundler.js#62 stops resetting the entry file. However it still does not render the component.
> 
> https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3 works smoothly out of the box. Changing the component also updates the entry file and displays accordingly.
> 
> I guess I'll need to work from what works merging [my existing project](https://github.com/etceterra/naturapeute/blob/master/src/admin.mjs#L42) with the [working example](https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3) to be able to report more exactly what is blocking.
> 
> BTW the JSCasts-episodes with AdminBro look great! :)

can you share the login credentials to run the app
