### ISSUE TITLE
"Cannot Get /" after the admin login

### ISSUE THREAD

**Issue by andreashp96** [SoftwareBrothers/admin-bro#455]
Today I have watched the tutorial of yours on Youtube and I have to admit, it helps so much. But something bothers me when I logged my admin account as exactly shown on the tutorial: 

The first try -- which included this code:
const AdminBro = require('admin-bro');
const AdminBroExpress = require('admin-bro-expressjs');
const mongoose = require('mongoose');
const AdminBroMongoose = require('admin-bro-mongoose');
AdminBro.registerAdapter(AdminBroMongoose);
const adminBro = new AdminBro({
    databases: [mongoose],
    rootPath: '/admin',
});
const router = AdminBroExpress.buildRouter(adminBro);
module.exports = router;
works just fine.

Now going through the second phase as exactly done as the tutorial, added with this code:

const ADMIN = {
email: process.env.ADMIN_EMAIL || 'admin@example.com',
password: process.env.ADMIN_PASSWORD || 'lovejs',
}

const router = AdminBroExpress.buildAuthenticatedRouter(adminBro, {
        cookieName: process.env.ADMIN_COOKIE_NAME || 'admin-bro',
        cookiePassword: process.env.ADMIN_COOKIE_PASS || 'supersecret',
        authenticate: async(email, password) => {
           if(email === ADMIN.email && password === ADMIN.password){
               return ADMIN;
           }
           else {
               return null;
           }
       }
   });

After I logged in, the error occurs and such in the lines of: "Error: You probably used old `body-parser` middleware, which is not compatible with admin-bro-expressjs. In order to make it work you will have to 1. move body-parser invocation after the admin bro setup like this:" etc. etc.

And when I get back to the last phase I executed where it was successful, the end message shows, "CANNOT GET /".

I have no idea for this solution. Should I create a new admin js or restarting a new one since localhost 5000 writes "cannot get /"? Please help!

**Comment by andreashp96** [comment]
at any rate, here's written on the app.js about the "old" middleware

app.use(bodyParser.urlencoded({
    extended: true
}));

app.use(bodyParser.json());

**Comment by wojtek-krysiak** [comment]
hi - so you do you use `body-parser` package in your code?

**Comment by andreashp96** [comment]
yes, I used body parser on my app (app.js),
at any rate, here's written on the app.js (not on the admin.js) about the "old" middleware:

app.use(bodyParser.urlencoded({
extended: true
}));

app.use(bodyParser.json());

**Comment by andreashp96** [comment]
Never mind, I forgot the localhost:5000/admin, should've put it instead of localhost:5000
