### ISSUE TITLE
Not able to import socket.io-client

### ISSUE THREAD

**Issue by the-deadshot** [SoftwareBrothers/admin-bro#456]
I am making a custom dashboard and not able to import any external dependency. How am I supposed to do that?

> 'socket.io-client' is imported by my-dashboard-component.jsx, but could not be resolved – treating it as an external dependency

Thank you

**Comment by wojtek-krysiak** [comment]
you have to add this `/socket.io/socket.io.js` [assets.scripts](https://adminbro.com/AdminBroOptions.html#assets) in AdminBroOptions and serve it by your HTTP server (express):

**Comment by the-deadshot** [comment]
I am new in react js can you please tell me how to use that in .jsx file

**Comment by MexsonFernandes** [comment]
```
import { AdminBroOptions } from 'admin-bro

const options: AdminBroOptions = {
....
    assets: {
          scripts: [
           'https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js'
           ]
     }
}
```
