### ISSUE TITLE
Case insensivity search

### ISSUE THREAD

**Issue by bartoszhernas** [SoftwareBrothers/admin-bro#457]
**Describe the problem feature solves**
When searching for model in our DB, sometimes email is written with upper cases in DB, but when searching for it, admin-bro searches for exact match

**Describe the solution you'd like**
Best: option to configure filters and searching per resource type.

**Describe alternatives you've considered**
I considered changing source of adminbro-sequelize to use Op.iLike

**Acceptance criteria**
searching for "AbC" should match records with "ABC"

**Comment by bartoszhernas** [comment]
adding 
```
    "postinstall": "cd ./node_modules/admin-bro-sequelizejs/src/utils/ && cp convert-filter.js convert-filter.js.bak && sed 's/Op.like/Op.iLike/g' convert-filter.js.bak > convert-filter.js",
```
to package.json is a possible fix for sequelize users. I also made a PR in adminbro sequelize repo

**Comment by wojtek-krysiak** [comment]
its already merged to @admin-bro/sequelize
