### ISSUE TITLE
Show/Hide models in the sidebar based on user's roles

### ISSUE THREAD

**Issue by etahoon** [SoftwareBrothers/admin-bro#458]
it's a common scenario where we need to show/hide a list href from a sidebar based
on Role-Based Access Control 

I can implement this feature if you give me a guide for it .

thank you for this awesome app

**Comment by wojtek-krysiak** [comment]
hi @etahoon - you will need to implement an `isAccessible` method for a list action: https://adminbro.com/Action.html#isAccessible - return false when currentAdmin cannot see it. Also you might want to do the same for `edit`, `delete`, `bulkDelete` and new actions
