### ISSUE TITLE
Cannot read property 'toJSON' of null for new record on joint table

### ISSUE THREAD

**Issue by ccouturesitespect** [SoftwareBrothers/admin-bro#469]
**Describe the bug**
I am getting an error when attempting to create a record 

**Installed libraries and their versions**

    "admin-bro": "^2.3.1",
    "admin-bro-expressjs": "^2.0.5",
    "admin-bro-sequelizejs": "^0.4.2",

**To Reproduce**
1. Attempt to make a joint table record with valid foreignKey ids

**Expected behavior**
A new record should be created.

**AdminBroOptions with schema**
```
// Client model
module.exports = (sequelize, DataTypes) => {
	const Client = sequelize.define('Client', {
		siteId: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		name: {
			type: DataTypes.STRING,
			allowNull: true,
		},
	}, {
		charset: 'utf8mb4',
		collate: 'utf8mb4_general_ci',
	});
	Client.associate = (models) => {
		Client.belongsToMany(models.JWTConfig, {
			through: 'ClientsToJWTConfig',
			foreignKey: 'clientId'
		});
	};
	return Client;


module.exports = (sequelize, DataTypes) => {
	const JWTConfig = sequelize.define('JWTConfig', {
		name: {
			type: DataTypes.STRING,
			allowNull: false,
		},
	}, {
		charset: 'utf8mb4',
		collate: 'utf8mb4_general_ci',
	});


	JWTConfig.associate = (models) => {
		// JWTConfig.getClients()
		JWTConfig.belongsToMany(models.Client, {
			through: 'ClientsToJWTConfig',
			foreignKey: 'jwtConfigId'
		});
	};

	return JWTConfig;
};

// joint table (if it matters)
module.exports = (sequelize, DataTypes) => {
	const ClientsToJWTConfig = sequelize.define('ClientsToJWTConfig', {}, {
		charset: 'utf8mb4',
		collate: 'utf8mb4_general_ci',
		timestamps: false,
	});
	return ClientsToJWTConfig;
};

```
//adminbro options for the ClientsToJWTConfig resource

```
		{
			resource: ClientsToJWTConfig,
			options: {
				listProperties: clientToJWTProperties,
				editProperties: clientToJWTProperties,
				showProperties: clientToJWTProperties,
				properties: {
					clientId: {},
					jwtConfigId: {},
				},
				actions: {
					new: {
						before: async (request) => {
							console.log(request);
							return request;
						},
					},
				},
			},
		},

```

All indicators point at the fact that building the resource is failing in the `new-action` but I don't have any insights as to why. Doing a `ClientsToJWTConfig.build(request.payload).save()` in the `before` hook works (ie. the record actually makes it to the DB). What is the `new-action` handler doing that I'm not seeing? Should I be fashioning my model(s) differently so admin-bro can correctly create a joint table record?

Thanks for looking!

**Comment by wojtek-krysiak** [comment]
1. currently all resources in AdminBro has to have an id property which is autoincremented.
2. also AdminBro doesn't support (out of the box) many to many relationships :(

**Comment by marcoroganovic** [comment]
Hi, is there maybe some update about this issue? 

@wojtek-krysiak here you have said that is not supported out of the box, what can we do to make this work?

**Comment by wojtek-krysiak** [comment]
you can override the handler of new action (edit probably as well):

```
actions: {
  new: {
    handler: async(request, response, context) => {
     // code
    }
  }
}
```

original new action handler: 

https://github.com/SoftwareBrothers/admin-bro/blob/fabd7b6c4fad3cb628d76ba630a3907230394f13/src/backend/actions/new-action.ts#L27-L56

in line 30 you just need to: ClientsToJWTConfig.build(request.payload).save()

and then you have to convert sequelize model to BaseRecord like this

```
const record = resource.build(modelParams)
```

and in the response to RecordJSON: 

```
return {
   record: record.toJSON(currentAdmin)
}
```

both current admin and resource are in the context of the action

**Comment by ishan28mkip** [comment]
I am getting the same bug, I think this should not be a default behaviour as lot of people, me included, would be using uuid as id and it fails for uuid

**Comment by Unforgiven-wanda** [comment]
@wojtek-krysiak 
```
currently all resources in AdminBro has to have an id property which is autoincremented.
also AdminBro doesn't support (out of the box) many to many relationships :(
```

Is this still true?

**Comment by wojtek-krysiak** [comment]
yes

**Comment by wojtek-krysiak** [comment]
there is a task about Ids being not sequential - closing this one in favour of that: #544
