### ISSUE TITLE
Move the quill.js library locally

### ISSUE THREAD

**Issue by jzyds** [SoftwareBrothers/admin-bro#470]
Thanks for providing a very useful framework.

In some countries, access to quill.js CDN will be very slow, so can we change the online access to local?

**Comment by wojtek-krysiak** [comment]
what I did is I made quill only loading whey you use a `richtext` field. If you don't quill wont be loaded.

Furthermore, quill integration assumes that quill script should have the id='quill-script-tag' if it's not preset it is loaded when users want's to edit field for the first time.

So you can override how qull is loaded by simply writing custom component which creates `quill-script-tag` on document load:

```
// somewhere in the code:
AdminBro.bundle('./my-quill-override')

// .my-quill-override.jsx

const loadQuill = () => {
  const id = 'quill-script-tag'
  const script = window.document.createElement('script')

  // change that to your local file
  script.src = 'https://cdn.quilljs.com/1.3.6/quill.js'

  script.async = true
  script.defer = true
  script.id = id
  script.addEventListener('load', () => {
    console.log('quill loaded')
  })

  const style = window.document.createElement('link')
  style.rel = 'stylesheet'
  style.type = 'text/css'
  // change that to your local file
  style.href = 'https://cdn.quilljs.com/1.3.6/quill.snow.css'

  window.document.body.appendChild(script)
  window.document.body.appendChild(style)
}

window.document.addEventListener('DOMContentLoaded', loadQuill, false)

// it has to have a default export
export default () => null
```
