### ISSUE TITLE
Notice Message

### ISSUE THREAD

**Issue by KasimBasil** [SoftwareBrothers/admin-bro#478]
Hi, thank you for your great work, you're really saving us a lot of time.

This is not an issue at all, I just need your help very much. I'm working on a project (using express) and using admin bro and I need a custom handler for New action for my Admins model to create new admins and hash their password using passport, so I need to return an error to the admin (UI feedback) if something went wrong in the front-end form like a validation error or the user inputs a password shorter than 8 characters, in a normal route I should just `return res.json({error message})`,
so how can I achieve the same result using admin bro custom action handler?

like : 
`if (req.payload.password.length < 8) {
   return (the error handling code goes here)
}`

in the admin bro documentation, u mentioned to do such a thing we should use notice message in the action response, but I tried a lot of things and also read the source code and searched the internet and all issues in GitHub related to admin bro and I can't figure out a way to do it :(.

I'm sorry I'm just new to admin bro and I like it very much and I really need your help.

**Comment by wojtek-krysiak** [comment]
@KasimBasil - glad you like it :). I recently published a screencast about hashing password in AdminBro - there is a link: https://www.youtube.com/watch?v=wOSPDtvJcyQ I covers errors handling.

**Comment by KasimBasil** [comment]
@wojtek-krysiak Thank you for your replay, I did it by using
`if (password.length < 8) {
      return {
                  record: { errors: { password: { message: 'Password should be at least 8 characters', type: 'required' } } },
                  notice: { message: translateMessage('thereWereValidationErrors'), type: 'error' }}`

but now I need to redirect to the Admin resource List page after the record is successfully created using redirectUrl but it's not working at all there is no response, (I checked in the network tab) but the request status is pending, although the record is created in the database but I can't redirect, my code,
`if (user) {
   console.log(user)
   return { redirectUrl: '/dashboard/manager/resources/Admin' }
 }`

I can see the log, so the record is successfully created but why the redirect isn't working? 
the URL I provided is 100% working.
