### ISSUE TITLE
How to Integrate GraphQL Api With AdminBRo

### ISSUE THREAD

**Issue by harsh-solutelabs** [SoftwareBrothers/admin-bro#481]
Is there any way to integrate graphql API with the admin panel?

**Comment by wojtek-krysiak** [comment]
you would need to create a custom adapter which implements BaseResource. Take a look at how admin-bro-mongoose is done: https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/resource.js

then you can pass this resource to options like this:
```
const MyResource = require('path-to-my-resource')
```

**Comment by harsh-solutelabs** [comment]
How I can use that graphql API in a custom component because to call that mutation I want to wrap the custom component with Appollo server?

**Comment by wojtek-krysiak** [comment]
Unfortunately, I don't have any experience with apollo and react so I cannot help you :(

**Comment by HeetGosaliya** [comment]
**client.jsx**
`
import ApolloClient, { InMemoryCache } from 'apollo-boost';
export default new ApolloClient({
  headers: {
 Authorization : 'Bearer token'
  uri: 'some endpoint of graphql',
  cache: new InMemoryCache(),
});

`
**dashboard.jsx**
`
import React from 'react';
import Demo from './demo';
import { ApolloProvider } from 'react-apollo';
import client from './client';

const Dashboard = props => {
  return (
    <ApolloProvider client={client}>
      <Demo />
    </ApolloProvider>
  );
};
export default Dashboard;
`
**demo.jsx**

`
import React from "react";
import {  useQuery } from 'react-apollo';
const Demo = props => {
const { data, loading, error } = useQuery(SOME_QUERY);
if(data){
console.log(data);
}
  return (
   <p>Hello World!</p>
  );
};
export default Dashboard;
`

**Comment by HeetGosaliya** [comment]
**client.jsx**
```
import ApolloClient, { InMemoryCache } from 'apollo-boost';
export default new ApolloClient({
  headers: {
    Authorization:'Bearer sometoken'
  },
  uri: 'graphql end point',
  cache: new InMemoryCache(),
});

```
**dashboard.jsx**

```
import React from 'react';
import Demo from './demo';
import { ApolloProvider } from 'react-apollo';
import client from './client';

const Dashboard = props => {
  return (
    <ApolloProvider client={client}>
     <Demo />
    </ApolloProvider>
  );
};
export default Dashboard;


```
**demo.jsx**

```
import React from "react";
import {useQuery} from "react-apollo";

const Demo = props => {
const {data,loading,error} = useQuery(SOME_QUERY);
if(data){
console.log(data);
}
return (
     <p>Hello world</p>
);
};
export default Demo;

```

**Comment by wojtek-krysiak** [comment]
we have hasura integration in the backlog #655 (WIP)
