### ISSUE TITLE
image, film, link for wysiwyg(quilljs)

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/admin-bro#483]
Hello,

thanks for amazing admin panel, neither the wysiwyg editor nor the admin panel itself does not have image upload functionality which is vital.On the other hand, the editor lacks some features like image, film and link functionality. is there a way to add these functionalities to my panel ? 

thanks for any assistance,

**Comment by Amixengineer** [comment]
Hi once again, I have used DropZone and it works properly thanks for great docs but I still think that film , link and image for editor is a must would be appreciated for any help

**Comment by wojtek-krysiak** [comment]
Hi @Amixengineer - glad you like it so far :)

Regarding the quill editor - currently there is no easy way of modifying its behavior via admin-bro-options. The only thing you can do right now is to write your own edit component for your property (https://adminbro.com/tutorial-customizing-resources.html - section: `{ [propertyName].components } property appearance`)

original quill component [is here](https://github.com/SoftwareBrothers/admin-bro/blob/master/src/frontend/components/property-type/richtext/edit.tsx) - you can use it as a starting point.

**Comment by Amixengineer** [comment]
thanks for your replay

look here I have copied content from a webpage which have some linking words onto them and pasted to the editor. magically the links for the words remained!!!!!!!!

<img width="1059" alt="Screen Shot 1399-03-28 at 13 45 01" src="https://user-images.githubusercontent.com/34276557/84879559-9e945a80-b0a0-11ea-9721-1d0ddea973bc.png">

**Comment by Amixengineer** [comment]
https://www.youtube.com/watch?v=7WtKcFqJHho&t=320s

thanks for comprehensive explanation of file upload.

**Comment by wojtek-krysiak** [comment]
np - glad you liked it
