### ISSUE TITLE
custom Fonts for quillsjs

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/admin-bro#489]
Hello there, 

Is it possible to add my own RTL fonts to the toolbar option of quillsJs in AdminBro?

thanks for any assistance,

**Comment by wojtek-krysiak** [comment]
you will need to write your own edit component which render quill with this option (if there is any option for RTL in quill)

**Comment by Amixengineer** [comment]
Thanks a lot for the reply,

Although I am new to react, I could write a component .tsx for to render quill.
<img width="1145" alt="Screen Shot 1399-04-04 at 16 10 26" src="https://user-images.githubusercontent.com/34276557/85549504-50013600-b635-11ea-9c25-e5c290524565.png">

but something is going wrong. As soon as I type a letter or do an action like removing other field's text the quill toolbar gets incremented by one!!!!!!

<img width="1094" alt="Screen Shot 1399-04-04 at 16 14 39" src="https://user-images.githubusercontent.com/34276557/85550135-e6355c00-b635-11ea-91cb-b521efa43554.png">



the following is my EDIT components:

``
import * as React from "react";
import Quill from "quill";

const EditFont = () => {

    var quill = new Quill('#editor', {
        modules: {
            toolbar: [
                [{ header: [1, 2, false] }],
                ['bold', 'italic', 'underline'],
                ['image', 'code-block']
            ]
        },
        theme: 'snow'
    });
    return (
        <div id="editor"></div>
    )
}

export default EditFont
``

**Comment by Amixengineer** [comment]
I solved the Problem I'll post it here for other programmers in a day and close this post

**Comment by Amixengineer** [comment]
I solved the above problem by changing to .jsx it works perfectly I can add and edit toolbar but when I would like to update or publish the data. It give back with validation Error message it seems to me it doesn't have any connection to DataBase.

I also have an error in my console log which says = "quill Invalid Quill container #editor"

<img width="1193" alt="Screen Shot 1399-04-04 at 17 22 46" src="https://user-images.githubusercontent.com/34276557/85559760-4086ea80-b63f-11ea-96db-420f4199079f.png">

```
import * as React from "react";
import Quill from "quill";

const EditFont = () => {
    var Font = Quill.import('formats/font');
    // We do not add Aref Ruqaa since it is the default
    Font.whitelist = ['mirza', 'roboto', 'iranYekan'];
    Quill.register(Font, true);

    var quill = new Quill('#editor', {
        modules: { toolbar: '#toolbar' },
        theme: 'snow'
    });
    return (
        <div id="tollbox">
            <div id="toolbar">
                <button class="ql-bold">Bold</button>
                <button class="ql-italic">Italic</button>
                <select class="ql-font">
                    <option selected>Aref Ruqaa</option>
                    <option value="mirza">Mirza</option>
                    <option value="roboto">Roboto</option>
                    <option value="iranYekan">IranYekan</option>
                </select>
                <select class="ql-header">
                    <option value="1"></option>
                    <option value="2"></option>
                    <option value="3"></option>
                    <option value="4"></option>
                    <option selected></option>
                </select>
                <select class="ql-size">
                    <option value="small"></option>
                    <option selected></option>
                    <option value="large"></option>
                    <option value="huge"></option>
                </select>
                <button class="ql-underline"></button>
            </div>
            <div id="editor">
                <p>Hello World</p>
            </div>
        </div>
    )
}


export default EditFont
```


be grateful of any assistance,

**Comment by wojtek-krysiak** [comment]
basically in EditFont component you will have to handle onChange callback: 

```
const EditFont = (props) => {
  const { onChange } = props

  // your current code + invoke the onChange callback when quill changes content. Otherwise changes you do in the editor wont affect the database
}

you can take a look at the source code of the original quill implementation: https://github.com/SoftwareBrothers/admin-bro/blob/master/src/frontend/components/property-type/richtext/edit.tsx - it is done with regular class component but it should give you a good starting point.

**Comment by Amixengineer** [comment]
thanks a lot for hints I could get through of the problem.
