### ISSUE TITLE
Sequelize validation errors are not properly getting handled.

### ISSUE THREAD

**Issue by AKNiazi** [SoftwareBrothers/admin-bro#494]
I am using Admin Bro with Express and Sequelize.

    "admin-bro": "2.2.5",
    "admin-bro-expressjs": "2.0.4",
    "admin-bro-sequelizejs": "0.4.0",
    "sequelize": "5.21.7",

Admin Bro only handles isRequired validation gracefully for non foreign key attributes of a Model. Other validations return internet server error. Following are the validations which are not handled in my use case.

1. Unique Column Validation
2. If an attribute is a foreign key.

![validation-error](https://user-images.githubusercontent.com/4454540/85940789-0caa0e80-b938-11ea-8c09-62b0f60f3d1a.png)

In the above screenshot, mobile number should be unique, but it does not gracefully handle it and 500 is returned.

**Comment by wojtek-krysiak** [comment]
please write you schema definition for this particular field

**Comment by AKNiazi** [comment]
In model its

    mobile: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    }

In one migration, i added the column

     queryInterface.addColumn('users', 'mobile',{
          type: Sequelize.STRING,
          allowNull: false,
        })
and in a later migration i added the unique contraint as well.

     queryInterface.addConstraint('users', ['mobile'], {
        type: 'unique',
        name: 'users_mobile_unique_constraint'
      })

**Comment by leibowitz** [comment]
Not sure if this is related
https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/17

**Comment by wojtek-krysiak** [comment]
fixed with @admin-bro/sequelize@1.0.0-beta.3
