### ISSUE TITLE
published Boolean for articles

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/admin-bro#498]
Hello there,

I came across a functionality in adminBro-example-app articles (https://github.com/SoftwareBrothers/admin-bro-example-app/blob/master/admin/resources/article.js) which let admins to publish articles when they tick the box which is what I would like, I implemented but it does not work, does it?

**Comment by wojtek-krysiak** [comment]
it works: example for isAdmin boolean: https://github.com/SoftwareBrothers/admin-bro/blob/master/example-app/src/companies/company.entity.js#L30

**Comment by Amixengineer** [comment]
just to make clear for beginners. Use isAdmin with Boolean property into your model then wrap up you code into an IF statement 

if isAdmin === true {
// your logic goes here
}
else {
}


thanks a billion Wojtek
