### ISSUE TITLE
Sequelize hooks ignored

### ISSUE THREAD

**Issue by LucusWebsites** [SoftwareBrothers/admin-bro#503]
It seems that when you for example update an entity via admin-bro the hooks defined in sequelize are ignored, is this on purpose?

Versions I am using:
- admin-bro: 2.6.0
- admin-bro-sequelizejs: 0.5.1
- sequelize: 6.3.0

**Comment by wojtek-krysiak** [comment]
hmm - yes and no - we don't have a strict policy regarding hooks. In both sequelize and mongoose adapters they are not invoked, but there is a task for changing that (#105 ) so in the future it will change. I will add this task to the backlog so we will change how sequelize behaves as well

**Comment by LucusWebsites** [comment]
Thanks for the quick response @wojtek-krysiak  

It would be great if admin-bro triggers all hooks defined in sequelize, I am using admin-bro as a tiny extra layer on top of my app, not as the "core".

Also: keep up the great work, I am already falling in love with admin-bro :)

**Comment by wojtek-krysiak** [comment]
I just got the time to look at this issue again. Can you write which hooks are ignored? It seems that we use regular `create` and `update` command so they should be triggered.

**Comment by LucusWebsites** [comment]
I will take a look as soon as possible!

**Comment by LucusWebsites** [comment]
Sorry for the delay, but I just did some testing:

``` JavaScript

class Model extends Sequelize.Model {}

Model.init({
    ...
});

const hooks = ['beforeCreate', 'afterCreate', 'beforeUpdate', 'afterUpdate', 'beforeSave', 'afterSave', 'beforeDestroy', 'afterDestroy'];
for (const hookName of hooks) {
    Model.addHook(hookName, () => {
        console.log('Oh my, this sequelize hook was fired: ' + hookName);
    });
}

```

# Test results

### Add entity via adminbro:

Oh my, this sequelize hook was fired: beforeCreate
Oh my, this sequelize hook was fired: beforeSave
Oh my, this sequelize hook was fired: afterCreate
Oh my, this sequelize hook was fired: afterSave

### Add entity directly:

Oh my, this sequelize hook was fired: beforeCreate
Oh my, this sequelize hook was fired: beforeSave
Oh my, this sequelize hook was fired: afterCreate
Oh my, this sequelize hook was fired: afterSave

### Update entity via adminbro:

no hooks fired..

### Update entity directly:

Oh my, this sequelize hook was fired: beforeUpdate
Oh my, this sequelize hook was fired: beforeSave
Oh my, this sequelize hook was fired: afterUpdate
Oh my, this sequelize hook was fired: afterSave

### Delete entity via adminbro:

No hooks fired..

### Delete entity directly:

Oh my, this sequelize hook was fired: beforeDestroy
Oh my, this sequelize hook was fired: afterDestroy
