### ISSUE TITLE
custom search field

### ISSUE THREAD

**Issue by hvasc** [SoftwareBrothers/admin-bro#504]
Hi, I need customize sequelize's association property.
my resource has associate using belongsTo method to another models property.
It's good default component. but default search in select box's api is querying name property.
How can change search field?

**Comment by wojtek-krysiak** [comment]
The simples way would be to set [isTitle](https://adminbro.com/PropertyOptions.html#isTitle) to false for name property and set it to true to the property you would like to search for (it will also change what is displayed in a list and show views). If this is not the case there is a resource action called `search`. You can override it by calling:

```
/** @type ResourceOptions **/
options = {
  actions: {
    search: {
      handler: async (request, response) => {
        // write your implementation here
      }
    }
  }
}
```

Original search handler can be found here: https://adminbro.com/admin-bro_src_backend_actions_search-action.ts.html (line 28)

**Comment by hvasc** [comment]
thank you very much!
