### ISSUE TITLE
Sidebar resource parents sort order

### ISSUE THREAD

**Issue by LucusWebsites** [SoftwareBrothers/admin-bro#506]
Is it possible to force the sort order of sidebar resource parents? Other then with the order in which they are added?

I am using an autoloader to set the admin-bro resources automatically like this:

```
const adminBroResourceParents = {
    machines: {
        name: 'Machines',
        icon: 'Bot',
        sortOrder: 10 // <- something like this would be awesome
    },
    users: {
        name: 'Users',
        icon: 'User',
        sortOrder: 20 // <- something like this would be awesome
    },
    media: {
        name: 'Media',
        icon: 'Folders',
        sortOrder: 30 // <- something like this would be awesome
    }
}

adminbroResources = [ // filled via an autoloader
    {
        model: someSequelizeModel,
        options: {
            parent: adminBroResourceParents.media
        }
    }
]

new AdminBro({
    ...
    resources: adminbroResources
});

**Comment by cloudratha** [comment]
Couldn't you just sort the autoloader manually?

**Comment by LucusWebsites** [comment]
Sure something like that would be possible, but that would also kinda defeat the purpose of an autoloader.

But defining the resource parents in one place and setting the sort order there makes sense right?

**Comment by cloudratha** [comment]
I would say the general use case would prefer the order defined by the order in which they are added.

Parents aren't defined in one place, they are defined in each resource.
I think a better solution would be to have a top level grouping option that defines the structure, and the resource just references the group. So order can be inferred.

**Comment by wojtek-krysiak** [comment]
recently we added a feature which allows you to manually change the layout components of AdminBro. It can be done like this:

AdminBro.bundle('path-to-a-new-sidebar-component', 'SidebarResourceSection')

in this new component you can render whatever you like. This is the original implementation:
```
const SidebarResourceSectionOriginal: FC<SidebarResourceSectionProps> = ({ resources }) => {
  const groupedResources = groupResources(resources)

  return (
    <>
      {
        groupedResources
          .map(parent => (
            <SidebarParent parent={parent} key={parent.name} />
          ))
      }
    </>
  )
}
```

**Comment by wojtek-krysiak** [comment]
I don't think we will implement proposed `sortOrder: 20` because you can pass resources in the correct order or use the way to modify the sidebar as I described above. That is why I am closing this one.
