### ISSUE TITLE
Property comments in show/list/edit

### ISSUE THREAD

**Issue by LucusWebsites** [SoftwareBrothers/admin-bro#507]
**Describe the problem feature solves**
Some properties may require extra explanation when editing a resource.
Take for example a property "customUrl", the comment would be "Always start with a / and use only [a-z0-9-_]".

**Describe the solution you'd like**
The ability to add comments (maybe with translation support?) to a resource property.
The comment may differ per show/list/edit context.

**Describe alternatives you've considered**
Adding the comments via custom components.

**Acceptance criteria**
_List of checkpoints which has to be met to mark the issue as completed_

**Comment by wojtek-krysiak** [comment]
@michalniemiec-sb - it can be done by using

**Comment by wojtek-krysiak** [comment]
this can be done with the layout option in the show/edit action
