### ISSUE TITLE
Many to Many relationship

### ISSUE THREAD

**Issue by LucusWebsites** [SoftwareBrothers/admin-bro#508]
I looked around a bit, and I couldn't figure out wether showing relations of a resource is in the pipeline.
It would be awesome when you can define which relations you want to show per resource.

Hereby a brave attempt to visualize what I mean:

![image](https://user-images.githubusercontent.com/3696955/87037643-d5b3e280-c1ec-11ea-8fd0-e55ce545bd6d.png)

For one-to-many relations it would show a resource list.
For a one-to-one relation you might see the show page of the related resource, and a button to edit.

**Comment by LucusWebsites** [comment]
Also: ideally you would be able to nest resources infinitely.
For example: A user has one or more orders, a order has one ore more products, and so forth.

**Comment by wojtek-krysiak** [comment]
+1 for a brave attempt :) - we have a similar task in the backlog: #282 but leaving this one as it proposes more systematic solution

**Comment by leibowitz** [comment]
I've made an attempt at implementing a many-to-many component based on react-select. It's rather simple and works with basic cases, as far as I can tell. It is only for sequelizejs adapter at the moment.

Feel free to check it out and let me know what you think
https://gist.github.com/leibowitz/b94fc4eb2b8ab745267db99941757190

**Comment by wojtek-krysiak** [comment]
@leibowitz - since admin-bro@3.2 you can extract this to a separate feature :). So closing this one, leaving #282 open

**Comment by LucusWebsites** [comment]
@wojtek-krysiak Can you provide any details about this "feature"?

Is it on the roadmap or not at all?

**Comment by yuvapoojary** [comment]
Yes please give an example
