### ISSUE TITLE
remove reference properties value

### ISSUE THREAD

**Issue by hvasc** [SoftwareBrothers/admin-bro#515]
Hi, I want adding reference type component's remove button (assign null attribute for reference value)

can I customize admin-bro's default component?
otherwise can import reference type's edit component in my formgroup?

**Comment by leibowitz** [comment]
You can customise the [`edit reference`](https://github.com/SoftwareBrothers/admin-bro/blob/26c637829c5576bb7a221294343f6a78d8da2831/src/frontend/components/property-type/reference/edit.tsx) type

But I believe this would be best handled by passing [`isClearable`](https://react-select.com/props) to the [react-select](https://github.com/JedWatson/react-select) [`Select`](https://github.com/SoftwareBrothers/admin-bro/blob/26c637829c5576bb7a221294343f6a78d8da2831/src/frontend/components/property-type/reference/edit.tsx#L79-L88) component

**Comment by hvasc** [comment]
> You can customise the [`edit reference`](https://github.com/SoftwareBrothers/admin-bro/blob/26c637829c5576bb7a221294343f6a78d8da2831/src/frontend/components/property-type/reference/edit.tsx) type
> 
> But I believe this would be best handled by passing [`isClearable`](https://react-select.com/props) to the [react-select](https://github.com/JedWatson/react-select) [`Select`](https://github.com/SoftwareBrothers/admin-bro/blob/26c637829c5576bb7a221294343f6a78d8da2831/src/frontend/components/property-type/reference/edit.tsx#L79-L88) component when a field is nullable

thank you very much!

**Comment by leibowitz** [comment]
I meant this should be handled in the existing edit component, in my opinion. 

You can try sending a PR with a code change that checks the property (if nullable) and pass `isClearable` as props to the `Select` component in that case.

Alternatively you could just duplicate the whole component and use a version with `isClearable` added to the props. But that sounds like overkill

**Comment by hvasc** [comment]
> I meant this should be handled in the existing edit component, in my opinion.
> 
> You can try sending a PR with a code change that checks the property (if nullable) and pass `isClearable` as props to the `Select` component in that case.
> 
> Alternatively you could just duplicate the whole component and use a version with `isClearable` added to the props. But that sounds like overkill

thank very much. I'll try it

**Comment by wojtek-krysiak** [comment]
it duplicates #161
