### ISSUE TITLE
not accessing the same data for each admin 

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/admin-bro#516]
Hello there, 

I am trying to have restricted admins that can have access to their own resources. I mean Teacher A can not see Teacher's B online course or vice versa meanwhile full admin can see both teachers resources to manage them. Is that possible to handle through adminBro (Role-Based Access Control) ?
I went through adminBro docs and found something like isAccessible. is that the one that I am looking for ?
Lastly, the admin panel is going to have too many teachers that can only access to their own resources and can not see others resources is it possible to automate that or I should set it up for each teacher separately?
thanks for any suggestions,

**Comment by leibowitz** [comment]
If you have any questions, the best place to ask for them is on [slack](https://github.com/SoftwareBrothers/admin-bro#opensource-softwarebrothers-community) 

Issues should be kept for bugs

[`isAccessible`](https://adminbro.com/Action.html#isAccessible) can handle role based access control. 

As for multi-tenancy, up to you to decide. Read about the pros and cons.

**Comment by Amixengineer** [comment]
thanks a lot
