### ISSUE TITLE
Looking for an option to select rows and copy it into csv or excel

### ISSUE THREAD

**Issue by sharath-mallikarjuna** [SoftwareBrothers/admin-bro#517]
There's no option to select records and copy just like the remove option.

I want to export the records into an excel format or an option to download the shown records in any format also holds good.

**Comment by leibowitz** [comment]
Sounds like something that can be implemented quite easily via a custom bulk action
https://adminbro.com/tutorial-actions.html

**Comment by wojtek-krysiak** [comment]
I think it duplicates #322

**Comment by mohamednazmi1** [comment]
@leibowitz I truly did my best but I couldn't customize this feature! I'd appreciate any sort of guide.

**Comment by CarlosQ96** [comment]
Hello I am also on the same boat, really tried my best to get to implement this feature but couldn't. Is there any guide? Would appreciate it.
