### ISSUE TITLE
Bug when trying to search for mongoose.Schema.Types.Long field

### ISSUE THREAD

**Issue by iblessedi** [SoftwareBrothers/admin-bro#523]
I am using adminbro with Express and mongoose tools. I have one filed with type mongoose.Schema.Types.Long (https://www.npmjs.com/package/mongoose-long). When somebody tries to search for this field there is an error
_Error: Can't use $options with Long._

is there any way to search for Long field? Thanks.

**Comment by wojtek-krysiak** [comment]
I don't think so :( - I am looking at the code right now and we use this $options:

```
{
   autopopulate: false, skip: offset, limit, sort: sortingParam,
}
```

so it seems that this library doesn't allow you to sort or paginate, which is the basic requirement of AdminBro.
Since this won't be fixed, and I don't think we can find a workaround - I am closing this issue
