### ISSUE TITLE
Support for custom actions on collections

### ISSUE THREAD

**Issue by vladir95** [SoftwareBrothers/admin-bro#54]
Is there any planned support for custom actions on collections?

Example proposal:

- Add a `CollectionDecorator` base class or add a prop of `this.collectionActions` to `BaseDecorator`.
- Allow developer to define a custom form to show int the action, then the handler function that will be defined in `this.collectionActions` will get the params from the defined form. also override to Create new should be allowed. f.e:

Form definition for action:
```javascript
const fields = [
  {
    field: 'Business Name',
    description: 'Business Name.',
    type: 'Enum', // String, Number, Boolean, Enum or CustomHtml
    enums: ['hi', 'bb'],
    isRequired: true,
    customHtmlField: `<input ...>`
  }
...
]
```
Action Definition:
```javascript
const addNewBusinessAction = {
      id: 'publish',
      icon: 'fas fa-share',
      label: 'Publish',
      formFields: fields, //from the top example
      action: (request, response, data) => {
        // request.body Will be filled with form data with the fields defined above
        const { method } = request
        if (method === 'GET') {
          return 'Some content or form which you want to place here'
        }
        return 'PUBLISH ACTION WORKS'
      },
    }
this.collectionActions = [addNewBusinessAction]
```
- **UI**: a dropdown on top of the collection filled with the custom actions.

**Comment by wojtek-krysiak** [comment]
YES - we plan to do this next week.

**Comment by wojtek-krysiak** [comment]
Just updated admin-bro to the 0.5.0 version. It has custom actions for both resources and records.

Check out the example at https://admin-bro-example-app.herokuapp.com/admin/resources/user - there are both resource and record actions.

Documentation can be found here: https://softwarebrothers.github.io/admin-bro-dev/tutorial-05-actions.html
