### ISSUE TITLE
Spaces in the primary key do not allow you to edit that row

### ISSUE THREAD

**Issue by AeroNotix** [SoftwareBrothers/admin-bro#545]
Hi,

I have a primary key which is just a string, such as `"Foo And Bar"`. When I try to edit that row in the AdminBro UI I receive a 400 error.

**Comment by wojtek-krysiak** [comment]
Totally agree, there is a task in the backlog which is about this exact problem: #544

Right now there is no other way if fixing that otherwise than adding the second primary, sequential key. 

I will close this task since it duplicates it.
