### ISSUE TITLE
Custom auth method and login component (for Firebase Auth) 

### ISSUE THREAD

**Issue by ivawzh** [SoftwareBrothers/admin-bro#546]
**Describe the problem feature solves**

Hi, thank heaps for this awesome OSS.

I am trying to implement Firebase Auth with Admin Bro ExpressJs. 

Is this already a supported feature? If yes, can you please share with me some links or clues to the implementation?

**Describe the solution you'd like**

Ideally, I would like a landing login page with [FirebaseUI component](https://github.com/firebase/firebaseui-web). And then on the server-side, it statelessly decodes the auth token from either cookie or JWT header. 

Currently, I can see Admin Bro supports overiding components:

```ts
export declare type OverridableComponent = 'LoggedIn' | 'NoRecords' | 'SidebarResourceSection' | 'SidebarFooter';
```

But it doesn't support overriding Login Page. 

**Describe alternatives you've considered**

I am familiar with ExpressJS. It should be quite easy to implement something like

```ts
  app.all('*', decodeAuthTokenOrRedirectToLoginPage)

  function decodeAuthTokenOrRedirectToLoginPage() {
    ... 
    const claims = await firebase-admin.admin.auth().verifyIdToken(idToken)
    ...
  }
```

But I am not sure what is the best way to integrate with Admin Bro's existing component bundle and auth workflow. 

**Acceptance criteria**

1. Firebase Auth login page
1. Cookie support, so that doesn't require re-login on every fresh request.
1. Redirect to login page when users are not logged in.

Thanks in advanced =D

**Comment by ivawzh** [comment]
Hey @wojtek-krysiak , I have just tried it a bit more. I don't think it's possible to wire Firebase Auth at the moment.

As currently from `buildAuthenticatedRouter(admin: Admin, auth: { authenticate: (email: string, password: string) => unknown }` , `authenticate` is hardcoded to require `email` and `password` on https://github.com/SoftwareBrothers/admin-bro-expressjs/blob/507c6ca99d3bd8c20f29b47eeb8a7cbf82b560a9/plugin.js#L198.

**Comment by wojtek-krysiak** [comment]
we use it (firebase) in SoftwareBrothers with one of our clients.

don't use `buildAuthenticatedRouter()` - you have to write your own implementation. You can take a look at the source code (it is super simple: https://github.com/SoftwareBrothers/admin-bro-expressjs/blob/master/plugin.js#L141)

Example: this is how your `firebaseRouter()` function should look like (modified buildAuthenticatedRouter)

```

router.use(session()) // with your session options

const router = express.Router()

router.get('/login', () => {
  // here you have to render login page with firebase UI
})

router.post('/login', () => {
  // here you have to take firebase token, validate it and store to the `req.session.adminUser`. It has to be of type: https://adminbro.com/AdminBro.html#CurrentAdmin so you can have avatar, etc.
// and then redirect to /admin (assuming that this is your )
})

// this is copied from authenticatedRouerCode
router.use('(req, res, next) => {
    if (AdminBro.Router.assets.find(asset => req.originalUrl.match(asset.path))) {
     // all static assets are available by default
      next()
    } else if (req.session.adminUser) {
      next()
    } else {
      // If the redirection is caused by API call to some action just redirect to resource
      const [redirectTo] = req.originalUrl.split('/actions')
      req.session.redirectTo = redirectTo.includes(`${rootPath}/api`) ? rootPath : redirectTo
      req.session.save((err) => {
        if (err) {
          next(err)
        }
        res.redirect(admin.options.loginPath)
      })
    }
  })

router.get(logoutPath, async (req, res) => {
    req.session.destroy(() => {
      res.redirect(admin.options.loginPath)
    })
  })

// and finally you add adminbro to this router
buildRouter(admin, router) // you can add formidableOptions if any as a 3rd argument

```

PS: in case of problems let me know on slack - will be faster there.
