### ISSUE TITLE
What is the .adminbro directory created?

### ISSUE THREAD

**Issue by giorgosera** [SoftwareBrothers/admin-bro#549]
After installing `admin-bro` I realized that a new dot file was created at `.adminbro`. I couldn't find any reference to it in the documentation.

Is this something we should commit to version control or we can add it to an ignore file?

Thanks

**Comment by SimonB407** [comment]
@giorgosera It's generated by AdminBro during bundle process. It's used mainly to pair custom user components with AdminBro, to be visible by Admin Panel. It can be ignored from the repo without any consequences.
