### ISSUE TITLE
Custom component `onChange` does not update inputs since v3

### ISSUE THREAD

**Issue by FelixGaebler** [SoftwareBrothers/admin-bro#561]
**Describe the bug**
Since version 3.0.0 the inputs are not updated when using `onChange` in custom components.

**Installed libraries and their versions**

* admin-bro@3.0.1

**To Reproduce**
1. Clone https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3
2. npm i admin.bro@2.9.0
3. Works!
4. npm i admin.bro@latest
5. Does not work :(

**Expected behavior**
Inputs should be updated

Im searching for the code thats responsible and will add it as a comment as soon as I find it.

**Comment by FelixGaebler** [comment]
Maybe its not even the best way how the example does it :) I was wondering if the  
`record.update({ profilePhotoLocation: `/${filePath}` });`
from the provided example is clean code. I believe its a workaround to retrieve the id which it will get in the database first, but you should store the path without the id or generate one syntheticly...

Still the onChange function is useful.

**Comment by FelixGaebler** [comment]
https://github.com/SoftwareBrothers/admin-bro/commit/82f6db47ec8a5ea18757880a20c00af79659c041#diff-af02091d5e06fb98c84148caf84d2052
this might be the reason why... but its hard to debug bundles packages for me

**Comment by FelixGaebler** [comment]
The onBlur might be responsible since the component is not a casual text input

**Comment by wojtek-krysiak** [comment]
fixed in 3.1.0
