### ISSUE TITLE
change PropertyOptions#isTitle to simple ResourceOptions#title

### ISSUE THREAD

**Issue by zoftify** [SoftwareBrothers/admin-bro#567]
First of all, thank you guys for maintaining such a great product! Truly impressive.

Can you please clarify how could we properly map the reference to the table?
1. We use sequelize adapter
2. We have 2 tables: **brands** (`id`, `name`, `country_id`) and **countries** (`id`, `country`)
3. The tables are linked (as well as in the sequelize model) by `brands.country_id = countries.id`
4. In the table (see screenshot) we'd like to show the country name (`country` column) of the countries table instead of the `country_id` (as it's shown now)

How can we do that?

Thanks a lot in advance!

![image](https://user-images.githubusercontent.com/56393200/91548257-cec46900-e92d-11ea-9c74-db79874016f5.png)

**Comment by wojtek-krysiak** [comment]
in `country` resource set `isTitle` for `country` column to `true` and for `id` column to `false`: https://adminbro.com/PropertyOptions.html#isTitle

**Comment by zoftify** [comment]
Hi @wojtek-krysiak, thanks a lot for the response. It worked!
But can you please clarify if we could have a combined title: "country (id)", for example: "Poland (5)"

**Comment by wojtek-krysiak** [comment]
I think we will need to add this to the core. Right now it is not possible in a simple way

So the task would be to change from PropertyOptions#isTitle to simple ResourceOptions#title which will return whatever you like. I will change this task name to not forget about this idea.

**Comment by wojtek-krysiak** [comment]
or no - I will create another task and close this one :)

**Comment by zoftify** [comment]
@wojtek-krysiak  Great, thank you! :)
