### ISSUE TITLE
misspelling in Docs 

### ISSUE THREAD

**Issue by Chukstart** [SoftwareBrothers/admin-bro#569]
[https://adminbro.com/tutorial-installation-instructions.html](https://adminbro.com/tutorial-installation-instructions.html)
it reads >> 01. Install the **fremework** plugin
sorry for being so nit picky

**Comment by wojtek-krysiak** [comment]
Don't be sorry. Thank you so much!!!. We need lots of help with the docs so feel free to post any issue you will see.

I will fix this today because I will release docs for @admin-bro/koa

**Comment by Chukstart** [comment]
I could try and look for more and post them under one issue

**Comment by wojtek-krysiak** [comment]
cool. Even you can make a PR :)

We hold all our docs here: https://github.com/SoftwareBrothers/admin-bro-dev

**Comment by wojtek-krysiak** [comment]
fixed
