### ISSUE TITLE
Navbar broken beyond width: 1324

### ISSUE THREAD

**Issue by ArcaneDiver** [SoftwareBrothers/admin-bro#577]
**Describe the bug**
The navbar doesn't display beyond width: 1324. This bug persist even in the demo version on the website. [Demo](https://admin-bro-example-app-staging.herokuapp.com/admin)

**To Reproduce**
1. Go to 'https://admin-bro-example-app-staging.herokuapp.com/admin'
2. See error

**Expected behavior**
Sould let you see content but if width is more than 1324 there is no burger menu but with a width value less than 1324 a burger menu appears.

**Screenshots**
Width: 1324
![Cattura](https://user-images.githubusercontent.com/47637591/92138727-0d1ac600-ee0f-11ea-8c7d-feb97b8c2eca.JPG)
Width: 1323
![Cattura](https://user-images.githubusercontent.com/47637591/92138832-32a7cf80-ee0f-11ea-89ae-74abb5602e42.JPG)

**Comment by wojtek-krysiak** [comment]
thanks. Which browser and OS?

**Comment by ArcaneDiver** [comment]
Sorry, Chrome: 85.0.4183.83 OS: Windows 10 Home

**Comment by ArcaneDiver** [comment]
I close this issue because i just discovered that the problem was an extention which introduce a class called hidden that was in conflict with sidebar hidden class
