### ISSUE TITLE
How to create pages menu which when I click open an external page

### ISSUE THREAD

**Issue by empeje** [SoftwareBrothers/admin-bro#589]
**Describe the problem feature solves**

I have a use case where I need to create menu which opens to the external page. How I do that in Admin bro?

**Describe the solution you'd like**
A simple API to create menu and include the link or admin bro path

**Comment by wojtek-krysiak** [comment]
you have 2 optons:
* one is to create a simple page (https://adminbro.com/AdminBroOptions.html#pages), but there you will have to create a component rendering it there is no way of linking to external URL right now)
* the second is to override footer component:

```
// somewhere in the code
AdminBro.bundle('./your-new-component', 'SidebarFooter')
```

and your-new-component will appear on the bottom of the sidebar - where you can put whatever you like

hint: Another option would be to override an entire `SidebarResourceSection` where you can order menu as you like

**Comment by empeje** [comment]
@wojtek-krysiak an possibilities to add a custom sub-menu in the sidebar? Is the sidebar already extendable?

**Comment by wojtek-krysiak** [comment]
yes. take a look at AdminBro.bundle. as the second argument you can pass component name which you want to override. Not all components are overridable. In frontend/utils/overridable-component.ts there is a list of component names. This not documented well yet

**Comment by Coinhexa** [comment]
Any update to this issue or are we still stuck with the same limitation?
