### ISSUE TITLE
i18n config is overriden by admin-bro

### ISSUE THREAD

**Issue by adamgyulavari** [SoftwareBrothers/admin-bro#592]
**Describe the bug**
If admin-bro is initialized the i18n config of the host application is ignored and only the locales and languages coming from this library are present

**Installed libraries and their versions**

* admin-bro@3.2.5
* admin-bro-expressjs@3.0.0
* admin-bro-sequelize@1.1.0
* i18next@19.7.0
* i18next-fs-backend@1.0.7
* i18next-http-middleware@3.0.5

**To Reproduce**
1. Init npm project
2. install dependencies:
```json
"dependencies": {
    "@admin-bro/express": "^3.0.0",
    "admin-bro": "^3.2.5",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "i18next": "^19.7.0",
    "i18next-fs-backend": "^1.0.7"
  }
```
3. setup basic config and locals and run it:
```js
onst i18next = require('i18next')
const Backend = require('i18next-fs-backend')

i18next.use(Backend).init({
  // initImmediate: false,
  lng: 'en',
  fallbackLng: 'en',
  preload: ['en'],
  ns: ['translation'],
  defaultNS: 'translation',
  backend: {
    loadPath: 'locales/{{lng}}/{{ns}}.yml'
  }
}, (err, t) => {
  if (err) return console.error(err)
  console.log('i18next is ready...')
  console.log(t('welcome'))
  console.log(t('welcome', { lng: 'de' }))
})


const AdminBro = require('admin-bro')
const AdminBroExpress = require('@admin-bro/express')

const express = require('express')
const app = express()

const adminBro = new AdminBro({
  databases: [],
  rootPath: '/admin',
})

const router = AdminBroExpress.buildRouter(adminBro)

app.use(adminBro.options.rootPath, router)

app.get('/', (req, res) => {
  res.send(i18next.t('welcome'))
})
```

**Expected behavior**
The i18next backend is loaded, translations are loaded, translated message is displayed instead of the key in the callback and on the `/` endpoint

I don't think the rest is necessary, maybe I'm just missing something, but basically I'm just copying and pasting the Getting started section from `i18next` and `admin-bro`. I think this is expected to work.

I really love this project, so I wouldn't want to drop it's integration from my project, but I also need to use translations :)
Thanks for the help

**Comment by adamgyulavari** [comment]
here's a sample project:
https://github.com/adamgyulavari/admin-bro-bug

**Comment by wojtek-krysiak** [comment]
man thanks for that - this can be really an issue. We have a task in the backlog (https://github.com/SoftwareBrothers/admin-bro/issues/535) which changes locale base on the current user (right now there is a limitation for only one locale per app, so all users always see one language). I think that this task can be fixed along the way. But its quite complicated and I don't have this in the v3.2 backlog. When do you need this?

**Comment by adamgyulavari** [comment]
haha, well as soon as I can :)
I'll try to come up with a dirty hack somehow

**Comment by wojtek-krysiak** [comment]
I was thinking about: do you have some deadline with your project :) ?, or can wait like 2 weeks - because We have a couple of other exciting things we are working on right now in milestone v3.3.

**Comment by adamgyulavari** [comment]
I need to launch the project in exactly 2 weeks :)
either way I think I'll have to go around it somehow. I'm trying to fix it in the dev environment myself (I think it shouldn't be so hard, because there's a check for `in18next.isInitialized` and there's an `addResourceBundle` that can be used instead of `init`

**Comment by adamgyulavari** [comment]
hm. interestingly, inside the dev environment's example project it works without modifying anything (just adding the i18next config to the example `express/index.js`)
