### ISSUE TITLE
Add an option for custom pages (user member access resource)

### ISSUE THREAD

**Issue by s7web** [SoftwareBrothers/admin-bro#594]
**Describe the problem feature solves**
Standard we have option to define pages by member role,

**Describe the solution you'd like**
 It would be great to have same functionality to custom pages.

**Comment by johnyvelho** [comment]
hi @s7web. not sure exactly what you are looking for, but maybe this can solve your problem: https://github.com/johnyvelho/admin-bro-users-permissions

@wojtek-krysiak would you think that would be good to transform this package into a native solution for adminbro? I will start work on it, then I will create an Issue better described about this feature.

**Comment by wojtek-krysiak** [comment]
wow. this is awesome. after 3.3 we plan to run a page where plugin autors  could publish their plugins, this id definitely place for that. Untill then i can link this in the docs. Just let me know

**Comment by johnyvelho** [comment]
that's super cool.
sure, you can definitely link it in the docs, certainly will be helpful for a lot of people. and in case you decide to have it natively on AdminBro, I would be glad to help you move it, just get in touch.
