### ISSUE TITLE
customize dashboard

### ISSUE THREAD

**Issue by soheilgk** [SoftwareBrothers/admin-bro#597]
hi how can i customize dashboard?!
i couldn't find anything

**Comment by wojtek-krysiak** [comment]
yes we have to improve the docs regarding this one. But basically you have to read:
- https://adminbro.com/tutorial-writing-react-components.html there is a dashboard section
- an actual place in the Api where you pass the dashboardhttps://adminbro.com/AdminBroOptions.html#dashboard
-  in the component you will probably wato to use Api client: https://adminbro.com/ApiClient.html#getDashboard
- finally take a look at the design system to see which components you can use (by the examples there is a modify example button showing the example code which you can edit). Box is the most important one.

**Comment by soheilgk** [comment]
sorry but i couldnt get it..
i just want to empty dashboard

**Comment by johnyvelho** [comment]
hi @soheilgk . To get an empty dashboard, follow these steps:

1 - create a components folder (or whatever). Call it as dashboard.tsx (or whatever) with the following content:
```
const Dashboard = () => {
    return null
}

export default Dashboard
```

2 - add the dashboard option:

```
const adminBro = new AdminBro({
        resources: [
            ...yourResources
        ],
        dashboard: {
            component: AdminBro.bundle('./components/dashboard'),
        },
})
```

Done :)

**Comment by Chukstart** [comment]
Did this work it doesn't work for me do I have to install React or babel or any other packages?
