### ISSUE TITLE
Error on start up when loading AdminBro router to express / sequelize

### ISSUE THREAD

**Issue by nealdyrkacz** [SoftwareBrothers/admin-bro#600]
Wanting to check out AdminBro for use with Express / Sequelize / Typescript but I am getting some errors on server start up if I add in the AdminBro router I created below 
./admin.ts
```
import AdminBro from 'admin-bro';
const AdminBroExpress = require('@admin-bro/express');
import AdminBroSequelize from '@admin-bro/sequelize';


import { db } from './database/models/';

AdminBro.registerAdapter(AdminBroSequelize);

const adminBro = new AdminBro({
  resources: [
    {
      resource: db.Thing,
      options: {},
    },
  ],
  rootPath: '/admin',
});

export default AdminBroExpress.buildRouter(adminBro);
```

I am using v6 of Sequelize along with Typescript, so my model files are not using ```define``` , but by extending Model and Initializing before connection.

When adding the line ```this.app.use('/admin', adminBroRouter);``` the server throws an error.

**ERROR** :
```
node_modules/jest-worker/build/WorkerPool.js:25
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.obj.(anonymous function) [as runInThisContext] (/.../node_modules/ts-node-dev/lib/hook.js:30:19)
    at Module._compile (module.js:616:28)
    at Module._compile (/.../node_modules/source-map-support/source-map-support.js:521:25)
    at Module._extensions..js (module.js:663:10)
    at Object.nodeDevHook [as .js] (/.../node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[ERROR] 14:25:17 SyntaxError: Unexpected token {

```

**package versions:
"@admin-bro/express": "^3.0.0",
"@admin-bro/sequelize": "^1.1.0",
"admin-bro": "^3.2.5",
"express": "^4.17.1",
 "express-formidable": "^1.2.0",
 "sequelize": "^6.3.1",
"typescript": "^3.9.6",**

**Comment by wojtek-krysiak** [comment]
it looks like the syntax error in jest run by ts-node. I dont think it is related to AdminBro. For starterd try to run admin withour importing { db }, with empty resources array, and see if you have the same error.

you can take a look at @admin-bro/sequelize code since there is an example-app folder writen in ts.

**Comment by nealdyrkacz** [comment]
@wojtek-krysiak I removed the database import, no luck.  

I will dive more in to that example-app folder

**Comment by nealdyrkacz** [comment]
Got it.  Looks like I totally overlooked my node version
