### ISSUE TITLE
Is the custom property for richtext type still working?

### ISSUE THREAD

**Issue by domingosl** [SoftwareBrothers/admin-bro#603]
According to the documentation: https://adminbro.com/tutorial-cms.html we can pass a property named **custom** with parameters that are then serialized and passed to the frontend. But after several attempts, I cannot get Adminbro to pass the data, and after looking in the source https://github.com/SoftwareBrothers/admin-bro/blob/master/src/frontend/components/property-type/richtext/edit.tsx It doesn't seem that something is passed, in fact, the options for Quill are static (https://github.com/SoftwareBrothers/admin-bro/blob/c68e88be4414ede929899c90b82c9ebadf908cb4/src/frontend/components/property-type/richtext/edit.tsx#L78-L94)

Am I missing something or this is really broken?

**Comment by wojtek-krysiak** [comment]
we are in the process of rewriting quill because it is buggu. New version will be released next week
