### ISSUE TITLE
Unify login paths in AdminBroOptions

### ISSUE THREAD

**Issue by domingosl** [SoftwareBrothers/admin-bro#604]
Original message:

If you define **rootPath** as "/foo" (or any other value different from "/admin") with an authenticated router, and open the Adminbro webapp, in my case: http://127.0.0.1:2030/foo

The web app will redirect the user to http://127.0.0.1:2030/admin/login. Which is of course wrong, the expected behavior is a redirect to http://127.0.0.1:2030/foo/admin/login

It seems that Adminbro is not considering the **rootPath** value when doing the redirect.

Additional information:
* cleanup paths for adapters. For instance, when you pass '/' express has some hacks for that the same as firebase. basically, in this task, we will have to move all these hacks to admin bro core.

**Comment by wojtek-krysiak** [comment]
there are 2 other options: loginPath and logoutPath. cbeck out AdminBroOptions in the doce

**Comment by domingosl** [comment]
> there are 2 other options: loginPath and logoutPath. cbeck out AdminBroOptions in the doce

I think that needs a refactory, for 2 reasons, first  the user should no have to repeat the rootPath literal in the login path and logout path, also I don't think is useful for the user the choose those URLs, and second if you use "/" as rootPath the login page goes into an infinite loop of redirects for some reason. Example:

```
        rootPath: '/',
        loginPath: '/login',
        logoutPath: '/logout',
```

**Comment by wojtek-krysiak** [comment]
yep with / there is am issue in express plugin. This is something which wd have to  unify, but has super small priority. Leaving tjis open

**Comment by junnyea** [comment]
hello, this rootpath seriously confuse developer. the options provides developer to input 'rootPath' but your method only works with '/admin'. there should be something wrong with your design.

**Comment by wojtek-krysiak** [comment]
created a feature request for that: #653
