### ISSUE TITLE
Cannot call action with HTTP POST method

### ISSUE THREAD

**Issue by dyabala** [SoftwareBrothers/admin-bro#606]
**Describe the bug**
I have a custom action in resource options like this:

```
{
    ...,
    options: {
        ...,
        actions: {
            ...,
            someAction: {
				component: false,
				actionType: 'record',
				handler: async (req, res, context) => {
					// my logic here
					return <RecordJSON>
				}
			},
        }
    }
}
```
Inside the frontend component, I use ApiClient to request to this action:

```

api.recordAction({ recordId: record.id, resourceId: resource.id, actionName: "someAction", data: { foo: "bar" } }) // This gonna map as http POST method as the logic in api-client.ts
      .then(response => {
        console.log(response)
        sendNotice({message: 'Add new group successfully.', type: 'success'})
      })
      .catch(error => {
        console.log(error)
        sendNotice({message: 'Error occurs when trying to add new group to user.', type: 'error'})
      })

```

However, the request return with `BadRequestError: request aborted`, but when I call it with GET method everything is ok.

**Installed libraries and their versions**

   "admin-bro": "3.2.5-build9",
    "admin-bro-expressjs": "^2.0.0",
    "admin-bro-mongoose": "^v0.4.0",
    "express": "^4.17.1"

**Error Log**

BadRequestError: request aborted
    at IncomingMessage.onAborted (/ubuntu/my_project/node_modules/raw-body/index.js:231:10)

**Expected behavior**
Be able to call custom action with http method.

**Comment by dyabala** [comment]
Update: It appears to be my configurations of formidable and body-parser in express.

**Comment by Mnabawy** [comment]
what causes this issue?
