### ISSUE TITLE
Infinite loading on internal server error

### ISSUE THREAD

**Issue by Ellenek** [SoftwareBrothers/admin-bro#610]
**Describe the bug**
https://share.getcloudapp.com/04uqpvwx When I try to go into a resource and server returns 500, I have a default error popup that something went wrong and afterwards the loader never stops. Is there some way to make loader stop and show a custom message?

* admin-bro@3.2.5
* admin-bro-expressjs@2.1.0
* admin-bro-sequelizejs@0.5.0

**Comment by wojtek-krysiak** [comment]
can you paste the stacktrace from logs?

**Comment by Ellenek** [comment]
https://share.getcloudapp.com/WnuJovN8 I know that this loader never stops because of non existent user id, that's why server throws 500, but there should be a way to show a custom message instead of infinite loader in case of server errors

**Comment by wojtek-krysiak** [comment]
ok. noted. i think it is related to #580

**Comment by wojtek-krysiak** [comment]
closing in favour of #580
