### ISSUE TITLE
No values for arrey field in list view

### ISSUE THREAD

**Issue by amberlionk** [SoftwareBrothers/admin-bro#630]
**Describe the bug**
When i try to list records of a table with array field, in the column instead of value i see `lenght: 1` text.

**Installed libraries and their versions**

"admin-bro": "^3.2.5",
"admin-bro-expressjs": "^2.1.1",
"admin-bro-sequelizejs": "^0.5.1",
"sequelize": "^6.3.5",

Model:
```
  {
        id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
        },
        region: {
            type: DataTypes.ARRAY(
                DataTypes.ENUM(Object.values(Varieties.REGION_CHOICES)),
            ),
            values: Object.values(Varieties.REGION_CHOICES),
            allowNull: false,
        },
```
Adminbro setting:
```
       {
            resource: models.Varieties,
            options: {
                parent: contentParent,
                listProperties: ["id", "region"],
                properties: {
                    region: { position: 2, max: 10 },
                    id: { position: 98, isTitle: true },
                },
            },
        },
```

**Expected behavior**
To see values of region in the list, as it does when i open record.

**Screenshots**
![firefox_2020-10-08_11-35-21](https://user-images.githubusercontent.com/29119723/95435844-c4997f80-095b-11eb-9141-7d51be04469c.png)

**Comment by wojtek-krysiak** [comment]
this is how arrays are rendered in the list - we have less place than in show so we decided to do this by default. You can change that by writing custom component for list action.
