### ISSUE TITLE
When using admin-bro and admin-bro-sequelize, type json columns are parsed incorrectly.

### ISSUE THREAD

**Issue by Ellenek** [SoftwareBrothers/admin-bro#631]
**Describe the bug**
When using admin-bro and admin-bro-sequelize, type json columns are parsed incorrectly.
The data does not show up in the row, It should be `{
  "test": "test"
}`.
When inspecting the network request and seeing params this can be found `data.test: "test"` which should be this: `data: {"test":"test"}`.
This is not the case for all the json columns, some of them appear normally.

**Installed libraries and their versions**
* admin-bro@3.2.5 (also tested on  admin-bro@2.90)
* @admin-bro/sequelize@1.1.1

**Comment by wojtek-krysiak** [comment]
we are working on jsonb fields right now. It is done in the latest beat (v3.3-beta.17) but we are improving it here and there and will push an update In a matter of hours.

In the new beta there is a way of defining nested schemas right in AdmiBroOptions:

```
properties: {
  myRootProperty: { type: 'mixed' },
  'myRootProperty.nested1': {type: string},
  'myRootProperty.nested2': {type: string},
}
```

or even:
```
properties: {
  myRootProperty: { type: 'mixed', isArray: true},
  'myRootProperty.nested1': {type: string},
  'myRootProperty.nested2': {type: string},
}
```

I think that the final release will be done next week - but no promises.

Untill then we try to keep https://beta.adminbro.com/docs.html updated

**Comment by Ellenek** [comment]
@wojtek-krysiak thanks 🎉
