### ISSUE TITLE
Usage with MongoClient instead of mongoose

### ISSUE THREAD

**Issue by mahajan8** [SoftwareBrothers/admin-bro#633]
Hi,
This is a great library and it works with mongoose only. I have already written all of my code with MongoClient instead and I find it better.
Is there any way yet to use AdminBro along with MongoClient? Please help.

**Comment by wojtek-krysiak** [comment]
you will have to write your adapter. Dig to the admin-bro-mongoose code and see how that works.

PS: in latest v3.3 we moved populator logic to the admin-bro core so adapters doesn't have to implement that

**Comment by wojtek-krysiak** [comment]
just let you know that we don't have in plans writing adapter to MongoClient as a supported adapter (there are plans for prisma, graphql, micro orm). That is why I am closing this one

**Comment by kodeine** [comment]
@wojtek-krysiak any ideas when graphql and mikro orm will be integrated ?
