### ISSUE TITLE
BaseRecord.param() returns [null] if reference field value is null

### ISSUE THREAD

**Issue by dziraf** [SoftwareBrothers/admin-bro#634]
**Describe the bug**
When list view is entered and `populator` is run and a record exists which has `null` in reference field, `BaseRecord.param(path)` returns `[null]`.

This causes this fragment of `populateProperty` to behave wrongly:
```
  const externalIdsMap = records.reduce((memo, baseRecord) => {
    const foreignKeyValue = baseRecord.param(property.path)
    // when foreign key is not filled (like null) - don't add this because
    // BaseResource#findMany (which we will use) might break for nulls
    if (!foreignKeyValue) {
      return memo
    }
```
`foreignKeyValue` is not falsy in this case because it's a one element list.

When you debug `externalIdsMap` later, `[null]` is changed to `''` in the mapping. This results in:
```
CastError: Cast to ObjectId failed for value "" at path "_id" for model "ModelName"
```

The error is thrown because AdminBro attempts to populate using ObjectId cast with an empty string which appears in the mapping.

**Installed libraries and their versions**

* admin-bro@3.3.0-beta.13
* @admin-bro/mongoose@1.0.0

**To Reproduce**
1. Create a Model with a reference, i. e.:
```
export class Todo {
  @Expose({ name: 'id', toPlainOnly: true })
  public readonly _id!: mongoose.Types.ObjectId;

  @prop({ ref: Item })
  @Type(() => Item)
  public seller!: Ref<Item>;
}
```

```
export class Item {
  @Expose({ name: 'id', toPlainOnly: true })
  public readonly _id!: mongoose.Types.ObjectId;

  @prop({ required: true })
  public name!: string;
}
```
2. Setup AdminBro with these models, make sure `item` is in `listProperties` for Todo.
3. Create Todo where `item` is `null`.
4. Go to list view of Todo.
5. The error appears.

**Expected behavior**
There is no error and no value is displayed for `item` if it's null.

**AdminBroOptions with schema**
Example models are above.

**Comment by wojtek-krysiak** [comment]
I think it is was fixed - take a look at my comment in Your PR and this commit: https://github.com/SoftwareBrothers/admin-bro/commit/bb9de777d67e3425928a2b6a8825626c7f9bc4bd#diff-15b392d592d49fff9fe23078e53a9474R22
