### ISSUE TITLE
Is there a way we can stop duplicate properties for two records in a resource?

### ISSUE THREAD

**Issue by ayushbhat** [SoftwareBrothers/admin-bro#636]
I'm using your example app and when I try to make two companies with same email IDs, it doesn't complain.
![image](https://user-images.githubusercontent.com/10598279/95646721-0572cf00-0ae9-11eb-859c-a6cac1ecf29d.png)

Can there be a way we can stop this type of duplication?

**Comment by wojtek-krysiak** [comment]
not sure which example app are you using buy unique constrain can be achieved on the ORM level, or you can write your own validation with https://adminbro.com/ValidationError.html (https://adminbro.com/tutorial-actions-validations.html)

**Comment by ayushbhat** [comment]
That's exactly what I wanted sir!!!! Thanks!!
