### ISSUE TITLE
Richtext store in markdown

### ISSUE THREAD

**Issue by ArcaneDiver** [SoftwareBrothers/admin-bro#638]
**Problem**
I sould save the text from a `richtext` property in the markdown format because the Quill's html it is pratically end at itself

If you know any ways to solve this please tell them to me.

**Proposal**
You migth migrate to a more modern rich text editor like `SlateJs` which easily supports Markdown serialize

**Comment by wojtek-krysiak** [comment]
hmm - interesting. We implemented quill 2 years ago and haven't thought about changing it to something else. But this slatejs looks promising. Do you have more experience with it?

Until then you can try to use it on your own - simply create your own component for given property.

**Comment by ArcaneDiver** [comment]
I have no experience on it.
May you reference where i could look for implement my own component?

**Comment by wojtek-krysiak** [comment]
this is a big thing for a PR to the core right away (you will have to PR this to @admin-bro/design-system). But you can make it a feature as @admin-bro/upload or @admin-bro/password. I can then publish it on our documentation page.

**Comment by ArcaneDiver** [comment]
I tried to implement by my own and i recived errors on bundle similiar to this issue #492. Then i think that in the next days i'll investigate and make a PR to resolve those kind of problems.

**Comment by wojtek-krysiak** [comment]
I think I fixed that in latest beta so just upgrade and you should be able to import slate without a problem. https://github.com/SoftwareBrothers/admin-bro/releases/tag/v3.3.0-beta.25

`yarn add admin-bro@v3.3.0-beta.25`

**Comment by ArcaneDiver** [comment]
Awesome then i'll try It as soon as possible

**Comment by wojtek-krysiak** [comment]
So now this can be resolved by a custom AdminBro Feature. that is why I am closing this one, and opening this: #654

**Comment by PranaytheSingh** [comment]
,mnn
