### ISSUE TITLE
Is it possible to change the showing field name of some model?

### ISSUE THREAD

**Issue by heckad** [SoftwareBrothers/admin-bro#642]
For example, I have a foreign key field with the name `doctor_id`. This field shows as Doctor Id. I want to change this to just `Doctor`. How to do this?

**Comment by wojtek-krysiak** [comment]
https://adminbro.com/tutorial-i18n.html

**Comment by mohamed-nazmi** [comment]
There are some words that I can't translate according to the official tutorials. Here are some:

- "Dashboard"
- "Reset" in filters
- "Navigation" in sidebar
- The whole "Welcome" phrase in the login page

**Comment by wojtek-krysiak** [comment]
take a look at the original en translation file: https://github.com/SoftwareBrothers/admin-bro/blob/07f222eb50470cb926c76a5f1ccb6855b63566df/src/locale/en.ts#L1-L1

**Comment by bhoodream** [comment]
How to translate the word "Dashboard" in breadcrumbs?
