### ISSUE TITLE
When we remove a nested property it always removes the first last one only.

### ISSUE THREAD

**Issue by ayushbhat** [SoftwareBrothers/admin-bro#645]
If we have to remove the nested property field like below:
![image](https://user-images.githubusercontent.com/10598279/96468294-8ba9b680-1249-11eb-8af6-cc555b1f2d91.png)
It always only removes the last one no mater which one we will delete:
![image](https://user-images.githubusercontent.com/10598279/96468370-a9771b80-1249-11eb-96f7-f10cf932846e.png)
On clicking the delete of Camera it deleted the last one Keyboard not the Camera.

**Comment by wojtek-krysiak** [comment]
which versions of admin-bro and @admin-bro/mongoose do you use?

**Comment by ayushbhat** [comment]
"latest"

**Comment by wojtek-krysiak** [comment]
it doesn't give me any information - because the version depends on when you installed. Please write the output of:
* `npm ls admin-bro`
* `npm ls @admin-bro/mongoose`

**Comment by ayushbhat** [comment]
admin-bro@3.2.5

and 
@admin-bro/mongoose@1.0.2

**Comment by wojtek-krysiak** [comment]
we are working on the update in 3.3 regarding the nested arrays.

**Comment by ayushbhat** [comment]
Posting the "show" Referenced property bug here for the record:
If there is a nested property in a Resource: 
![image](https://user-images.githubusercontent.com/10598279/96772359-a6725b80-1400-11eb-8e13-a1e53d7c054d.png)
It's reference JUST from show ( not from list ) gives this error in console:
![image](https://user-images.githubusercontent.com/10598279/96772457-c9047480-1400-11eb-8d6a-ac82e6ef93bb.png)

**Comment by ayushbhat** [comment]
My main User schema: 
`const mongoose = require('mongoose')

const UserSchema = new mongoose.Schema({
  adminName: {
    type: String,
  },

  distributorName: {
    type: String,
  },

  dealerName: {
    type: String,
  },

  adminCreatedBy: {
    type: mongoose.SchemaTypes.ObjectId,
    ref: 'Admins',
  },

  distributorCreatedBy: {
    type: mongoose.SchemaTypes.ObjectId,
    ref: 'Admins',
  },

  dealerCreatedBy: {
    type: mongoose.SchemaTypes.ObjectId,
    ref: 'Distributors',
  },

  email: {
    type: String,
    required: true,
    unique: true,
  },
  phoneNumber: {
    type: Number,
    validate : {
      validator : Number.isInteger,
      message   : '{VALUE} is not an integer value'
    }
  },

  SPOC: {
    type: String,
  },

  address: {
    type: String,
    // required: true,
  },

  bufferStock: {
    type: Number,
  },

  website: {
    type: String,
  },

  profilePhotoLocation: {
    type: String,
  },

  productType: [{
    type: mongoose.SchemaTypes.ObjectId,
    ref: 'ProductType',
  }],

  isAdmin: {
    type: Boolean,
    default: false,
  },

  isDistributor: {
    type: Boolean,
    default: false,
  },

  isDealer: {
    type: Boolean,
    default: false,
  },

  createdOn: {
    type: Date,
    default: Date.now(),
  },


  // companySize: {
  //   type: String,
  //   enum: ['b', 's', 't'],
  // },
  encryptedPassword: {
    type: String,
    required: true,
  },
  // disabledAt: {
  //   type: Date,
  // },
  // isAdmin: {
  //   type: Boolean,
  // },
  // isBig: {
  //   type: Boolean,
  // },
  // tags: [String],
})

const User = mongoose.model('User', UserSchema)

module.exports = { UserSchema, User }
`

Admin and Distributors are just renamed ( by ID ) resources of the same User Schema

**Comment by ayushbhat** [comment]
With the Schema specified above, the items in the payload is a string, but when we refresh or paste the URL in new tab, the iteams variable in the payload is an array.
