### ISSUE TITLE
Unable to use react-select inside my custom compoent

### ISSUE THREAD

**Issue by LahmerIlyas** [SoftwareBrothers/admin-bro#649]
**Describe the bug**
I'm trying to use react-select in one of my components, but an error is thrown

**Installed libraries and their versions**

* admin-bro@3.2.5
* @admin-bro/express@^3.0.1
* @admin-bro/typeorm@^1.3.0

**To Reproduce**
1. Bundle the following component:

```
import * as React from 'react';
import { EditPropertyProps, DropZone, FormGroup, Label, DropZoneItem } from 'admin-bro'
import * as Select from 'react-select';

export default function ManyToManyEditComponent({ property, record, onChange }: EditPropertyProps){
  const { custom, label } = property;

  return(
    <FormGroup>
      <Label> {label} </Label>
      <Select options={[]}/>
    </FormGroup>
  )
}
```

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    in Unknown (created by BasePropertyComponent)
    in section (created by styled.section)
    in styled.section (created by BasePropertyComponent)
    in ErrorBoundary (created by BasePropertyComponent)
    in BasePropertyComponent (created by New)
    in section (created by styled.section)
    in styled.section (created by New)
    in form (created by styled.section)
    in styled.section (created by New)
    in New (created by BaseActionComponent)
    in ErrorBoundary (created by BaseActionComponent)
    in BaseActionComponent (created by ResourceAction)
    in section (created by wrapper__StyledWrapper)
    in wrapper__StyledWrapper (created by Wrapper$1)
    in Wrapper$1 (created by ResourceAction)
    in ResourceAction (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in section (created by styled.section)
    in styled.section (created by App)
    in section (created by styled.section)
    in styled.section (created by App)
    in App
    in Router (created by BrowserRouter)
    in BrowserRouter
    in ThemeProvider
    in Provider global.bundle.js:510:31

**Expected behavior**
react-select is bundled with react-admin, so we should be able to use it.

**Comment by ayushbhat** [comment]
No it's not bundled,

add this to your dependencies:     "react-select": "^3.1.0",

and try again.

**Comment by LahmerIlyas** [comment]
@ayushbhat thx for your reply, I added it to my dependecies file and the same error persisted.

**Comment by ayushbhat** [comment]
change 
`import { EditPropertyProps, DropZone, FormGroup, Label, DropZoneItem } from 'admin-bro'`
to
`import { EditPropertyProps } from 'admin-bro'
import {DropZone, FormGroup, Label, DropZoneItem} from '@admin-bro/design-system'`

**Comment by LahmerIlyas** [comment]
@ayushbhat I did as you suggested but the same issue persisted

**Comment by LahmerIlyas** [comment]
any updates about this ?

**Comment by wojtek-krysiak** [comment]
`import Select from 'react-select'` doesn't work?

in the end you can use it from `window.ReactSelect` like `const ReactSelect = window.ReactSelect` since it is bundled there.

All the things related to problems with bundler will be handled in this task: #614

**Comment by LahmerIlyas** [comment]
@wojtek-krysiak Thx, your proposed solution works, you saved me.

**Comment by KrisTemmerman** [comment]
The actual solution to this issue is importing react-select the following way in TS, so it gets bundled !
``` import * as Select from 'react-select'```
