### ISSUE TITLE
Add the ability to use external react dependecies.

### ISSUE THREAD

**Issue by LahmerIlyas** [SoftwareBrothers/admin-bro#650]
Hi, thx for this awesome project, it saved a lot of time for me. I'm just wondering why is it hard to use external react dependencies, I tried to use many external packages, but with no success.

**Comment by wojtek-krysiak** [comment]
we use an old version of rollup bundler - there are tasks in backlog to change that but not scheduled right now #614 #359 #185 #575

**Comment by wojtek-krysiak** [comment]
I added more info to https://github.com/SoftwareBrothers/admin-bro/issues/575 - let it be the core task fro bundler long term improvements. Closing this one and lets move communication there
