### ISSUE TITLE
Is there a way to change the label of properties in Show/Edit page?

### ISSUE THREAD

**Issue by rishi-shah** [SoftwareBrothers/admin-bro#663]
Hi, Sorry I am new to this and didn't know who to ask, or didn't find any problem/solution similar to mine. I wanted to change the name of the label on the list/show page. I have a model like below

```
import mongoose from 'mongoose'


const socialmedia = new mongoose.Schema({
 Youtube: String,
 Facebook: String,
 Twitter: String,
 Instagram: String,
 TikTok: String,
 Snapchat: String,
 Reddit: String
});

const user = new mongoose.Schema({
 name: String,
 email: String,
 intro: String,
 socialmediachannels: socialmedia
});

```

now the problem with this is that, when I go to the edit/show option of the single user. it gives social media labels as

_socialmediachannels Youtube_ <- I want to change this to just show as _Youtube_, instead it shows as schema + propertyname

Is there a possible way to change _socialmediachannels Youtube_ -> _Youtube_. Or infact _intro_ -> _summary_ when shown in Show/edit page on UI.

Thanks in advance.

**Comment by dziraf** [comment]
Didn't test, but you can try to i. e. create an empty translation string for `socialmediachannels`, i. e.

*locale.js*:
```
module.exports = {
  language: 'en',
  translations: {
    resources: {
      user: {
        properties: { // might be "labels" instead of "properties"?
          socialmediachannels: '',
        }
      }
    }
  }
}
```
This should do what you want. If it doesn't you can also create a property component:

*user.resource.js*:
```
module.exports = {
  resource: user,
  options: {
    // the rest of your resource options,
    properties: {
      socialmediachannels: {
        components: {
          list: <list component>,
          show: <show component>,
          //etc
        }
      }
    }
  }
}
```
You can lookup `BasePropertyComponent` in source code on how to create one. Or you can create any React component that uses `BasePropertyProps`

**Comment by rishi-shah** [comment]
@dziraf : Thank you very much, this worked great! I made changes in `properties: {}` and it seems to be working now. You saved me a ton of work, Thanks again :)
