### ISSUE TITLE
Can't localize filter action.

### ISSUE THREAD

**Issue by heckad** [SoftwareBrothers/admin-bro#675]
**Describe the bug**
I tried to localize a filter button on resource using action filter but this nothing change. In inspector filter button don't have the `data-testid="action-filter"`.

**Installed libraries and their versions**

* admin-bro@3.31
* admin-bro-expressjs@2.1.1
* admin-bro-sequelizejs@0.5.1

**Comment by wojtek-krysiak** [comment]
there is no filter action per se. Filter it is just a component which (base on his inputs) adds to the query string parameters. Next, these parameters, are passed to the List action
