### ISSUE TITLE
use sequelize connect to mysql, set up resources, create, edit and other actions, data operation is successful, but 404 is reported

### ISSUE THREAD

**Issue by TerryZiHang** [SoftwareBrothers/admin-bro#693]
**Describe the bug**

**Installed libraries and their versions**

* admin-bro@2.0.1
* admin-bro-expressjs@2.0.0
* admin-bro-mongoose@1.4.0
... mongo, express (whatever you think is relevant)

**To Reproduce**

**Expected behavior**

**Screenshots**

**AdminBroOptions with schema**
Paste your AdminBro config with database schema if it could be related to the issue

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Additional context**

**Comment by SimonB407** [comment]
Please fill template when creating an issue. We could not help you if you not provide description of an issue.
