### ISSUE TITLE
Filter by multiple text fields

### ISSUE THREAD

**Issue by omen-x** [SoftwareBrothers/admin-bro#697]
**Describe the bug**
When I try to filter by 2 or more "text" fields only the first "text" filter is applied.
Can be reproduced with "admin-bro-example-app". 

**To Reproduce**
1. Setup and run "admin-bro-example-app"
2. Add some users
3. Change "email" and "lastName" in the filter
4. Only "email" applied

**Expected behavior**
All "text" filters applied

**Comment by dziraf** [comment]
Works for me in the demo app: https://admin-bro-app.firebaseapp.com/admin/resources/Users?filters.firstName=Test&filters.lastName=User&page=1

`admin@example.com / password`

**Comment by omen-x** [comment]
I've added one more user.

1) https://admin-bro-app.firebaseapp.com/admin/resources/Users?page=1&filters.firstName=Bob&filters.lastName=User
Two users filtered (incorrect)
2) https://admin-bro-app.firebaseapp.com/admin/resources/Users?page=1&filters.firstName=Bob
One user filtered (correct)

**Comment by dziraf** [comment]
This is now fixed in `@admin-bro/sequelize@1.1.2`. Thanks to @t1nky for creating the PR with the fix!
