### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by al6x** [SoftwareBrothers/admin-bro#701]
<img width="1002" alt="Screen Shot 2020-12-05 at 2 11 05 am" src="https://user-images.githubusercontent.com/94196/101224270-2b5ac100-369f-11eb-93fe-c25f51aa4d39.png">

**Comment by fogine** [comment]
its been migrated to 
https://admin-bro-app.firebaseapp.com/admin

**Comment by al6x** [comment]
Thanks, is the password the same? The `test@example.com/password` is not working.

**Comment by fogine** [comment]
I think its admin@example.com

**Comment by jligeza** [comment]
@fogine admin@example.com:password doesn't work

**Comment by fogine** [comment]
it did, now it doesnt :(

**Comment by SimonB407** [comment]
Duplicate of #684
