### ISSUE TITLE
Action filte by ID is not work

### ISSUE THREAD

**Issue by peter-up** [SoftwareBrothers/admin-bro#713]
**Describe the bug**
you can try to browser https://admin-bro-app.firebaseapp.com/admin/resources/Users?filters.id=1234&page=1 
**Installed libraries and their versions**
I tried adminbro demo

**Screenshots**
![image](https://user-images.githubusercontent.com/7362306/102210646-68c81580-3f0d-11eb-9f9b-61bf214aaae8.png)

**Comment by dziraf** [comment]
This fails because the id in Users table is a UUID. Passing a non-UUID value causes an error on SQL level. We could validate if provided value is UUID before querying, but the error would still be there
