### ISSUE TITLE
You probably used old `body-parser` middleware, which is not compatible with admin-bro-expressjs

### ISSUE THREAD

**Issue by ffegu** [SoftwareBrothers/admin-bro#718]
You probably used old `body-parser` middleware, which is not compatible with admin-bro-expressjs. In order to make it work you will have to 1. move body-parser invocation after the admin bro setup like this: const adminBro = new AdminBro() const router = new buildRouter(adminBro) app.use(adminBro.options.rootPath, router) // body parser goes after the AdminBro router app.use(bodyParser()) 2. Upgrade body-parser to the latest version and use it like this: app.use(bodyParser.json())

**Comment by dziraf** [comment]
Are you sure this should be a separate issue, not a response to an existing one?
