### ISSUE TITLE
Insert Section wrapping a Resource and Children

### ISSUE THREAD

**Issue by Cauen** [SoftwareBrothers/admin-bro#719]
I just spent some hours trying to create a section to group a resource (just for organization)
But, i couldnt find any option inside ResourceOptions
If i use "type: mixed", an section is created but data cant be saved
The section is also created if i create a array of billings, but i want only one

There is a way to turn this model (Mongoose)
![image](https://user-images.githubusercontent.com/8796757/102703922-275ca080-4254-11eb-8e79-a4517b7249dc.png)

From this UI 
![image](https://user-images.githubusercontent.com/8796757/102703943-5d018980-4254-11eb-985c-114a9553c5d9.png)

Into this?
![image](https://user-images.githubusercontent.com/8796757/102703916-0c8a2c00-4254-11eb-971d-7959fbb65ceb.png)

Thanks

**Comment by dziraf** [comment]
Using a Mongoose schema for `shipping` in the model is enough to get this to work:
```
  shipping: new mongoose.Schema({
    state: { type: String, required: true },
    city: { type: String, required: true },
    checkbox: Boolean
  })
```
![image](https://user-images.githubusercontent.com/16668924/102888527-48421300-4459-11eb-8492-8bf2205e5b4b.png)

Let me know if this works fo you so I can close the issue.
