### ISSUE TITLE
Is there a way to group Navigations in sidebar? : i.e. Parent/Parent/Resources in sidebar

### ISSUE THREAD

**Issue by creeper00** [SoftwareBrothers/admin-bro#735]
Read docs and codes on ResourceOptions and SidebarResourceSections but couldn't find the way to do it.
Can we group Resource Navigations in sidebar? : like Companies/Products/Cars 
Currently it looks like only single grouping is possible, like in Tutorials and Examples using Options in Resource.

**Comment by SimonB407** [comment]
Built in navigation allows only for depth of one. You can customize resources sidebar component with your custom component that will group everything your way. You can achieve it by doing `AdminBro.bundle('_path to your custom component_', 'SidebarResourceSection')`;
