### ISSUE TITLE
adding multiple mongoose databases with createConnection instead connect

### ISSUE THREAD

**Issue by handrei** [SoftwareBrothers/admin-bro#742]
**Describe the bug**
adding multiple mongoose databases with createConnection() instead connect() isn't working. I receive this error:
`NoDatabaseAdapterError: There are no adapters supporting one of the database you provided`

**Installed libraries and their versions**

"@admin-bro/express": "^3.0.1",
"@admin-bro/mongoose": "^1.1.0",
 "admin-bro": "^3.3.1",
"express": "^4.17.1",
"express-formidable": "^1.2.0",

**To Reproduce**
i have two mongoose connections created with mongoose.createConnection(uri)

const adminBro = new AdminBro({
      databases: [conn1, conn2],
      rootPath: '/admin',
    });

**Expected behavior**
createConnection() should work as connect()

**Comment by handrei** [comment]
hello guys, i closed this issue because it's not a bug.
the fix is not to add the databases property to adminBro, only the resources.
ex: 

`
const api = mongoose.createConnection(process.env.apiURI);
const car = mongoose.createConnection(process.env.carURI);

const User = api.model('User', require('../models/User');
const Car = cars.model('Car', require('../models/Car');

const adminBro = new AdminBro({
resources: [{resource: User}, {resource: Car}]
rootPath: '/admin',
});`

and keep in mind that the model should export only the UserSchema and CarSchema

**Comment by on21life** [comment]
Even if it was a simple mistake in that version, it is now not possible to refer to it in the same way. "@adminjs/mongoose": "^2.0.2",
    "adminjs": "^5.8.1".
Use this method to solve
`new AdminJS({
        databases: [mongooseConnection.base])`
