### ISSUE TITLE
Can't upload public files to S3

### ISSUE THREAD

**Issue by MohOraby** [SoftwareBrothers/admin-bro#774]
**Describe the bug**
Files won't be publicly readable in S3 bucket even if expires is set to 0

Error probably caused by 
Line 22 in build/features/upload-file/providers/aws-provider.js
`this.expires = options.expires || constants_1.DAY_IN_MINUTES;`
and/or Line 55 in src/features/upload-file/providers/aws-provider.ts
`this.expires = options.expires || DAY_IN_MINUTES`

if expires is set to 0 the || will cause the code to use the constant value of 86400 minutes for expires

**Installed libraries and their versions**

* @admin-bro/express@3.1.0
* @admin-bro/mongoose@1.1.0
* @admin-bro/upload@1.3.0

**Expected behavior**
Upload file to bucket with ACL 'public-read'

**Comment by dziraf** [comment]
Hi this should be fixed in v1.3.1
