### ISSUE TITLE
Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by Nerah** [SoftwareBrothers/admin-bro#775]
# Context

I use Chrome and Windows 10.

AdminBro works pretty well when I test it in localhost.
However, when I tried to host it on OVH, it gave me the following error messages :

![Capture](https://user-images.githubusercontent.com/35778915/108878531-a2e61f80-7600-11eb-9514-e88a67a9dee0.PNG)

It seems it doesn't compile.

![Capture](https://user-images.githubusercontent.com/35778915/108879001-17b95980-7601-11eb-8940-d2625bec52cb.PNG)

I saw a similar issue in the list.
It seemed it was due to the route.
However, I specified my route as "/admin" in express.

![Capture](https://user-images.githubusercontent.com/35778915/108879375-7d0d4a80-7601-11eb-96e5-9d6e72d7b0da.PNG)

AdminBro options :

![Capture](https://user-images.githubusercontent.com/35778915/108879820-ec833a00-7601-11eb-8247-d3ac7c98c8d4.PNG)

# Hunches

To access the deployed server, I set up the path to be "myapplication/api".
Therefore, I try to access to AdminBro through "myapplication/api/admin".
Is it possibly a reason?

<br/>

I love your library, by the way! :3
Thank you for your work!

**Comment by leibowitz** [comment]
How do you deploy your app, and what command do you use to run it on your server?

**Comment by Nerah** [comment]
Thank you for your answer.

The server is deployed on a VPS with Nginx.
It is launched with the start command: "node src/index.js".

Here is the Nginx configuration :

server {
        listen 80;

        index index.html

        server_name ***;

        client_max_body_size 10M;

        location / {
                root /var/www/webapp/build;
                try_files $uri /index.html;
        }

        location /api/ {
                proxy_pass http://127.0.0.1:9000/;
        }

        location /socket.io {
                proxy_pass http://localhost:9001/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
}

**Comment by leibowitz** [comment]
> ![Capture](https://user-images.githubusercontent.com/35778915/108878531-a2e61f80-7600-11eb-9514-e88a67a9dee0.PNG)

You can clearly see in your console that the bunde files are not being served properly. The fact that it mentions unexpected token "<" in red means it's serving an error on that url.

In the following image, you should look closely at the head section, where all the script are being loaded:
> ![Capture](https://user-images.githubusercontent.com/35778915/108879001-17b95980-7601-11eb-8940-d2625bec52cb.PNG)


You mention that the start command you use is "node src/index.js", suggesting you are not building the code. You haven't talked about dependencies (do you run yarn or npm install on deploy?)

> It is launched with the start command: "node src/index.js".

And in your config, you use a directory called `/var/www/webapp/build`. Does that mean you are serving the build files from there? 

There's a lot of gap of information in your issue. It's hard to help without them. Best is to ask on #slack for these kind of problems

**Comment by Nerah** [comment]
I'll try my best to decrease the lack of information.

## Global architecture

I'm working on a application which is using following architecture :
- a client side based on React (which is contained in the webapp folder).
- an Express server using Mongoose and AdminBro.
- I also use a reverse proxy (Nginx) to connect the two sides and socket.io.

In the deployment phase, the client is built and will run at http://myapplication/.
The server will on the other hand be running at http://myapplication/api.

## Running locally the server

As you said, I don't build my server. I just run it. Maybe this is the reason! ^^

The package.json file use the following dependencies and scripts:

![package_json](https://user-images.githubusercontent.com/35778915/109193169-62b9a500-7798-11eb-979e-3541902c158f.PNG)

I use npm to install dependencies (locally and before deployment).

When I run the server locally (with nodemon or node), AdminBro does work:

![server_running_locally](https://user-images.githubusercontent.com/35778915/109193396-9a285180-7798-11eb-9589-8f335281163f.PNG)

![adminbro_dashboard](https://user-images.githubusercontent.com/35778915/109193470-ac09f480-7798-11eb-89c4-65d6ab90a203.PNG)

## Running the deployed server

After deployment, the server is working:

![server_deployed](https://user-images.githubusercontent.com/35778915/109192390-6dc00580-7797-11eb-94ff-819be3b0c695.PNG)

However, when I try to access to the route /admin of the server (myapplication/api/admin),
I have the error I previously spoke of.

In the head section, I get a script with an assignment of the window.REDUX_STATE variable:

![admin_error_head](https://user-images.githubusercontent.com/35778915/109194034-4ff3a000-7799-11eb-89b6-3e279b9161b7.PNG)

Here is the full source file:

[adminbro_not_compiled.zip](https://github.com/SoftwareBrothers/admin-bro/files/6044854/adminbro_not_compiled.zip)

**Comment by leibowitz** [comment]
I was referring to the `script` tags in the `head` section, aka:
```
      <script src="/admin/frontend/assets/global.bundle.js"></script>
      <script src="/admin/frontend/assets/design-system.bundle.js"></script>
      <script src="/admin/frontend/assets/app.bundle.js"></script>
      <script src="/admin/frontend/assets/components.bundle.js"></script>
```
This is the part that is failing for you. You have to find out why these assets are not loading properly.

If you are accessing your server via `myapplication/api/`, then `/admin` will refer to the root path, aka `myapplication/admin`. Since you are serving those files under `myapplication/api/admin/...`, obviously these won't load properly.

Just try accessing `myapplication/admin/frontend/assets/global.bundle.js` and `myapplication/api/admin/frontend/assets/global.bundle.js` to see what I mean. One should load, and the other will return a 400 (or any other error response)

**Comment by Nerah** [comment]
I see the issue now!
The scripts are indeed accessible through ``myapplication/admin/api/...``,
and the page tries to load them through ``myapplication/admin/...``.

I will look into it when I can.
I will put the way I resolve the case here.

Thank you so much!

**Comment by Nerah** [comment]
Hi @p-pcode !
If I remember well, I was under a nginx reverse proxy.
The URL that was called wasn't the one I wanted (https://myurl.com instead of https://myurl.com/api).
I just had to change the configuration to make it work.
