### ISSUE TITLE
Set height of rich text and change tab title

### ISSUE THREAD

**Issue by fahimhoque** [SoftwareBrothers/admin-bro#780]
is it possible to set height for the rich text in admin bro?

`        
             
            {
                 
            resource: Visa,  
             
            options: {
                parent: {
                    name: 'Visa'
                },
                properties: {
                    visa_free_travel: {
                        availableValues: [
                            {value: 'Yes', label: 'Yes'},
                            {value: 'No', label: 'No'},
                        ],
                    },
                    details: {
                      type: 'richtext',
                    },
                },
            }
        },
`
    
And is there a way to change the tab title for admin panel. It shows company by default.

**Comment by dziraf** [comment]
You can change textarea height using css:
```
textarea.admin-bro_Input {
  min-height: 200px;
}
```

Company name can be set in admin bro options, i. e:
```
...
branding: { companyName: 'Example' },
...
```
