### ISSUE TITLE
AdminBro Custom Component fails when deployed

### ISSUE THREAD

**Issue by raghavmecheri** [SoftwareBrothers/admin-bro#783]
**Describe the bug**
Transpiled AdminBro custom components break in production. While I'm not entirely sure why this occurs, my project runs as expected post-transpilation locally, but the component does not render when deployed to the Google App Engine.

**Installed libraries and their versions**
```
"@admin-bro/design-system": "^1.7.0",
"@admin-bro/express": "^3.0.1",
"@admin-bro/mongoose": "^1.1.0",
"@babel/cli": "^7.10.5",
"@babel/core": "^7.10.5",
"@babel/node": "^7.10.5",
"@babel/plugin-proposal-export-default-from": "^7.10.4",
"@babel/plugin-transform-runtime": "^7.10.5",
"@babel/preset-env": "^7.10.4",
"@babel/register": "^7.10.5",
"@babel/runtime": "^7.10.5",
"admin-bro": "^3.3.1",
```

**To Reproduce**
Our project structure is as follows, and the AdminBro call may be found in `server/routes/admin.js`:

```
.babelrc
server/
server/admin/dashboard.jsx
server/routes/admin.js
package.json
package-lock.json
```

server/routes/admin.js:
```js
export const adminPortal = (app) => {
  AdminBro.registerAdapter(AdminBroMongoose);
  const adminBro = new AdminBro({
    resources: [
      Resource1,
      Resource2
    ],
    rootPath: "/admin",
    branding: {
      companyName: "Name",
      logo: "image.jpg",
    },
    dashboard: {
      component: AdminBro.bundle("../admin/dashboard"),
    },
  });
  const router = AdminBroExpress.buildRouter(adminBro);
  app.use(adminBro.options.rootPath, VerifyRedirectToken, router);
  logger.info({
    message: `Admin router configured!`,
  });
};
```

The contents of the `.babelrc` are as follows, and the transpile command is be invoked as through`babel -d ./build ./server -s`:
```
{
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-proposal-export-default-from",
      "@babel/plugin-transform-runtime"
    ]
}
```

The error encountered may be found below:

```
[Error] Failed to load resource: the server responded with a status of 500 () (components.bundle.js, line 0)
[Error] Refused to execute https://[DOMAIN]/admin/frontend/assets/components.bundle.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Failed to load resource: The file “purify.js.map” couldn’t be opened because there is no such file. (purify.js.map, line 0)
```

**Expected behavior**
When the transpile command is run locally, the dashboard component renders. However, the same fails on the App Engine. The `.entry.js` file is as follows and it is the same file both locally, and on the remote deployment:
```js
AdminBro.UserComponents = {}
import Component1 from '../build/admin/dashboard'
AdminBro.UserComponents.Component1 = Component1
```

**Additional context**
This was not a problem earlier when our project had a `bundle.js` file within the `.adminbro/` directory. However, we deleted that file since it seemed to be caching the versions of the `.jsx` files and were hindering development.

**Comment by leibowitz** [comment]
could be related https://github.com/SoftwareBrothers/admin-bro/issues/751?

**Comment by raghavmecheri** [comment]
Closing this issue as it was related to running a snippet similar to the one below:

```js
if (process.env.ENV !== "test") {
    if (process.env.NODE_ENV === "production") {
      adminBro.initialize();
    } else {
      adminBro.watch();
    }
  }
```
