### ISSUE TITLE
Can I add dynamic values into my dropdown?

### ISSUE THREAD

**Issue by shivarajsb** [SoftwareBrothers/admin-bro#785]
**Describe the problem feature solves**
I currently have a dropdown and I'm using the availableValues field to populate it. Is there a way to query the database and populate this value?

**Describe the solution you'd like**
this would be a great solution to have , please do let me know if this has already been implemented 
![image](https://user-images.githubusercontent.com/73460908/110356691-831f1480-8060-11eb-94ea-2eab84c7664c.png)

**Comment by dziraf** [comment]
You'd probably have to create a custom component for this. There are autopopulated dropdowns for selecting references but adminbro recognises these through reference definitions in your models.

If you wanted to create a custom property component which loads available options dynamically, you can refer to: https://github.com/SoftwareBrothers/admin-bro/blob/907d03c7ed8f01ca5027655599faabad5c0f6d8c/src/frontend/components/property-type/reference/edit.tsx

The property options in your resource definition would then look like this:
```
questionType: {
  component: {
    edit: AdminBro.bundle(<component path>, <component name>),
    show: ... // you need to define a component for every action where you want to use it, but for i. e. show you can just use a default label/value here probably
  },
  type: 'string',
  custom: {
    reference: { resourceId: 'questions_types' }
  }
}
```
The `custom` property allows you to pass extra information to the property component. In this case you'd be passing reference data which you can use in your component's `loadOptions` method
