### ISSUE TITLE
Problems with simple record action

### ISSUE THREAD

**Issue by vladiulianbogdan** [SoftwareBrothers/admin-bro#791]
Hello,

I want to make a simple record action that when I click on it, it does something on the backend and when the response is received, the page is just refreshed.

My handler is like this:

```
handler: async (request, response, context) => {
          await CustomUserAdapter.blockUser(request.params.recordId, context.currentAdmin.providerType);
          return {
          };
        },
```

The problem that I encounter is in backend/controllers/api-controller at line 170:

```
    if (jsonWithRecord && jsonWithRecord.record && jsonWithRecord.record.recordActions) {
      return jsonWithRecord;
    }

    throw new _configurationError.default('handler of a recordAction should return a RecordJSON object', 'Action#handler');
```

The error is thrown here.

I've managed to hack my way into obtaining this by modifying the lines above to

```
    if (jsonWithRecord || jsonWithRecord.record && jsonWithRecord.record.recordActions) {
      return jsonWithRecord;
    }

     throw new _configurationError.default('handler of a recordAction should return a RecordJSON object', 'Action#handler');
```

and by adding an "after" handler that removes the record in order to avoid an error on the frontend.

``` 
      after: async (response, request, context) => {
          // response.record = undefined;
          return response;
        },
```

Is there a way to obtain this behaviour without these hacks?

**Comment by dziraf** [comment]
A record must be returned by design but you can attempt to return an empty record if you don't want to show this to the user:

```
import { BaseRecord } from 'admin-bro;
...
return {
  record: new BaseRecord({}, context.resource),
}
```

Not tested but might work

**Comment by vladiulianbogdan** [comment]
That still does not work because in the api-controller the third condition in the "if" fails because `jsonWithRecord.record.recordActions` is undefined. :(

**Comment by dziraf** [comment]
Could you try:
```
return {
  record: new BaseRecord({}, context.resource).toJSON(context.currentAdmin),
}
```
?
`jsonWithRecord.record.recordActions` might not be 100% needed in the condition but it's very likely that frontend components which depend on it will break if we simply remove that

**Comment by vladiulianbogdan** [comment]
Thank you! That works!
