### ISSUE TITLE
Allow override of CSS theme values

### ISSUE THREAD

**Issue by arronhunt** [SoftwareBrothers/admin-bro#80]
Looking through the docs, it looks like we're very limited on customizations when it comes to brand, specifically only being able to override `logo` and `companyName`. Since all the branding colors are being pulled from `src/frontend/styles/variables.js` it stands to reason it should be simple to allow for an override for these default variables.

**Comment by wojtek-krysiak** [comment]
yep - makes sense. Added this task to todo list

**Comment by arronhunt** [comment]
#87 is ready to merge pending you guys' approval :)

**Comment by wojtek-krysiak** [comment]
thanks - will look at it tomorrow and merge

**Comment by wojtek-krysiak** [comment]
was released in version 0.9.0-beta.3
