### ISSUE TITLE
rename fields

### ISSUE THREAD

**Issue by jhoriascos** [SoftwareBrothers/admin-bro#800]
Is it possible to rename the fields of the displayed tables?

Note: I would like to set special characters such as accents.

**Installed libraries and their versions**.
"admin-bro": "^2.9.0",
"admin-bro-expressjs": "^2.1.1",
"admin-bro-typeorm": "^0.1.6-alpha.9",

<img width="1277" alt="Captura de Pantalla 2021-03-30 a la(s) 10 56 10 a  m" src="https://user-images.githubusercontent.com/66481268/113018947-afe9b780-9146-11eb-93e9-7ac7c1bd15bd.png">

<img width="1280" alt="Captura de Pantalla 2021-03-30 a la(s) 10 58 38 a  m" src="https://user-images.githubusercontent.com/66481268/113019140-e6bfcd80-9146-11eb-845f-3bb7624eda3e.png">

**Comment by dziraf** [comment]
Yes, you can do this via `locale` property in AdminBro options: https://adminbro.com/AdminBroOptions.html#locale

**Comment by RudrikaJnext** [comment]
I have tried to change the field from the displayed table, referred: https://adminbro.com/AdminBroOptions.html#locale

Here, **Items** is the Resource name as well as a model name, and **ownerid** is the property.
![image](https://user-images.githubusercontent.com/82202278/114496773-4be2eb00-9c3e-11eb-88cc-0bc807551432.png)
![ColumnChange](https://user-images.githubusercontent.com/82202278/114496907-8e0c2c80-9c3e-11eb-911f-80d06dce11b4.png)
It still remains same. Is there any alternate way to do that?

**Comment by mokshmodi96** [comment]
Any update on this issue?

**Comment by dziraf** [comment]
I can't think of a reason why it wouldn't work for you, are you sure your the property name matches exactly what's in your model?

**Comment by mokshmodi96** [comment]
i want to name it differently than in the model

**Comment by dziraf** [comment]
Yes, but if your model field is defined as such:
```
@Column(...)
public ownerId: number;
```
you should use `ownerId` in adminjs locale settings:
```
...,
resources: {
  YourModel: {
    properties: {
      ownerId: 'Owner',
    },
  },
},
```

**Comment by RudrikaJnext** [comment]
@dziraf Thank you,
Yes it worked for me: 

```
locale: {
    // language: 'en',
    translations: {
      resources: {
        Reports: {
          properties: {
            userId: 'User'
          }
        },
```

**Comment by lumayara** [comment]
> I have tried to change the field from the displayed table, referred: https://adminbro.com/AdminBroOptions.html#locale
> 
> Here, **Items** is the Resource name as well as a model name, and **ownerid** is the property. ![image](https://user-images.githubusercontent.com/82202278/114496773-4be2eb00-9c3e-11eb-88cc-0bc807551432.png) ![ColumnChange](https://user-images.githubusercontent.com/82202278/114496907-8e0c2c80-9c3e-11eb-911f-80d06dce11b4.png) It still remains same. Is there any alternate way to do that?

Mine also doesn't work. any updates on this on how to actually rename it?

**Comment by dziraf** [comment]
Do your properties have uppercased names? Could you share your model schema?

**Comment by lumayara** [comment]
@dziraf Yes it's all uppercase.. I am using an old db.
```
const Sequelize = require('sequelize');
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Tolerable_Intake', {
     INTAKE_ID: {
      autoIncrement: true,
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    },
TI_MODIFIEDBY: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    DOCUMENT_URL: {
      type: DataTypes.TEXT,
      allowNull: true
    }
  }, {
    sequelize,
    tableName: 'Tolerable_Intake',
    schema: 'dbo',
    timestamps: false,
    indexes: [
      {
        name: "PK__TBL_TOLE__BB5D29EA7A3FD38E",
        unique: true,
        fields: [
          { name: "INTAKE_ID" },
        ]
      },
    ]
  });
};

```

**Comment by lumayara** [comment]
Still no luck for me...

**Comment by jbotejue** [comment]
I have the same issue. I can hide the field, but I can not rename it.

**Comment by jbotejue** [comment]
No luck for me either. I can hider the issue, but I am not able to rename it.
....
properties: {
      id: {
        isVisible: false,
      },
      fPublisherID: {isVisible : false}, // works
....
 however if I do:
properties: {
      id: {
        isVisible: false,
      },
      fPublisherID:  "Published Status" // does not change the name.

@lumayara  where you able to resolve ?

**Comment by dhammikab** [comment]
No luck for me either. I can hide the field, but I am not able to rename it.
eg: 
....
 properties: {
 id: {
 isVisible: false,
 },
 fPublisherID: {isVisible : false}, // works
 ....
 
however if I do:
 properties: {
 id: {
 isVisible: false,
 },
 fPublisherID: "Published Status" // does not change the name.

 @lumayara were you able to resolve this?

**Comment by lumayara** [comment]
@dhammikab No luck for me. Can anyone else?

**Comment by krzysztofstudniarek** [comment]
@lumayara did you check here: https://github.com/SoftwareBrothers/adminjs/issues/1169#issuecomment-1181831026 ? 😉
