### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by AlexeyVlasenko** [SoftwareBrothers/admin-bro#808]
**Describe the bug**
Admin panel shows white screen due to requested bundles are not exists
I've got `Error: ENOENT: no such file or directory` for next:
```
/admin-bro/lib/frontend/assets/scripts/global-bundle.development.js
/admin-bro/lib/frontend/assets/scripts/app-bundle.development.js'
```

**Installed libraries and their versions**

* "@admin-bro/express": "^3.1.0"
* "@admin-bro/mongoose": "^1.1.0",
* "admin-bro": "^3.4.0",

**Expected behavior**
Admin panel should load :D

**AdminBroOptions with schema**
```
{
  rootPath: '/admin',
  resources: [
    {
      resource: SomeRes,
    },
  ],
}
```

**Desktop (please complete the following information if relevant):**
 - OS: MacOS
 - Browser Chrome
 - Version 89.0.4389.114 

**Additional context**
Another project with ABSOLUTELY same configuration of AdminBro works perfectly.
Cleaning node_modules don't resolve issue
Cleaning cache don't resolve issue

**Comment by dziraf** [comment]
When you go to `/admin-bro/lib/frontend/assets/scripts/` directory, is it empty?

**Comment by AlexeyVlasenko** [comment]
> When you go to `/admin-bro/lib/frontend/assets/scripts/` directory, is it empty?

Yep, it's empty.

**Comment by AlexeyVlasenko** [comment]
Also `assets` folder doesn't exists

**Comment by dziraf** [comment]
1. Can you add following lines after you create AdminBro instance:
```
if (process.env.NODE_ENV === 'production') adminBro.initialize();
else adminBro.watch();
```

2. Can you `rm -rf node_modules && yarn install` in your old/working project and see if it still works there after reinstallation?

3. Can you share your routes specification, etc?

**Comment by AlexeyVlasenko** [comment]
1) already tried, bundler bundles only 1 file (but still no folders)
![image](https://user-images.githubusercontent.com/25363536/114016215-474fb880-9873-11eb-958b-065d51c3cea2.png)

2) will try in 5 min.
3) I've commented all middlewares/another routes to make sure that it's not trouble in it, so my express app like:

```
  app.use(adminBro.options.rootPath, adminBroRoute);
  app.listen(process.env.PORT || 3000);
```

**Comment by AlexeyVlasenko** [comment]
> 1. Can you add following lines after you create AdminBro instance:
> 
> ```
> if (process.env.NODE_ENV === 'production') adminBro.initialize();
> else adminBro.watch();
> ```
> 
> 1. Can you `rm -rf node_modules && yarn install` in your old/working project and see if it still works there after reinstallation?
> 2. Can you share your routes specification, etc?

2. Tried, all works perfectly :(

**Comment by dziraf** [comment]
Do you use `yarn` or `npm`? I think this might be yarn/npm issue. I've just checked and those files are included in the package (they are pre-bundled) so whenever you install they should be included.

My other suggestions to try:
1. Run `yarn cache clean` / `npm cache clean --force`
2. Remove `.yarnclean`if it exists in your project
3. Delete `yarn.lock` / `package-lock.json`
4. `rm -rf node_modules` and `yarn install --force` (or npm equivalent)

**Comment by AlexeyVlasenko** [comment]
> Do you use `yarn` or `npm`? I think this might be yarn/npm issue. I've just checked and those files are included in the package (they are pre-bundled) so whenever you install they should be included.
> 
> My other suggestions to try:
> 
> 1. Run `yarn cache clean` / `npm cache clean --force`
> 2. Remove `.yarnclean`if it exists in your project
> 3. Delete `yarn.lock` / `package-lock.json`
> 4. `rm -rf node_modules` and `yarn install --force` (or npm equivalent)
> 
> Could you also share the output from when you run `yarn/npm install` or `yarn add admin-bro`?

Wow, looks like it was an issue with `.yarnclean`
On my other project, there is no auto-clean option during install.

Removing `.yarnclean` and force reinstall modules helps!
Thanks for great support!

**Comment by dziraf** [comment]
I'm not sure how yarnclean exactly works, but those two files aren't imported anywhere in the codebase (they're just prebundled for your own app to use) so they could've been considered unneeded
