### ISSUE TITLE
Can't resolve 'fsevents' error

### ISSUE THREAD

**Issue by alvaropaco** [SoftwareBrothers/admin-bro#809]
**Describe the bug**
I'm stuck when I try to compile my TS react project with webpack. I'm trying to deploy my AdminBro to a serverless lambda aws environment  with the server-webpack. I'm receiving an error related to the `fsevents`:
`ERROR in .../node_modules/rollup/dist/es/shared/rollup.js
Module not found: Error: Can't resolve 'fsevents' in '.../node_modules/rollup/dist/es/shared'`

**Installed libraries and their versions**

* admin-bro^3.4.0
* @admin-bro/express^3.1.0"
* @admin-bro/sequelize^1.2.1
* serverless-webpack

I've configured the serverles-webpack plugin in my `serverless.yml` as well to configure my weback like:
```
{
  "entry": {
    "index": "./index.ts"
  },
  "devtool": "source-map",
  "resolve": {
    "extensions": [
      ".js",
      ".jsx",
      ".json",
      ".ts",
      ".tsx"
    ]
  },
  "output": {
    "libraryTarget": "commonjs",
    "path": "/.../.webpack",
    "filename": "[name].js"
  },
  "target": "node",
  "module": {
    "rules": [
      {
        "test": {},
        "use": [
          {
            "loader": "ts-loader"
          },
          {
            "loader": "script-loader"
          }
        ]
      },
      {
        "test": {},
        "exclude": {},
        "loader": "ts-loader"
      },
      {
        "test": {},
        "loader": "node-loader",
        "options": {
          "flags": 2
        }
      }
    ]
  },
  "mode": "production",
  "node": {
    "__dirname": false
  },
  "externals": {
    "AdminBro": "admin-bro"
  }
}
```

**To Reproduce**
1. Go and run `serverless webpack`

**Expected behavior**
Up and run a serverless offline lambdas with the routes to the AdminBro.

**Desktop (please complete the following information if relevant):**
 - OS: Ubuntu
 - Browser: chrome
 - Version:  89.0.4389.90

**Comment by dziraf** [comment]
I think we don't use AWS Lambda in any of our projects that use AdminBro so my help will be kinda limited, but my guess is that webpack could be conflicting with rollup which is used by admin. Whenever you start a server, it runs a script to build user (custom) components before they're served. What you can try is:

You could try to pre-bundle or bundle your AdminBro js files before deploying like here:
https://github.com/SoftwareBrothers/admin-bro/blob/master/packages/admin-bro-demo/src/utils/bundle.ts

Upload this to i. e. S3. and set `assetsCDN` when instantiating AdminBro: https://adminbro.com/AdminBroOptions.html#assetsCDN

Set env: `ADMIN_BRO_SKIP_BUNDLE` to `'true'` (this has to be a string 'true') on your server - this will skip bundling on server start.

Deploy and attempt to start admin

**Comment by alvaropaco** [comment]
Thank you @dziraf . I solved this problem including the admin-bro and fsevents at the webpack externals. That way the webpack ski the admin-bro compilation.
