### ISSUE TITLE
Not getting other columns value using foreign key from table

### ISSUE THREAD

**Issue by RudrikaJnext** [SoftwareBrothers/admin-bro#811]
I have two tables one is Users and the second is Products,

**Table: Users**
-> Column: id, userName, password, firstName

&

**Table: Products**
-> Column: id, productName, userId

I have assign foreign key to get Users(id) -> userId

But I want the userName instead of userId in the Products table. 

Is it possible to do in admin-bro? or is there any way to add mannual query for it?

**Comment by dziraf** [comment]
In your Users resource add `isTitle: true` to `userName` property, i. e.

```
const UserResource = {
  resource: User,
  options: {
    ...,
    properties: {
      userName: { isTitle: true },
    },
  },
};
```

**Comment by RudrikaJnext** [comment]
@dziraf Thank you for the solution! It works perfectly!
