### ISSUE TITLE
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by GDmail91** [SoftwareBrothers/admin-bro#816]
If edit a record within array what has some unicodes then occured exception with error page.
It's not occured neither below 4.0.0 and demo page.
Probably it's version 4's problem.

details are below.
Message: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

Screenshots:
![array edit text encoding error 1](https://user-images.githubusercontent.com/11922156/114826504-8bf2cb00-9e02-11eb-8935-22497b72d8d9.PNG)

**Comment by dziraf** [comment]
Closing because the fix is merged
