### ISSUE TITLE
Including the populated references in the frontend

### ISSUE THREAD

**Issue by alvaropaco** [SoftwareBrothers/admin-bro#823]
**Describe the bug**
I don't know if it is a bug, but I want to include a specific field of a referenced relation in the table of the list action For example, I've two tables, "Users" and "Names". The "Users" table has a foreign key "name_id" that's reference to the id field at the table "Names". It is a belongsTo relationship between Users and Names. I've used Sequelize as the ORM and the ` @admin-bro/sequelize` to connect to the AdminBro. I've created the the relation as:

```Users
db?.models.Users.belongsTo(db.models.Name, {
      foreignKey: 'name_id', targetKey: 'id',
});
```
This works well, but my problem is that is displaying the id of the "Names" record as a link, but I want to display the name in the field  and not the id:

![issue-adminbro](https://user-images.githubusercontent.com/3423410/116102104-c707c080-a684-11eb-9500-00e01ce9b9a6.png)

**Installed libraries and their versions**

* admin-bro@3.4.0
* @admin-bro/sequelize@1.2.1
* @admin-bro/express@3.1.0

**To Reproduce**
1. Create a new project with the AmdinBro and Sequelize;
2. Create the db schema using two tables with a 1:1 relationship;
3. Include a relation between the tables as a belongsTo relation;
4. See the problem in the list of the Users table.

**Expected behavior**
Display the name at the Users list and not the id of the relation.

**Screenshots**
![FireShot Capture 043 - Company - hiq-local](https://user-images.githubusercontent.com/3423410/116103454-fb2fb100-a685-11eb-9a29-62f6cf001a40.png)

**AdminBroOptions with schema**
```JSON
{
  "resources": [
    {
      "options": {
        "navigation": {
          "name": "Menu",
          "icon": "Menu"
        },
        "actions": {
          "list": {}
        }
      }
    },
    {
      "options": {
        "navigation": {
          "name": "Menu",
          "icon": "Menu"
        },
        "actions": {
          "list": {}
        }
      }
    },
    {
      "options": {
        "navigation": {
          "name": "Menu",
          "icon": "Menu"
        },
        "actions": {
          "list": {}
        }
      }
    }
  ],
  "rootPath": "/"
}
```

**Desktop (please complete the following information if relevant):**
 - OS: Ubuntu
 - Browser: chrome
 - Version: 89.0.4389.90

**Comment by dziraf** [comment]
In your `Name` resource options add `isTitle: true` to a property that's supposed to be used as a title.
https://adminbro.com/PropertyOptions.html#isTitle

**Comment by alvaropaco** [comment]
Thank you @dziraf!
