### ISSUE TITLE
Refused to execute script errors

### ISSUE THREAD

**Issue by derkweijers** [SoftwareBrothers/admin-bro#83]
I've upgraded from 0.6.0 to 0.8.2 and now I'm getting 2 errors that prevent the UI from loading after login (buildAuthenticatedRouter):

`Refused to execute script from 'http://localhost:3000/admin/frontend/assets/app.bundle.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`

`Refused to execute script from 'http://localhost:3000/admin/frontend/assets/components.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

I'm not entirely sure what's causing this, unfortunately.
I'm using admin-bro-expressjs and admin-bro-mongoose as well.

**Comment by wojtek-krysiak** [comment]
it might be a problem with expressjs plugin - will check it out today and let you know

**Comment by wojtek-krysiak** [comment]
Which version of admin-bro-expressjs are you using? (latest?)

**Comment by derkweijers** [comment]
I believe so, yes. 0.1.6.

**Comment by wojtek-krysiak** [comment]
check out the AdminBro v 0.8.3 and admin-bro-expressjs v0.1.7 and let me know if that helped

**Comment by derkweijers** [comment]
Most definitely worked. Thanks!
