### ISSUE TITLE
Not able to update Records - Node + AdminBro + Sequalzie.

### ISSUE THREAD

**Issue by vaibhavmagon** [SoftwareBrothers/admin-bro#842]
**Issue**
The records are not updating via Admin Bro. Listing, view and delete is working fine.

**Installed libraries and their versions**
"@admin-bro/express": "^3.1.0"
"@admin-bro/sequelize": "^1.2.1"
"admin-bro": "^4.0.1"

**To Reproduce**
1. Go to List.
2. Click on individual list item.
3. Click on Edit.
4. The API call doesn't hit the server. The Call goes in Pending state.

**Expected behavior**
The API should update the record in the database.

**Screenshots**
<img src="https://i.ibb.co/xm9YPYv/Screenshot-2021-05-17-at-5-38-28-PM.png"/>

**AdminBroOptions with schema**
```
const AdminBro = require('admin-bro');
const AdminBroExpress = require('@admin-bro/express');
  const AdminBroSequelize = require('@admin-bro/sequelize')
  AdminBro.registerAdapter(AdminBroSequelize);
  const db = await require('./../database/models');
  const contentNavigation = {
    name: 'Logistics',
    icon: 'Accessibility',
  }
  const adminBro = new AdminBro({
    databases: [db],
    resources:[
      { resource: db.PincodeServiceability, options: { navigation: contentNavigation } },
    ],
    rootPath: '/admin',
    branding: {
      companyName: CONSTANTS.assets.companyName,
      favicon: CONSTANTS.assets.favicon,
      logo: CONSTANTS.assets.logo,
      softwareBrothers: false
    }
  });

  app.use(adminBro.options.rootPath, basicAuth ({
    users: CONSTANTS.admin.auth,
    challenge: true,
  }), AdminBroExpress.buildRouter(adminBro));
```

**Comment by dziraf** [comment]
Check whether you're calling `app.use(bodyParser.json())` before setting up admin router and if so, move it after

**Comment by vaibhavmagon** [comment]
Worked beautifully! @dziraf :-)
